// ==================================================
// RTL generated by RapidStream
//
// Copyright 2024 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
/**   Generated by RapidStream   **/
module __merged_task_fsm_SLOT_X0Y0_TO_SLOT_X0Y0 (
    input wire         Linear_Layer_i4xi4_q_0_ap_done,
    input wire         Linear_Layer_i4xi4_q_0_ap_idle,
    input wire         Linear_Layer_i4xi4_q_0_ap_ready,
    output wire [31:0] __tapa_fsm_unit_Linear_Layer_i4xi4_q_0___seq_len__q0,
    output wire        __tapa_fsm_unit_Linear_Layer_i4xi4_q_0__ap_start,
    input wire         __tapa_fsm_unit_ap_rst_n,
    output wire [31:0] __tapa_fsm_unit_dequant_layer_q_int_fp32_0___seq_len__q0,
    output wire        __tapa_fsm_unit_dequant_layer_q_int_fp32_0__ap_start,
    input wire         __tapa_fsm_unit_global_fsm_ap_done,
    input wire         __tapa_fsm_unit_global_fsm_ap_start,
    input wire  [63:0] __tapa_fsm_unit_global_fsm_s_input_mmap_offset,
    input wire  [63:0] __tapa_fsm_unit_global_fsm_s_output_mmap_offset,
    input wire  [63:0] __tapa_fsm_unit_global_fsm_s_quant_weight_mmap_offset,
    input wire  [31:0] __tapa_fsm_unit_global_fsm_s_seq_len,
    input wire  [63:0] __tapa_fsm_unit_global_fsm_s_weight_s_sum_mmap_offset,
    output wire [31:0] __tapa_fsm_unit_input_loader_r1_ln_iembed_fp32_0___seq_len__q0,
    output wire        __tapa_fsm_unit_input_loader_r1_ln_iembed_fp32_0__ap_start,
    output wire [63:0] __tapa_fsm_unit_input_loader_r1_ln_iembed_fp32_0__mmap_offset_q0,
    output wire        __tapa_fsm_unit_is_done_Linear_Layer_i4xi4_q_0,
    output wire        __tapa_fsm_unit_is_done_dequant_layer_q_int_fp32_0,
    output wire        __tapa_fsm_unit_is_done_input_loader_r1_ln_iembed_fp32_0,
    output wire        __tapa_fsm_unit_is_done_output_drainer_q_fp32_0,
    output wire        __tapa_fsm_unit_is_done_quant_layer_r1_ln_iembed_fp32_int4_0,
    output wire        __tapa_fsm_unit_is_done_weight_loader_wq_0,
    output wire        __tapa_fsm_unit_is_done_weight_s_loader_wq_0,
    output wire [63:0] __tapa_fsm_unit_output_drainer_q_fp32_0___output_mmap_offset__q0,
    output wire [31:0] __tapa_fsm_unit_output_drainer_q_fp32_0___seq_len__q0,
    output wire        __tapa_fsm_unit_output_drainer_q_fp32_0__ap_start,
    output wire        __tapa_fsm_unit_quant_layer_r1_ln_iembed_fp32_int4_0__ap_start,
    output wire [31:0] __tapa_fsm_unit_quant_layer_r1_ln_iembed_fp32_int4_0__seq_len_q0,
    output wire [63:0] __tapa_fsm_unit_weight_loader_wq_0___quant_mmap_offset__q0,
    output wire [31:0] __tapa_fsm_unit_weight_loader_wq_0___seq_len__q0,
    output wire        __tapa_fsm_unit_weight_loader_wq_0__ap_start,
    output wire [63:0] __tapa_fsm_unit_weight_s_loader_wq_0___s_sum_mmap_offset__q0,
    output wire [31:0] __tapa_fsm_unit_weight_s_loader_wq_0___seq_len__q0,
    output wire        __tapa_fsm_unit_weight_s_loader_wq_0__ap_start,
    input wire         ap_clk,
    input wire         dequant_layer_q_int_fp32_0_ap_done,
    input wire         dequant_layer_q_int_fp32_0_ap_idle,
    input wire         dequant_layer_q_int_fp32_0_ap_ready,
    input wire         input_loader_r1_ln_iembed_fp32_0_ap_done,
    input wire         input_loader_r1_ln_iembed_fp32_0_ap_idle,
    input wire         input_loader_r1_ln_iembed_fp32_0_ap_ready,
    input wire         output_drainer_q_fp32_0_ap_done,
    input wire         output_drainer_q_fp32_0_ap_idle,
    input wire         output_drainer_q_fp32_0_ap_ready,
    input wire         quant_layer_r1_ln_iembed_fp32_int4_0_ap_done,
    input wire         quant_layer_r1_ln_iembed_fp32_int4_0_ap_idle,
    input wire         quant_layer_r1_ln_iembed_fp32_int4_0_ap_ready,
    input wire         weight_loader_wq_0_ap_done,
    input wire         weight_loader_wq_0_ap_idle,
    input wire         weight_loader_wq_0_ap_ready,
    input wire         weight_s_loader_wq_0_ap_done,
    input wire         weight_s_loader_wq_0_ap_idle,
    input wire         weight_s_loader_wq_0_ap_ready
);




__task_fsm_Linear_Layer_i4xi4_q_0 __tapa_fsm_unit_Linear_Layer_i4xi4_q_0 /**   Generated by RapidStream   **/ (
    .ap_clk                (ap_clk),
    .ap_rst_n              (__tapa_fsm_unit_ap_rst_n),
    .global_fsm_ap_done    (__tapa_fsm_unit_global_fsm_ap_done),
    .global_fsm_ap_start   (__tapa_fsm_unit_global_fsm_ap_start),
    .global_fsm_s_seq_len  (__tapa_fsm_unit_global_fsm_s_seq_len),
    .task_ap_done          (Linear_Layer_i4xi4_q_0_ap_done),
    .task_ap_idle          (Linear_Layer_i4xi4_q_0_ap_idle),
    .task_ap_ready         (Linear_Layer_i4xi4_q_0_ap_ready),
    .task_ap_start         (__tapa_fsm_unit_Linear_Layer_i4xi4_q_0__ap_start),
    .task_s_seq_len        (__tapa_fsm_unit_Linear_Layer_i4xi4_q_0___seq_len__q0),
    .to_global_fsm_is_done (__tapa_fsm_unit_is_done_Linear_Layer_i4xi4_q_0)
);


__task_fsm_dequant_layer_q_int_fp32_0 __tapa_fsm_unit_dequant_layer_q_int_fp32_0 /**   Generated by RapidStream   **/ (
    .ap_clk                (ap_clk),
    .ap_rst_n              (__tapa_fsm_unit_ap_rst_n),
    .global_fsm_ap_done    (__tapa_fsm_unit_global_fsm_ap_done),
    .global_fsm_ap_start   (__tapa_fsm_unit_global_fsm_ap_start),
    .global_fsm_s_seq_len  (__tapa_fsm_unit_global_fsm_s_seq_len),
    .task_ap_done          (dequant_layer_q_int_fp32_0_ap_done),
    .task_ap_idle          (dequant_layer_q_int_fp32_0_ap_idle),
    .task_ap_ready         (dequant_layer_q_int_fp32_0_ap_ready),
    .task_ap_start         (__tapa_fsm_unit_dequant_layer_q_int_fp32_0__ap_start),
    .task_s_seq_len        (__tapa_fsm_unit_dequant_layer_q_int_fp32_0___seq_len__q0),
    .to_global_fsm_is_done (__tapa_fsm_unit_is_done_dequant_layer_q_int_fp32_0)
);


__task_fsm_input_loader_r1_ln_iembed_fp32_0 __tapa_fsm_unit_input_loader_r1_ln_iembed_fp32_0 /**   Generated by RapidStream   **/ (
    .ap_clk                         (ap_clk),
    .ap_rst_n                       (__tapa_fsm_unit_ap_rst_n),
    .global_fsm_ap_done             (__tapa_fsm_unit_global_fsm_ap_done),
    .global_fsm_ap_start            (__tapa_fsm_unit_global_fsm_ap_start),
    .global_fsm_s_input_mmap_offset (__tapa_fsm_unit_global_fsm_s_input_mmap_offset),
    .global_fsm_s_seq_len           (__tapa_fsm_unit_global_fsm_s_seq_len),
    .task_ap_done                   (input_loader_r1_ln_iembed_fp32_0_ap_done),
    .task_ap_idle                   (input_loader_r1_ln_iembed_fp32_0_ap_idle),
    .task_ap_ready                  (input_loader_r1_ln_iembed_fp32_0_ap_ready),
    .task_ap_start                  (__tapa_fsm_unit_input_loader_r1_ln_iembed_fp32_0__ap_start),
    .task_s_input_mmap_offset       (__tapa_fsm_unit_input_loader_r1_ln_iembed_fp32_0__mmap_offset_q0),
    .task_s_seq_len                 (__tapa_fsm_unit_input_loader_r1_ln_iembed_fp32_0___seq_len__q0),
    .to_global_fsm_is_done          (__tapa_fsm_unit_is_done_input_loader_r1_ln_iembed_fp32_0)
);


__task_fsm_output_drainer_q_fp32_0 __tapa_fsm_unit_output_drainer_q_fp32_0 /**   Generated by RapidStream   **/ (
    .ap_clk                          (ap_clk),
    .ap_rst_n                        (__tapa_fsm_unit_ap_rst_n),
    .global_fsm_ap_done              (__tapa_fsm_unit_global_fsm_ap_done),
    .global_fsm_ap_start             (__tapa_fsm_unit_global_fsm_ap_start),
    .global_fsm_s_output_mmap_offset (__tapa_fsm_unit_global_fsm_s_output_mmap_offset),
    .global_fsm_s_seq_len            (__tapa_fsm_unit_global_fsm_s_seq_len),
    .task_ap_done                    (output_drainer_q_fp32_0_ap_done),
    .task_ap_idle                    (output_drainer_q_fp32_0_ap_idle),
    .task_ap_ready                   (output_drainer_q_fp32_0_ap_ready),
    .task_ap_start                   (__tapa_fsm_unit_output_drainer_q_fp32_0__ap_start),
    .task_s_output_mmap_offset       (__tapa_fsm_unit_output_drainer_q_fp32_0___output_mmap_offset__q0),
    .task_s_seq_len                  (__tapa_fsm_unit_output_drainer_q_fp32_0___seq_len__q0),
    .to_global_fsm_is_done           (__tapa_fsm_unit_is_done_output_drainer_q_fp32_0)
);


__task_fsm_quant_layer_r1_ln_iembed_fp32_int4_0 __tapa_fsm_unit_quant_layer_r1_ln_iembed_fp32_int4_0 /**   Generated by RapidStream   **/ (
    .ap_clk                (ap_clk),
    .ap_rst_n              (__tapa_fsm_unit_ap_rst_n),
    .global_fsm_ap_done    (__tapa_fsm_unit_global_fsm_ap_done),
    .global_fsm_ap_start   (__tapa_fsm_unit_global_fsm_ap_start),
    .global_fsm_s_seq_len  (__tapa_fsm_unit_global_fsm_s_seq_len),
    .task_ap_done          (quant_layer_r1_ln_iembed_fp32_int4_0_ap_done),
    .task_ap_idle          (quant_layer_r1_ln_iembed_fp32_int4_0_ap_idle),
    .task_ap_ready         (quant_layer_r1_ln_iembed_fp32_int4_0_ap_ready),
    .task_ap_start         (__tapa_fsm_unit_quant_layer_r1_ln_iembed_fp32_int4_0__ap_start),
    .task_s_seq_len        (__tapa_fsm_unit_quant_layer_r1_ln_iembed_fp32_int4_0__seq_len_q0),
    .to_global_fsm_is_done (__tapa_fsm_unit_is_done_quant_layer_r1_ln_iembed_fp32_int4_0)
);


__task_fsm_weight_loader_wq_0 __tapa_fsm_unit_weight_loader_wq_0 /**   Generated by RapidStream   **/ (
    .ap_clk                                (ap_clk),
    .ap_rst_n                              (__tapa_fsm_unit_ap_rst_n),
    .global_fsm_ap_done                    (__tapa_fsm_unit_global_fsm_ap_done),
    .global_fsm_ap_start                   (__tapa_fsm_unit_global_fsm_ap_start),
    .global_fsm_s_quant_weight_mmap_offset (__tapa_fsm_unit_global_fsm_s_quant_weight_mmap_offset),
    .global_fsm_s_seq_len                  (__tapa_fsm_unit_global_fsm_s_seq_len),
    .task_ap_done                          (weight_loader_wq_0_ap_done),
    .task_ap_idle                          (weight_loader_wq_0_ap_idle),
    .task_ap_ready                         (weight_loader_wq_0_ap_ready),
    .task_ap_start                         (__tapa_fsm_unit_weight_loader_wq_0__ap_start),
    .task_s_quant_weight_mmap_offset       (__tapa_fsm_unit_weight_loader_wq_0___quant_mmap_offset__q0),
    .task_s_seq_len                        (__tapa_fsm_unit_weight_loader_wq_0___seq_len__q0),
    .to_global_fsm_is_done                 (__tapa_fsm_unit_is_done_weight_loader_wq_0)
);


__task_fsm_weight_s_loader_wq_0 __tapa_fsm_unit_weight_s_loader_wq_0 /**   Generated by RapidStream   **/ (
    .ap_clk                                (ap_clk),
    .ap_rst_n                              (__tapa_fsm_unit_ap_rst_n),
    .global_fsm_ap_done                    (__tapa_fsm_unit_global_fsm_ap_done),
    .global_fsm_ap_start                   (__tapa_fsm_unit_global_fsm_ap_start),
    .global_fsm_s_seq_len                  (__tapa_fsm_unit_global_fsm_s_seq_len),
    .global_fsm_s_weight_s_sum_mmap_offset (__tapa_fsm_unit_global_fsm_s_weight_s_sum_mmap_offset),
    .task_ap_done                          (weight_s_loader_wq_0_ap_done),
    .task_ap_idle                          (weight_s_loader_wq_0_ap_idle),
    .task_ap_ready                         (weight_s_loader_wq_0_ap_ready),
    .task_ap_start                         (__tapa_fsm_unit_weight_s_loader_wq_0__ap_start),
    .task_s_seq_len                        (__tapa_fsm_unit_weight_s_loader_wq_0___seq_len__q0),
    .task_s_weight_s_sum_mmap_offset       (__tapa_fsm_unit_weight_s_loader_wq_0___s_sum_mmap_offset__q0),
    .to_global_fsm_is_done                 (__tapa_fsm_unit_is_done_weight_s_loader_wq_0)
);

endmodule  // __merged_task_fsm_SLOT_X0Y0_TO_SLOT_X0Y0