// ==================================================
// RTL generated by RapidStream
//
// Copyright 2024 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
/**   Generated by RapidStream   **/
module __rs_pt_control_s_axi_U_5 #(
    parameter C_S_AXI_ADDR_WIDTH                   = 7,
    parameter C_S_AXI_DATA_WIDTH                   = 32,
    parameter ADDR_AP_CTRL                         = 7'h00,
    parameter ADDR_GIE                             = 7'h04,
    parameter ADDR_IER                             = 7'h08,
    parameter ADDR_ISR                             = 7'h0c,
    parameter ADDR_INPUT_MMAP_OFFSET_DATA_0        = 7'h10,
    parameter ADDR_INPUT_MMAP_OFFSET_DATA_1        = 7'h14,
    parameter ADDR_INPUT_MMAP_OFFSET_CTRL          = 7'h18,
    parameter ADDR_QUANT_WEIGHT_MMAP_OFFSET_DATA_0 = 7'h1c,
    parameter ADDR_QUANT_WEIGHT_MMAP_OFFSET_DATA_1 = 7'h20,
    parameter ADDR_QUANT_WEIGHT_MMAP_OFFSET_CTRL   = 7'h24,
    parameter ADDR_WEIGHT_S_SUM_MMAP_OFFSET_DATA_0 = 7'h28,
    parameter ADDR_WEIGHT_S_SUM_MMAP_OFFSET_DATA_1 = 7'h2c,
    parameter ADDR_WEIGHT_S_SUM_MMAP_OFFSET_CTRL   = 7'h30,
    parameter ADDR_OUTPUT_MMAP_OFFSET_DATA_0       = 7'h34,
    parameter ADDR_OUTPUT_MMAP_OFFSET_DATA_1       = 7'h38,
    parameter ADDR_OUTPUT_MMAP_OFFSET_CTRL         = 7'h3c,
    parameter ADDR_SEQ_LEN_DATA_0                  = 7'h40,
    parameter ADDR_SEQ_LEN_CTRL                    = 7'h44,
    parameter WRIDLE                               = 2'd0,
    parameter WRDATA                               = 2'd1,
    parameter WRRESP                               = 2'd2,
    parameter WRRESET                              = 2'd3,
    parameter RDIDLE                               = 2'd0,
    parameter RDDATA                               = 2'd1,
    parameter RDRESET                              = 2'd2,
    parameter ADDR_BITS                            = 7
) (
    input wire  ACLK,
    input wire  __rs_pt_interrupt,
    output wire interrupt
);




__rs_pass_through #(
    .WIDTH (1)
) __rs_pt_QuantWrapper_Linear_Layer_q_tb_control_s_axi_interrupt_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_interrupt),
    .dout (interrupt)
);

endmodule  // __rs_pt_control_s_axi_U_5