// ==================================================
// RTL generated by RapidStream
//
// Copyright 2024 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
/**   Generated by RapidStream   **/
module __rs_pt_weight_s_loader_wq_0_0 #(
    parameter ap_ST_fsm_state1                       = 3'd1,
    parameter ap_ST_fsm_state2                       = 3'd2,
    parameter ap_ST_fsm_state3                       = 3'd4,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_ID_WIDTH     = 1,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_ADDR_WIDTH   = 64,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_DATA_WIDTH   = 64,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_AWUSER_WIDTH = 1,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_ARUSER_WIDTH = 1,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_WUSER_WIDTH  = 1,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_RUSER_WIDTH  = 1,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_BUSER_WIDTH  = 1,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_USER_VALUE   = 0,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_PROT_VALUE   = 0,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_CACHE_VALUE  = 3,
    parameter C_M_AXI_DATA_WIDTH                     = 32,
    parameter C_M_AXI_WEIGHT_S_SUM_MMAP_WSTRB_WIDTH  = 32'd8,
    parameter C_M_AXI_WSTRB_WIDTH                    = 32'd4
) (
    input wire  [  (C_M_AXI_WEIGHT_S_SUM_MMAP_ADDR_WIDTH - 1):0] __rs_pt_m_axi_weight_s_sum_mmap_ARADDR,
    input wire  [                                           1:0] __rs_pt_m_axi_weight_s_sum_mmap_ARBURST,
    input wire  [                                           3:0] __rs_pt_m_axi_weight_s_sum_mmap_ARCACHE,
    input wire  [    (C_M_AXI_WEIGHT_S_SUM_MMAP_ID_WIDTH - 1):0] __rs_pt_m_axi_weight_s_sum_mmap_ARID,
    input wire  [                                           7:0] __rs_pt_m_axi_weight_s_sum_mmap_ARLEN,
    input wire  [                                           1:0] __rs_pt_m_axi_weight_s_sum_mmap_ARLOCK,
    input wire  [                                           2:0] __rs_pt_m_axi_weight_s_sum_mmap_ARPROT,
    input wire  [                                           3:0] __rs_pt_m_axi_weight_s_sum_mmap_ARQOS,
    output wire                                                  __rs_pt_m_axi_weight_s_sum_mmap_ARREADY,
    input wire  [                                           3:0] __rs_pt_m_axi_weight_s_sum_mmap_ARREGION,
    input wire  [                                           2:0] __rs_pt_m_axi_weight_s_sum_mmap_ARSIZE,
    input wire  [(C_M_AXI_WEIGHT_S_SUM_MMAP_ARUSER_WIDTH - 1):0] __rs_pt_m_axi_weight_s_sum_mmap_ARUSER,
    input wire                                                   __rs_pt_m_axi_weight_s_sum_mmap_ARVALID,
    input wire                                                   ap_clk,
    input wire                                                   ap_rst_n,
    output wire [  (C_M_AXI_WEIGHT_S_SUM_MMAP_ADDR_WIDTH - 1):0] m_axi_weight_s_sum_mmap_ARADDR,
    output wire [                                           1:0] m_axi_weight_s_sum_mmap_ARBURST,
    output wire [                                           3:0] m_axi_weight_s_sum_mmap_ARCACHE,
    output wire [    (C_M_AXI_WEIGHT_S_SUM_MMAP_ID_WIDTH - 1):0] m_axi_weight_s_sum_mmap_ARID,
    output wire [                                           7:0] m_axi_weight_s_sum_mmap_ARLEN,
    output wire [                                           1:0] m_axi_weight_s_sum_mmap_ARLOCK,
    output wire [                                           2:0] m_axi_weight_s_sum_mmap_ARPROT,
    output wire [                                           3:0] m_axi_weight_s_sum_mmap_ARQOS,
    input wire                                                   m_axi_weight_s_sum_mmap_ARREADY,
    output wire [                                           3:0] m_axi_weight_s_sum_mmap_ARREGION,
    output wire [                                           2:0] m_axi_weight_s_sum_mmap_ARSIZE,
    output wire [(C_M_AXI_WEIGHT_S_SUM_MMAP_ARUSER_WIDTH - 1):0] m_axi_weight_s_sum_mmap_ARUSER,
    output wire                                                  m_axi_weight_s_sum_mmap_ARVALID
);




__rs_pass_through #(
    .WIDTH (( ( C_M_AXI_WEIGHT_S_SUM_MMAP_ADDR_WIDTH - 1 ) - ( 0 ) + 1 ))
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARADDR_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARADDR),
    .dout (m_axi_weight_s_sum_mmap_ARADDR)
);


__rs_pass_through #(
    .WIDTH (2)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARBURST_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARBURST),
    .dout (m_axi_weight_s_sum_mmap_ARBURST)
);


__rs_pass_through #(
    .WIDTH (4)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARCACHE_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARCACHE),
    .dout (m_axi_weight_s_sum_mmap_ARCACHE)
);


__rs_pass_through #(
    .WIDTH (( ( C_M_AXI_WEIGHT_S_SUM_MMAP_ID_WIDTH - 1 ) - ( 0 ) + 1 ))
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARID_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARID),
    .dout (m_axi_weight_s_sum_mmap_ARID)
);


__rs_pass_through #(
    .WIDTH (8)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARLEN_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARLEN),
    .dout (m_axi_weight_s_sum_mmap_ARLEN)
);


__rs_pass_through #(
    .WIDTH (2)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARLOCK_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARLOCK),
    .dout (m_axi_weight_s_sum_mmap_ARLOCK)
);


__rs_pass_through #(
    .WIDTH (3)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARPROT_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARPROT),
    .dout (m_axi_weight_s_sum_mmap_ARPROT)
);


__rs_pass_through #(
    .WIDTH (4)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARQOS_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARQOS),
    .dout (m_axi_weight_s_sum_mmap_ARQOS)
);


__rs_pass_through #(
    .WIDTH (1)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARREADY_inst /**   Generated by RapidStream   **/ (
    .din  (m_axi_weight_s_sum_mmap_ARREADY),
    .dout (__rs_pt_m_axi_weight_s_sum_mmap_ARREADY)
);


__rs_pass_through #(
    .WIDTH (4)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARREGION_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARREGION),
    .dout (m_axi_weight_s_sum_mmap_ARREGION)
);


__rs_pass_through #(
    .WIDTH (3)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARSIZE_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARSIZE),
    .dout (m_axi_weight_s_sum_mmap_ARSIZE)
);


__rs_pass_through #(
    .WIDTH (( ( C_M_AXI_WEIGHT_S_SUM_MMAP_ARUSER_WIDTH - 1 ) - ( 0 ) + 1 ))
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARUSER_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARUSER),
    .dout (m_axi_weight_s_sum_mmap_ARUSER)
);


__rs_pass_through #(
    .WIDTH (1)
) __rs_pt_weight_s_loader_wq_m_axi_weight_s_sum_mmap_ARVALID_inst /**   Generated by RapidStream   **/ (
    .din  (__rs_pt_m_axi_weight_s_sum_mmap_ARVALID),
    .dout (m_axi_weight_s_sum_mmap_ARVALID)
);

endmodule  // __rs_pt_weight_s_loader_wq_0_0