// ==================================================
// RTL generated by RapidStream
//
// Copyright 2024 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
module __rs_QuantWrapper_Linear_Layer_q_tb_aux_split_aux_1 #(
    parameter C_S_AXI_CONTROL_DATA_WIDTH  = 32,
    parameter C_S_AXI_CONTROL_ADDR_WIDTH  = 7,
    parameter C_S_AXI_DATA_WIDTH          = 32,
    parameter C_S_AXI_CONTROL_WSTRB_WIDTH = 32'd4,
    parameter C_S_AXI_WSTRB_WIDTH         = 32'd4
) (
    output wire Linear_Layer_i4xi4_q_0_ap_clk,
    output wire Linear_Layer_i4xi4_q_0_ap_rst_n,
    output wire __tapa_fsm_unit_ap_clk,
    output wire __tapa_fsm_unit_ap_rst_n,
    input wire  ap_clk,
    input wire  ap_rst_n,
    output wire control_s_axi_U_ACLK,
    output wire control_s_axi_U_ARESET,
    output wire dequant_layer_q_int_fp32_0_ap_clk,
    output wire dequant_layer_q_int_fp32_0_ap_rst_n,
    output wire input_loader_r1_ln_iembed_fp32_0_ap_clk,
    output wire input_loader_r1_ln_iembed_fp32_0_ap_rst_n,
    output wire input_s_b_stream_clk,
    output wire input_s_b_stream_reset,
    output wire input_stream_clk,
    output wire input_stream_reset,
    output wire output_drainer_q_fp32_0_ap_clk,
    output wire output_drainer_q_fp32_0_ap_rst_n,
    output wire output_stream_clk,
    output wire output_stream_reset,
    output wire quant_input_stream_clk,
    output wire quant_input_stream_reset,
    output wire quant_layer_r1_ln_iembed_fp32_int4_0_ap_clk,
    output wire quant_layer_r1_ln_iembed_fp32_int4_0_ap_rst_n,
    output wire quant_output_stream_clk,
    output wire quant_output_stream_reset,
    output wire quant_weight_stream_clk,
    output wire quant_weight_stream_reset,
    output wire weight_loader_wq_0_ap_clk,
    output wire weight_loader_wq_0_ap_rst_n,
    output wire weight_s_loader_wq_0_ap_clk,
    output wire weight_s_loader_wq_0_ap_rst_n,
    output wire weight_s_sum_stream_clk,
    output wire weight_s_sum_stream_reset
);




__rs_QuantWrapper_Linear_Layer_q_tb_aux #(
    .C_S_AXI_CONTROL_ADDR_WIDTH  (C_S_AXI_CONTROL_ADDR_WIDTH),
    .C_S_AXI_CONTROL_DATA_WIDTH  (C_S_AXI_CONTROL_DATA_WIDTH),
    .C_S_AXI_CONTROL_WSTRB_WIDTH (C_S_AXI_CONTROL_WSTRB_WIDTH),
    .C_S_AXI_DATA_WIDTH          (C_S_AXI_DATA_WIDTH),
    .C_S_AXI_WSTRB_WIDTH         (C_S_AXI_WSTRB_WIDTH)
) __rs_QuantWrapper_Linear_Layer_q_tb_aux_0 (
    .Linear_Layer_i4xi4_q_0_ap_clk                 (Linear_Layer_i4xi4_q_0_ap_clk),
    .Linear_Layer_i4xi4_q_0_ap_rst_n               (Linear_Layer_i4xi4_q_0_ap_rst_n),
    .__tapa_fsm_unit_ap_clk                        (__tapa_fsm_unit_ap_clk),
    .__tapa_fsm_unit_ap_rst_n                      (__tapa_fsm_unit_ap_rst_n),
    .ap_clk                                        (ap_clk),
    .ap_rst_n                                      (ap_rst_n),
    .control_s_axi_U_ACLK                          (control_s_axi_U_ACLK),
    .control_s_axi_U_ARESET                        (control_s_axi_U_ARESET),
    .dequant_layer_q_int_fp32_0_ap_clk             (dequant_layer_q_int_fp32_0_ap_clk),
    .dequant_layer_q_int_fp32_0_ap_rst_n           (dequant_layer_q_int_fp32_0_ap_rst_n),
    .input_loader_r1_ln_iembed_fp32_0_ap_clk       (input_loader_r1_ln_iembed_fp32_0_ap_clk),
    .input_loader_r1_ln_iembed_fp32_0_ap_rst_n     (input_loader_r1_ln_iembed_fp32_0_ap_rst_n),
    .input_s_b_stream_clk                          (input_s_b_stream_clk),
    .input_s_b_stream_reset                        (input_s_b_stream_reset),
    .input_stream_clk                              (input_stream_clk),
    .input_stream_reset                            (input_stream_reset),
    .output_drainer_q_fp32_0_ap_clk                (output_drainer_q_fp32_0_ap_clk),
    .output_drainer_q_fp32_0_ap_rst_n              (output_drainer_q_fp32_0_ap_rst_n),
    .output_stream_clk                             (output_stream_clk),
    .output_stream_reset                           (output_stream_reset),
    .quant_input_stream_clk                        (quant_input_stream_clk),
    .quant_input_stream_reset                      (quant_input_stream_reset),
    .quant_layer_r1_ln_iembed_fp32_int4_0_ap_clk   (quant_layer_r1_ln_iembed_fp32_int4_0_ap_clk),
    .quant_layer_r1_ln_iembed_fp32_int4_0_ap_rst_n (quant_layer_r1_ln_iembed_fp32_int4_0_ap_rst_n),
    .quant_output_stream_clk                       (quant_output_stream_clk),
    .quant_output_stream_reset                     (quant_output_stream_reset),
    .quant_weight_stream_clk                       (quant_weight_stream_clk),
    .quant_weight_stream_reset                     (quant_weight_stream_reset),
    .weight_loader_wq_0_ap_clk                     (weight_loader_wq_0_ap_clk),
    .weight_loader_wq_0_ap_rst_n                   (weight_loader_wq_0_ap_rst_n),
    .weight_s_loader_wq_0_ap_clk                   (weight_s_loader_wq_0_ap_clk),
    .weight_s_loader_wq_0_ap_rst_n                 (weight_s_loader_wq_0_ap_rst_n),
    .weight_s_sum_stream_clk                       (weight_s_sum_stream_clk),
    .weight_s_sum_stream_reset                     (weight_s_sum_stream_reset)
);

endmodule  // __rs_QuantWrapper_Linear_Layer_q_tb_aux_split_aux_1