// ==================================================
// RTL generated by RapidStream
//
// Copyright 2024 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
module __rs_ff_pipeline_0 #(
    parameter DATA_WIDTH    = 32,
    parameter HEAD_LEVEL    = 0,
    parameter BODY_LEVEL    = 0,
    parameter TAIL_LEVEL    = 0,
    parameter __HEAD_REGION = "",
    parameter __TAIL_REGION = ""
) (
    input wire                       clk,
    input wire  [(DATA_WIDTH - 1):0] if_din,
    output wire [(DATA_WIDTH - 1):0] if_dout
);

wire                      RS_FF_PP_HEAD_clk;
wire [(DATA_WIDTH - 1):0] RS_FF_PP_HEAD_if_din;
wire [(DATA_WIDTH - 1):0] RS_FF_PP_HEAD_if_dout;
wire                      RS_FF_PP_TAIL_clk;
wire [(DATA_WIDTH - 1):0] RS_FF_PP_TAIL_if_din;
wire [(DATA_WIDTH - 1):0] RS_FF_PP_TAIL_if_dout;



__rs_feed_forward_reg #(
    .DATA_WIDTH (DATA_WIDTH),
    .ENABLE_REG (HEAD_LEVEL),
    .__REGION   (__HEAD_REGION)
) RS_FF_PP_HEAD (
    .clk     (clk),
    .if_din  (if_din),
    .if_dout (RS_FF_PP_HEAD_if_dout)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH (DATA_WIDTH),
    .ENABLE_REG (TAIL_LEVEL),
    .__REGION   (__TAIL_REGION)
) RS_FF_PP_TAIL (
    .clk     (clk),
    .if_din  (RS_FF_PP_HEAD_if_dout),
    .if_dout (if_dout)
);

endmodule  // __rs_ff_pipeline_0