// ==================================================
// RTL generated by RapidStream
//
// Copyright 2024 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
module dequant_layer_q_int_fp32 #(
    parameter ap_ST_fsm_state1 = 3'd1,
    parameter ap_ST_fsm_state2 = 3'd2,
    parameter ap_ST_fsm_state3 = 3'd4
) (
    input wire          ap_clk,
    output wire         ap_done,
    output wire         ap_idle,
    output wire         ap_ready,
    input wire          ap_rst_n,
    input wire          ap_start,
    input wire  [ 64:0] input_s_b_stream_peek_dout,
    input wire          input_s_b_stream_peek_empty_n,
    output wire         input_s_b_stream_peek_read,
    input wire  [ 64:0] input_s_b_stream_s_dout,
    input wire          input_s_b_stream_s_empty_n,
    output wire         input_s_b_stream_s_read,
    input wire  [304:0] input_stream_peek_dout,
    input wire          input_stream_peek_empty_n,
    output wire         input_stream_peek_read,
    input wire  [304:0] input_stream_s_dout,
    input wire          input_stream_s_empty_n,
    output wire         input_stream_s_read,
    input wire  [512:0] output_stream_peek,
    output wire [512:0] output_stream_s_din,
    input wire          output_stream_s_full_n,
    output wire         output_stream_s_write,
    input wire  [ 31:0] seq_len,
    input wire  [ 64:0] weight_s_sum_stream_peek_dout,
    input wire          weight_s_sum_stream_peek_empty_n,
    output wire         weight_s_sum_stream_peek_read,
    input wire  [ 64:0] weight_s_sum_stream_s_dout,
    input wire          weight_s_sum_stream_s_empty_n,
    output wire         weight_s_sum_stream_s_read
);




dequant_layer_q_int_fp32_hide_peek #(
    .ap_ST_fsm_state1 (ap_ST_fsm_state1),
    .ap_ST_fsm_state2 (ap_ST_fsm_state2),
    .ap_ST_fsm_state3 (ap_ST_fsm_state3)
) dequant_layer_q_int_fp32_hide_peek_0 /**   Generated by RapidStream   **/ (
    .ap_clk                           (ap_clk),
    .ap_done                          (ap_done),
    .ap_idle                          (ap_idle),
    .ap_ready                         (ap_ready),
    .ap_rst_n                         (ap_rst_n),
    .ap_start                         (ap_start),
    .input_s_b_stream_peek_dout       (input_s_b_stream_s_dout),
    .input_s_b_stream_peek_empty_n    (input_s_b_stream_s_empty_n),
    .input_s_b_stream_peek_read       (),
    .input_s_b_stream_s_dout          (input_s_b_stream_s_dout),
    .input_s_b_stream_s_empty_n       (input_s_b_stream_s_empty_n),
    .input_s_b_stream_s_read          (input_s_b_stream_s_read),
    .input_stream_peek_dout           (input_stream_s_dout),
    .input_stream_peek_empty_n        (input_stream_s_empty_n),
    .input_stream_peek_read           (),
    .input_stream_s_dout              (input_stream_s_dout),
    .input_stream_s_empty_n           (input_stream_s_empty_n),
    .input_stream_s_read              (input_stream_s_read),
    .output_stream_peek               (output_stream_peek),
    .output_stream_s_din              (output_stream_s_din),
    .output_stream_s_full_n           (output_stream_s_full_n),
    .output_stream_s_write            (output_stream_s_write),
    .seq_len                          (seq_len),
    .weight_s_sum_stream_peek_dout    (weight_s_sum_stream_s_dout),
    .weight_s_sum_stream_peek_empty_n (weight_s_sum_stream_s_empty_n),
    .weight_s_sum_stream_peek_read    (),
    .weight_s_sum_stream_s_dout       (weight_s_sum_stream_s_dout),
    .weight_s_sum_stream_s_empty_n    (weight_s_sum_stream_s_empty_n),
    .weight_s_sum_stream_s_read       (weight_s_sum_stream_s_read)
);

endmodule  // dequant_layer_q_int_fp32