`timescale 1 ns / 1 ps
// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
 
module dequant_layer_q_int_fp32_dequant_layer_qint_fp32_19_true_16_2048_1024_Pipeline_output_dim_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_stream_s_dout,
        input_stream_s_empty_n,
        input_stream_s_read,
        weight_s_sum_stream_s_dout,
        weight_s_sum_stream_s_empty_n,
        weight_s_sum_stream_s_read,
        output_stream_s_din,
        output_stream_s_full_n,
        output_stream_s_write,
        s_load,
        b_load,
        s_load_1,
        b_load_1,
        s_load_2,
        b_load_2,
        s_load_3,
        b_load_3,
        s_load_4,
        b_load_4,
        s_load_5,
        b_load_5,
        s_load_6,
        b_load_6,
        s_load_7,
        b_load_7,
        s_load_8,
        b_load_8,
        s_load_9,
        b_load_9,
        s_load_10,
        b_load_10,
        s_load_11,
        b_load_11,
        s_load_12,
        b_load_12,
        s_load_13,
        b_load_13,
        s_load_14,
        b_load_14,
        s_load_15,
        b_load_15
);
parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [304:0] input_stream_s_dout;
input   input_stream_s_empty_n;
output   input_stream_s_read;
input  [64:0] weight_s_sum_stream_s_dout;
input   weight_s_sum_stream_s_empty_n;
output   weight_s_sum_stream_s_read;
output  [512:0] output_stream_s_din;
input   output_stream_s_full_n;
output   output_stream_s_write;
input  [31:0] s_load;
input  [31:0] b_load;
input  [31:0] s_load_1;
input  [31:0] b_load_1;
input  [31:0] s_load_2;
input  [31:0] b_load_2;
input  [31:0] s_load_3;
input  [31:0] b_load_3;
input  [31:0] s_load_4;
input  [31:0] b_load_4;
input  [31:0] s_load_5;
input  [31:0] b_load_5;
input  [31:0] s_load_6;
input  [31:0] b_load_6;
input  [31:0] s_load_7;
input  [31:0] b_load_7;
input  [31:0] s_load_8;
input  [31:0] b_load_8;
input  [31:0] s_load_9;
input  [31:0] b_load_9;
input  [31:0] s_load_10;
input  [31:0] b_load_10;
input  [31:0] s_load_11;
input  [31:0] b_load_11;
input  [31:0] s_load_12;
input  [31:0] b_load_12;
input  [31:0] s_load_13;
input  [31:0] b_load_13;
input  [31:0] s_load_14;
input  [31:0] b_load_14;
input  [31:0] s_load_15;
input  [31:0] b_load_15;
reg ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state13_pp0_stage0_iter12;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln889_fu_769_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_stream_s_blk_n;
wire    ap_block_pp0_stage0;
reg    weight_s_sum_stream_s_blk_n;
reg    output_stream_s_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [18:0] trunc_ln91_fu_789_p1;
reg   [18:0] trunc_ln91_reg_1824;
reg   [18:0] trunc_ln91_5_reg_1829;
reg   [18:0] trunc_ln91_6_reg_1834;
reg   [18:0] trunc_ln91_7_reg_1839;
reg   [18:0] trunc_ln91_8_reg_1844;
reg   [18:0] trunc_ln91_9_reg_1849;
reg   [18:0] trunc_ln91_s_reg_1854;
reg   [18:0] trunc_ln91_3_reg_1859;
reg   [18:0] trunc_ln91_1_reg_1864;
reg   [18:0] trunc_ln91_2_reg_1869;
reg   [18:0] trunc_ln91_4_reg_1874;
reg   [18:0] trunc_ln91_10_reg_1879;
reg   [18:0] trunc_ln91_11_reg_1884;
reg   [18:0] trunc_ln91_12_reg_1889;
reg   [18:0] trunc_ln91_13_reg_1894;
reg   [18:0] trunc_ln91_14_reg_1899;
wire   [31:0] trunc_ln91_15_fu_945_p1;
reg   [31:0] trunc_ln91_15_reg_1904;
reg   [31:0] trunc_ln91_15_reg_1904_pp0_iter2_reg;
reg   [31:0] trunc_ln91_15_reg_1904_pp0_iter3_reg;
reg   [31:0] trunc_ln91_15_reg_1904_pp0_iter4_reg;
reg   [31:0] trunc_ln91_15_reg_1904_pp0_iter5_reg;
reg   [31:0] trunc_ln91_15_reg_1904_pp0_iter6_reg;
reg   [31:0] trunc_ln91_15_reg_1904_pp0_iter7_reg;
reg   [31:0] trunc_ln91_15_reg_1904_pp0_iter8_reg;
reg   [31:0] trunc_ln91_16_reg_1909;
reg   [31:0] trunc_ln91_16_reg_1909_pp0_iter2_reg;
reg   [31:0] trunc_ln91_16_reg_1909_pp0_iter3_reg;
reg   [31:0] trunc_ln91_16_reg_1909_pp0_iter4_reg;
reg   [31:0] trunc_ln91_16_reg_1909_pp0_iter5_reg;
wire   [31:0] bitcast_ln91_1_fu_1087_p1;
wire   [31:0] grp_fu_521_p1;
wire   [31:0] grp_fu_524_p1;
wire   [31:0] grp_fu_527_p1;
wire   [31:0] grp_fu_530_p1;
wire   [31:0] grp_fu_533_p1;
wire   [31:0] grp_fu_536_p1;
wire   [31:0] grp_fu_539_p1;
wire   [31:0] grp_fu_542_p1;
wire   [31:0] grp_fu_545_p1;
wire   [31:0] grp_fu_548_p1;
wire   [31:0] grp_fu_551_p1;
wire   [31:0] grp_fu_554_p1;
wire   [31:0] grp_fu_557_p1;
wire   [31:0] grp_fu_560_p1;
wire   [31:0] grp_fu_563_p1;
wire   [31:0] grp_fu_566_p1;
wire   [31:0] bitcast_ln91_fu_1314_p1;
reg   [31:0] grp_fu_393_p2;
reg   [31:0] grp_fu_397_p2;
reg   [31:0] grp_fu_401_p2;
reg   [31:0] grp_fu_405_p2;
reg   [31:0] grp_fu_409_p2;
reg   [31:0] grp_fu_413_p2;
reg   [31:0] grp_fu_417_p2;
reg   [31:0] grp_fu_421_p2;
reg   [31:0] grp_fu_425_p2;
reg   [31:0] grp_fu_429_p2;
reg   [31:0] grp_fu_433_p2;
reg   [31:0] grp_fu_437_p2;
reg   [31:0] grp_fu_441_p2;
reg   [31:0] grp_fu_445_p2;
reg   [31:0] grp_fu_449_p2;
reg   [31:0] grp_fu_453_p2;
reg   [31:0] grp_fu_457_p2;
reg   [31:0] grp_fu_461_p2;
reg   [31:0] grp_fu_465_p2;
reg   [31:0] grp_fu_469_p2;
reg   [31:0] grp_fu_473_p2;
reg   [31:0] grp_fu_477_p2;
reg   [31:0] grp_fu_481_p2;
reg   [31:0] grp_fu_485_p2;
reg   [31:0] grp_fu_489_p2;
reg   [31:0] grp_fu_493_p2;
reg   [31:0] grp_fu_497_p2;
reg   [31:0] grp_fu_501_p2;
reg   [31:0] grp_fu_505_p2;
reg   [31:0] grp_fu_509_p2;
reg   [31:0] grp_fu_513_p2;
reg   [31:0] grp_fu_517_p2;
reg   [11:0] k_fu_178;
wire   [11:0] k_2_fu_763_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_k_1;
reg    input_stream_s_read_local;
reg    weight_s_sum_stream_s_read_local;
wire   [512:0] zext_ln150_fu_1609_p1;
reg    ap_block_pp0_stage0_01001;
reg    output_stream_s_write_local;
reg   [31:0] grp_fu_393_p0;
reg   [31:0] grp_fu_393_p1;
reg   [31:0] grp_fu_397_p0;
reg   [31:0] grp_fu_397_p1;
reg   [31:0] grp_fu_401_p0;
reg   [31:0] grp_fu_401_p1;
reg   [31:0] grp_fu_405_p0;
reg   [31:0] grp_fu_405_p1;
reg   [31:0] grp_fu_409_p0;
reg   [31:0] grp_fu_409_p1;
reg   [31:0] grp_fu_413_p0;
reg   [31:0] grp_fu_413_p1;
reg   [31:0] grp_fu_417_p0;
reg   [31:0] grp_fu_417_p1;
reg   [31:0] grp_fu_421_p0;
reg   [31:0] grp_fu_421_p1;
reg   [31:0] grp_fu_425_p0;
reg   [31:0] grp_fu_425_p1;
reg   [31:0] grp_fu_429_p0;
reg   [31:0] grp_fu_429_p1;
reg   [31:0] grp_fu_433_p0;
reg   [31:0] grp_fu_433_p1;
reg   [31:0] grp_fu_437_p0;
reg   [31:0] grp_fu_437_p1;
reg   [31:0] grp_fu_441_p0;
reg   [31:0] grp_fu_441_p1;
reg   [31:0] grp_fu_445_p0;
reg   [31:0] grp_fu_445_p1;
reg   [31:0] grp_fu_449_p0;
reg   [31:0] grp_fu_449_p1;
reg   [31:0] grp_fu_453_p0;
reg   [31:0] grp_fu_453_p1;
reg   [31:0] grp_fu_457_p0;
reg   [31:0] grp_fu_457_p1;
reg   [31:0] grp_fu_461_p0;
reg   [31:0] grp_fu_461_p1;
reg   [31:0] grp_fu_465_p0;
reg   [31:0] grp_fu_465_p1;
reg   [31:0] grp_fu_469_p0;
reg   [31:0] grp_fu_469_p1;
reg   [31:0] grp_fu_473_p0;
reg   [31:0] grp_fu_473_p1;
reg   [31:0] grp_fu_477_p0;
reg   [31:0] grp_fu_477_p1;
reg   [31:0] grp_fu_481_p0;
reg   [31:0] grp_fu_481_p1;
reg   [31:0] grp_fu_485_p0;
reg   [31:0] grp_fu_485_p1;
reg   [31:0] grp_fu_489_p0;
reg   [31:0] grp_fu_489_p1;
reg   [31:0] grp_fu_493_p0;
reg   [31:0] grp_fu_493_p1;
reg   [31:0] grp_fu_497_p0;
reg   [31:0] grp_fu_497_p1;
reg   [31:0] grp_fu_501_p0;
reg   [31:0] grp_fu_501_p1;
reg   [31:0] grp_fu_505_p0;
reg   [31:0] grp_fu_505_p1;
reg   [31:0] grp_fu_509_p0;
reg   [31:0] grp_fu_509_p1;
reg   [31:0] grp_fu_513_p0;
reg   [31:0] grp_fu_513_p1;
reg   [31:0] grp_fu_517_p0;
reg   [31:0] grp_fu_517_p1;
wire  signed [31:0] grp_fu_521_p0;
wire  signed [31:0] grp_fu_524_p0;
wire  signed [31:0] grp_fu_527_p0;
wire  signed [31:0] grp_fu_530_p0;
wire  signed [31:0] grp_fu_533_p0;
wire  signed [31:0] grp_fu_536_p0;
wire  signed [31:0] grp_fu_539_p0;
wire  signed [31:0] grp_fu_542_p0;
wire  signed [31:0] grp_fu_545_p0;
wire  signed [31:0] grp_fu_548_p0;
wire  signed [31:0] grp_fu_551_p0;
wire  signed [31:0] grp_fu_554_p0;
wire  signed [31:0] grp_fu_557_p0;
wire  signed [31:0] grp_fu_560_p0;
wire  signed [31:0] grp_fu_563_p0;
wire  signed [31:0] grp_fu_566_p0;
reg   [31:0] grp_fu_569_p1;
reg   [31:0] grp_fu_569_p2;
reg   [31:0] grp_fu_569_p3;
reg   [31:0] grp_fu_576_p1;
reg   [31:0] grp_fu_576_p2;
reg   [31:0] grp_fu_576_p3;
reg   [31:0] grp_fu_583_p1;
reg   [31:0] grp_fu_583_p2;
reg   [31:0] grp_fu_583_p3;
reg   [31:0] grp_fu_590_p1;
reg   [31:0] grp_fu_590_p2;
reg   [31:0] grp_fu_590_p3;
reg   [31:0] grp_fu_597_p1;
reg   [31:0] grp_fu_597_p2;
reg   [31:0] grp_fu_597_p3;
reg   [31:0] grp_fu_604_p1;
reg   [31:0] grp_fu_604_p2;
reg   [31:0] grp_fu_604_p3;
reg   [31:0] grp_fu_611_p1;
reg   [31:0] grp_fu_611_p2;
reg   [31:0] grp_fu_611_p3;
reg   [31:0] grp_fu_618_p1;
reg   [31:0] grp_fu_618_p2;
reg   [31:0] grp_fu_618_p3;
reg   [31:0] grp_fu_625_p1;
reg   [31:0] grp_fu_625_p2;
reg   [31:0] grp_fu_625_p3;
reg   [31:0] grp_fu_632_p1;
reg   [31:0] grp_fu_632_p2;
reg   [31:0] grp_fu_632_p3;
reg   [31:0] grp_fu_639_p1;
reg   [31:0] grp_fu_639_p2;
reg   [31:0] grp_fu_639_p3;
reg   [31:0] grp_fu_646_p1;
reg   [31:0] grp_fu_646_p2;
reg   [31:0] grp_fu_646_p3;
reg   [31:0] grp_fu_653_p1;
reg   [31:0] grp_fu_653_p2;
reg   [31:0] grp_fu_653_p3;
reg   [31:0] grp_fu_660_p1;
reg   [31:0] grp_fu_660_p2;
reg   [31:0] grp_fu_660_p3;
reg   [31:0] grp_fu_667_p1;
reg   [31:0] grp_fu_667_p2;
reg   [31:0] grp_fu_667_p3;
reg   [31:0] grp_fu_674_p1;
reg   [31:0] grp_fu_674_p2;
reg   [31:0] grp_fu_674_p3;
reg   [31:0] grp_fu_569_p4;
reg   [31:0] grp_fu_576_p4;
reg   [31:0] grp_fu_583_p4;
reg   [31:0] grp_fu_590_p4;
reg   [31:0] grp_fu_597_p4;
reg   [31:0] grp_fu_604_p4;
reg   [31:0] grp_fu_611_p4;
reg   [31:0] grp_fu_618_p4;
reg   [31:0] grp_fu_625_p4;
reg   [31:0] grp_fu_632_p4;
reg   [31:0] grp_fu_639_p4;
reg   [31:0] grp_fu_646_p4;
reg   [31:0] grp_fu_653_p4;
reg   [31:0] grp_fu_660_p4;
reg   [31:0] grp_fu_667_p4;
reg   [31:0] grp_fu_674_p4;
wire   [31:0] bitcast_ln150_15_fu_1569_p1;
wire   [31:0] bitcast_ln150_14_fu_1565_p1;
wire   [31:0] bitcast_ln150_13_fu_1561_p1;
wire   [31:0] bitcast_ln150_12_fu_1557_p1;
wire   [31:0] bitcast_ln150_11_fu_1553_p1;
wire   [31:0] bitcast_ln150_10_fu_1549_p1;
wire   [31:0] bitcast_ln150_9_fu_1545_p1;
wire   [31:0] bitcast_ln150_8_fu_1541_p1;
wire   [31:0] bitcast_ln150_7_fu_1537_p1;
wire   [31:0] bitcast_ln150_6_fu_1533_p1;
wire   [31:0] bitcast_ln150_5_fu_1529_p1;
wire   [31:0] bitcast_ln150_4_fu_1525_p1;
wire   [31:0] bitcast_ln150_3_fu_1521_p1;
wire   [31:0] bitcast_ln150_2_fu_1517_p1;
wire   [31:0] bitcast_ln150_1_fu_1513_p1;
wire   [31:0] bitcast_ln150_fu_1509_p1;
wire   [511:0] or_ln150_2_fu_1573_p17;
reg    grp_fu_393_ce;
wire   [31:0] pre_grp_fu_393_p2;
reg   [31:0] pre_grp_fu_393_p2_reg;
reg    grp_fu_397_ce;
wire   [31:0] pre_grp_fu_397_p2;
reg   [31:0] pre_grp_fu_397_p2_reg;
reg    grp_fu_401_ce;
wire   [31:0] pre_grp_fu_401_p2;
reg   [31:0] pre_grp_fu_401_p2_reg;
reg    grp_fu_405_ce;
wire   [31:0] pre_grp_fu_405_p2;
reg   [31:0] pre_grp_fu_405_p2_reg;
reg    grp_fu_409_ce;
wire   [31:0] pre_grp_fu_409_p2;
reg   [31:0] pre_grp_fu_409_p2_reg;
reg    grp_fu_413_ce;
wire   [31:0] pre_grp_fu_413_p2;
reg   [31:0] pre_grp_fu_413_p2_reg;
reg    grp_fu_417_ce;
wire   [31:0] pre_grp_fu_417_p2;
reg   [31:0] pre_grp_fu_417_p2_reg;
reg    grp_fu_421_ce;
wire   [31:0] pre_grp_fu_421_p2;
reg   [31:0] pre_grp_fu_421_p2_reg;
reg    grp_fu_425_ce;
wire   [31:0] pre_grp_fu_425_p2;
reg   [31:0] pre_grp_fu_425_p2_reg;
reg    grp_fu_429_ce;
wire   [31:0] pre_grp_fu_429_p2;
reg   [31:0] pre_grp_fu_429_p2_reg;
reg    grp_fu_433_ce;
wire   [31:0] pre_grp_fu_433_p2;
reg   [31:0] pre_grp_fu_433_p2_reg;
reg    grp_fu_437_ce;
wire   [31:0] pre_grp_fu_437_p2;
reg   [31:0] pre_grp_fu_437_p2_reg;
reg    grp_fu_441_ce;
wire   [31:0] pre_grp_fu_441_p2;
reg   [31:0] pre_grp_fu_441_p2_reg;
reg    grp_fu_445_ce;
wire   [31:0] pre_grp_fu_445_p2;
reg   [31:0] pre_grp_fu_445_p2_reg;
reg    grp_fu_449_ce;
wire   [31:0] pre_grp_fu_449_p2;
reg   [31:0] pre_grp_fu_449_p2_reg;
reg    grp_fu_453_ce;
wire   [31:0] pre_grp_fu_453_p2;
reg   [31:0] pre_grp_fu_453_p2_reg;
reg    grp_fu_457_ce;
wire   [31:0] pre_grp_fu_457_p2;
reg   [31:0] pre_grp_fu_457_p2_reg;
reg    grp_fu_461_ce;
wire   [31:0] pre_grp_fu_461_p2;
reg   [31:0] pre_grp_fu_461_p2_reg;
reg    grp_fu_465_ce;
wire   [31:0] pre_grp_fu_465_p2;
reg   [31:0] pre_grp_fu_465_p2_reg;
reg    grp_fu_469_ce;
wire   [31:0] pre_grp_fu_469_p2;
reg   [31:0] pre_grp_fu_469_p2_reg;
reg    grp_fu_473_ce;
wire   [31:0] pre_grp_fu_473_p2;
reg   [31:0] pre_grp_fu_473_p2_reg;
reg    grp_fu_477_ce;
wire   [31:0] pre_grp_fu_477_p2;
reg   [31:0] pre_grp_fu_477_p2_reg;
reg    grp_fu_481_ce;
wire   [31:0] pre_grp_fu_481_p2;
reg   [31:0] pre_grp_fu_481_p2_reg;
reg    grp_fu_485_ce;
wire   [31:0] pre_grp_fu_485_p2;
reg   [31:0] pre_grp_fu_485_p2_reg;
reg    grp_fu_489_ce;
wire   [31:0] pre_grp_fu_489_p2;
reg   [31:0] pre_grp_fu_489_p2_reg;
reg    grp_fu_493_ce;
wire   [31:0] pre_grp_fu_493_p2;
reg   [31:0] pre_grp_fu_493_p2_reg;
reg    grp_fu_497_ce;
wire   [31:0] pre_grp_fu_497_p2;
reg   [31:0] pre_grp_fu_497_p2_reg;
reg    grp_fu_501_ce;
wire   [31:0] pre_grp_fu_501_p2;
reg   [31:0] pre_grp_fu_501_p2_reg;
reg    grp_fu_505_ce;
wire   [31:0] pre_grp_fu_505_p2;
reg   [31:0] pre_grp_fu_505_p2_reg;
reg    grp_fu_509_ce;
wire   [31:0] pre_grp_fu_509_p2;
reg   [31:0] pre_grp_fu_509_p2_reg;
reg    grp_fu_513_ce;
wire   [31:0] pre_grp_fu_513_p2;
reg   [31:0] pre_grp_fu_513_p2_reg;
reg    grp_fu_517_ce;
wire   [31:0] pre_grp_fu_517_p2;
reg   [31:0] pre_grp_fu_517_p2_reg;
reg    grp_fu_521_ce;
reg    grp_fu_524_ce;
reg    grp_fu_527_ce;
reg    grp_fu_530_ce;
reg    grp_fu_533_ce;
reg    grp_fu_536_ce;
reg    grp_fu_539_ce;
reg    grp_fu_542_ce;
reg    grp_fu_545_ce;
reg    grp_fu_548_ce;
reg    grp_fu_551_ce;
reg    grp_fu_554_ce;
reg    grp_fu_557_ce;
reg    grp_fu_560_ce;
reg    grp_fu_563_ce;
reg    grp_fu_566_ce;
reg    grp_fu_569_ce;
wire   [31:0] pre_grp_fu_569_p4;
reg   [31:0] pre_grp_fu_569_p4_reg;
reg    grp_fu_576_ce;
wire   [31:0] pre_grp_fu_576_p4;
reg   [31:0] pre_grp_fu_576_p4_reg;
reg    grp_fu_583_ce;
wire   [31:0] pre_grp_fu_583_p4;
reg   [31:0] pre_grp_fu_583_p4_reg;
reg    grp_fu_590_ce;
wire   [31:0] pre_grp_fu_590_p4;
reg   [31:0] pre_grp_fu_590_p4_reg;
reg    grp_fu_597_ce;
wire   [31:0] pre_grp_fu_597_p4;
reg   [31:0] pre_grp_fu_597_p4_reg;
reg    grp_fu_604_ce;
wire   [31:0] pre_grp_fu_604_p4;
reg   [31:0] pre_grp_fu_604_p4_reg;
reg    grp_fu_611_ce;
wire   [31:0] pre_grp_fu_611_p4;
reg   [31:0] pre_grp_fu_611_p4_reg;
reg    grp_fu_618_ce;
wire   [31:0] pre_grp_fu_618_p4;
reg   [31:0] pre_grp_fu_618_p4_reg;
reg    grp_fu_625_ce;
wire   [31:0] pre_grp_fu_625_p4;
reg   [31:0] pre_grp_fu_625_p4_reg;
reg    grp_fu_632_ce;
wire   [31:0] pre_grp_fu_632_p4;
reg   [31:0] pre_grp_fu_632_p4_reg;
reg    grp_fu_639_ce;
wire   [31:0] pre_grp_fu_639_p4;
reg   [31:0] pre_grp_fu_639_p4_reg;
reg    grp_fu_646_ce;
wire   [31:0] pre_grp_fu_646_p4;
reg   [31:0] pre_grp_fu_646_p4_reg;
reg    grp_fu_653_ce;
wire   [31:0] pre_grp_fu_653_p4;
reg   [31:0] pre_grp_fu_653_p4_reg;
reg    grp_fu_660_ce;
wire   [31:0] pre_grp_fu_660_p4;
reg   [31:0] pre_grp_fu_660_p4_reg;
reg    grp_fu_667_ce;
wire   [31:0] pre_grp_fu_667_p4;
reg   [31:0] pre_grp_fu_667_p4_reg;
reg    grp_fu_674_ce;
wire   [31:0] pre_grp_fu_674_p4;
reg   [31:0] pre_grp_fu_674_p4_reg;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;
// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 k_fu_178 = 12'd0;
#0 ap_done_reg = 1'b0;
end
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_393_p0),
    .din1(grp_fu_393_p1),
    .ce(grp_fu_393_ce),
    .dout(pre_grp_fu_393_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_397_p0),
    .din1(grp_fu_397_p1),
    .ce(grp_fu_397_ce),
    .dout(pre_grp_fu_397_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_401_p0),
    .din1(grp_fu_401_p1),
    .ce(grp_fu_401_ce),
    .dout(pre_grp_fu_401_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_405_p0),
    .din1(grp_fu_405_p1),
    .ce(grp_fu_405_ce),
    .dout(pre_grp_fu_405_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_409_p0),
    .din1(grp_fu_409_p1),
    .ce(grp_fu_409_ce),
    .dout(pre_grp_fu_409_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_413_p0),
    .din1(grp_fu_413_p1),
    .ce(grp_fu_413_ce),
    .dout(pre_grp_fu_413_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_417_p0),
    .din1(grp_fu_417_p1),
    .ce(grp_fu_417_ce),
    .dout(pre_grp_fu_417_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_421_p0),
    .din1(grp_fu_421_p1),
    .ce(grp_fu_421_ce),
    .dout(pre_grp_fu_421_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_425_p0),
    .din1(grp_fu_425_p1),
    .ce(grp_fu_425_ce),
    .dout(pre_grp_fu_425_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_429_p0),
    .din1(grp_fu_429_p1),
    .ce(grp_fu_429_ce),
    .dout(pre_grp_fu_429_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_433_p0),
    .din1(grp_fu_433_p1),
    .ce(grp_fu_433_ce),
    .dout(pre_grp_fu_433_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_437_p0),
    .din1(grp_fu_437_p1),
    .ce(grp_fu_437_ce),
    .dout(pre_grp_fu_437_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_441_p0),
    .din1(grp_fu_441_p1),
    .ce(grp_fu_441_ce),
    .dout(pre_grp_fu_441_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_445_p0),
    .din1(grp_fu_445_p1),
    .ce(grp_fu_445_ce),
    .dout(pre_grp_fu_445_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_449_p0),
    .din1(grp_fu_449_p1),
    .ce(grp_fu_449_ce),
    .dout(pre_grp_fu_449_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_453_p0),
    .din1(grp_fu_453_p1),
    .ce(grp_fu_453_ce),
    .dout(pre_grp_fu_453_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_457_p0),
    .din1(grp_fu_457_p1),
    .ce(grp_fu_457_ce),
    .dout(pre_grp_fu_457_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_461_p0),
    .din1(grp_fu_461_p1),
    .ce(grp_fu_461_ce),
    .dout(pre_grp_fu_461_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_465_p0),
    .din1(grp_fu_465_p1),
    .ce(grp_fu_465_ce),
    .dout(pre_grp_fu_465_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_469_p0),
    .din1(grp_fu_469_p1),
    .ce(grp_fu_469_ce),
    .dout(pre_grp_fu_469_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_473_p0),
    .din1(grp_fu_473_p1),
    .ce(grp_fu_473_ce),
    .dout(pre_grp_fu_473_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_477_p0),
    .din1(grp_fu_477_p1),
    .ce(grp_fu_477_ce),
    .dout(pre_grp_fu_477_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_481_p0),
    .din1(grp_fu_481_p1),
    .ce(grp_fu_481_ce),
    .dout(pre_grp_fu_481_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_485_p0),
    .din1(grp_fu_485_p1),
    .ce(grp_fu_485_ce),
    .dout(pre_grp_fu_485_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_489_p0),
    .din1(grp_fu_489_p1),
    .ce(grp_fu_489_ce),
    .dout(pre_grp_fu_489_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_493_p0),
    .din1(grp_fu_493_p1),
    .ce(grp_fu_493_ce),
    .dout(pre_grp_fu_493_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_497_p0),
    .din1(grp_fu_497_p1),
    .ce(grp_fu_497_ce),
    .dout(pre_grp_fu_497_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_501_p0),
    .din1(grp_fu_501_p1),
    .ce(grp_fu_501_ce),
    .dout(pre_grp_fu_501_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_505_p0),
    .din1(grp_fu_505_p1),
    .ce(grp_fu_505_ce),
    .dout(pre_grp_fu_505_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_509_p0),
    .din1(grp_fu_509_p1),
    .ce(grp_fu_509_ce),
    .dout(pre_grp_fu_509_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_513_p0),
    .din1(grp_fu_513_p1),
    .ce(grp_fu_513_ce),
    .dout(pre_grp_fu_513_p2)
);
dequant_layer_q_int_fp32_fmul_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_primitive_dsp_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_517_p0),
    .din1(grp_fu_517_p1),
    .ce(grp_fu_517_ce),
    .dout(pre_grp_fu_517_p2)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_521_p0),
    .ce(grp_fu_521_ce),
    .dout(grp_fu_521_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_524_p0),
    .ce(grp_fu_524_ce),
    .dout(grp_fu_524_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_527_p0),
    .ce(grp_fu_527_ce),
    .dout(grp_fu_527_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_530_p0),
    .ce(grp_fu_530_ce),
    .dout(grp_fu_530_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_533_p0),
    .ce(grp_fu_533_ce),
    .dout(grp_fu_533_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_536_p0),
    .ce(grp_fu_536_ce),
    .dout(grp_fu_536_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_539_p0),
    .ce(grp_fu_539_ce),
    .dout(grp_fu_539_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_542_p0),
    .ce(grp_fu_542_ce),
    .dout(grp_fu_542_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_545_p0),
    .ce(grp_fu_545_ce),
    .dout(grp_fu_545_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_548_p0),
    .ce(grp_fu_548_ce),
    .dout(grp_fu_548_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_551_p0),
    .ce(grp_fu_551_ce),
    .dout(grp_fu_551_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_554_p0),
    .ce(grp_fu_554_ce),
    .dout(grp_fu_554_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_557_p0),
    .ce(grp_fu_557_ce),
    .dout(grp_fu_557_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_560_p0),
    .ce(grp_fu_560_ce),
    .dout(grp_fu_560_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_563_p0),
    .ce(grp_fu_563_ce),
    .dout(grp_fu_563_p1)
);
dequant_layer_q_int_fp32_sitofp_32s_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_5_no_dsp_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_566_p0),
    .ce(grp_fu_566_ce),
    .dout(grp_fu_566_p1)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_569_p1),
    .din2(grp_fu_569_p2),
    .din3(grp_fu_569_p3),
    .ce(grp_fu_569_ce),
    .dout(pre_grp_fu_569_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_576_p1),
    .din2(grp_fu_576_p2),
    .din3(grp_fu_576_p3),
    .ce(grp_fu_576_ce),
    .dout(pre_grp_fu_576_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_583_p1),
    .din2(grp_fu_583_p2),
    .din3(grp_fu_583_p3),
    .ce(grp_fu_583_ce),
    .dout(pre_grp_fu_583_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_590_p1),
    .din2(grp_fu_590_p2),
    .din3(grp_fu_590_p3),
    .ce(grp_fu_590_ce),
    .dout(pre_grp_fu_590_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_597_p1),
    .din2(grp_fu_597_p2),
    .din3(grp_fu_597_p3),
    .ce(grp_fu_597_ce),
    .dout(pre_grp_fu_597_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_604_p1),
    .din2(grp_fu_604_p2),
    .din3(grp_fu_604_p3),
    .ce(grp_fu_604_ce),
    .dout(pre_grp_fu_604_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_611_p1),
    .din2(grp_fu_611_p2),
    .din3(grp_fu_611_p3),
    .ce(grp_fu_611_ce),
    .dout(pre_grp_fu_611_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_618_p1),
    .din2(grp_fu_618_p2),
    .din3(grp_fu_618_p3),
    .ce(grp_fu_618_ce),
    .dout(pre_grp_fu_618_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_625_p1),
    .din2(grp_fu_625_p2),
    .din3(grp_fu_625_p3),
    .ce(grp_fu_625_ce),
    .dout(pre_grp_fu_625_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_632_p1),
    .din2(grp_fu_632_p2),
    .din3(grp_fu_632_p3),
    .ce(grp_fu_632_ce),
    .dout(pre_grp_fu_632_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_639_p1),
    .din2(grp_fu_639_p2),
    .din3(grp_fu_639_p3),
    .ce(grp_fu_639_ce),
    .dout(pre_grp_fu_639_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_646_p1),
    .din2(grp_fu_646_p2),
    .din3(grp_fu_646_p3),
    .ce(grp_fu_646_ce),
    .dout(pre_grp_fu_646_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_653_p1),
    .din2(grp_fu_653_p2),
    .din3(grp_fu_653_p3),
    .ce(grp_fu_653_ce),
    .dout(pre_grp_fu_653_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_660_p1),
    .din2(grp_fu_660_p2),
    .din3(grp_fu_660_p3),
    .ce(grp_fu_660_ce),
    .dout(pre_grp_fu_660_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_667_p1),
    .din2(grp_fu_667_p2),
    .din3(grp_fu_667_p3),
    .ce(grp_fu_667_ce),
    .dout(pre_grp_fu_667_p4)
);
dequant_layer_q_int_fp32_fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmadd_32ns_32ns_32ns_32ns_32_3_primitive_dsp_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_674_p1),
    .din2(grp_fu_674_p2),
    .din3(grp_fu_674_p3),
    .ce(grp_fu_674_ce),
    .dout(pre_grp_fu_674_p4)
);
dequant_layer_q_int_fp32_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_393_ce <= 1'b1;
    end else begin
        grp_fu_393_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_397_ce <= 1'b1;
    end else begin
        grp_fu_397_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_401_ce <= 1'b1;
    end else begin
        grp_fu_401_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_405_ce <= 1'b1;
    end else begin
        grp_fu_405_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_409_ce <= 1'b1;
    end else begin
        grp_fu_409_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_413_ce <= 1'b1;
    end else begin
        grp_fu_413_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_417_ce <= 1'b1;
    end else begin
        grp_fu_417_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_421_ce <= 1'b1;
    end else begin
        grp_fu_421_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_425_ce <= 1'b1;
    end else begin
        grp_fu_425_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_429_ce <= 1'b1;
    end else begin
        grp_fu_429_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_433_ce <= 1'b1;
    end else begin
        grp_fu_433_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_437_ce <= 1'b1;
    end else begin
        grp_fu_437_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_441_ce <= 1'b1;
    end else begin
        grp_fu_441_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_445_ce <= 1'b1;
    end else begin
        grp_fu_445_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_449_ce <= 1'b1;
    end else begin
        grp_fu_449_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_453_ce <= 1'b1;
    end else begin
        grp_fu_453_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_457_ce <= 1'b1;
    end else begin
        grp_fu_457_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_461_ce <= 1'b1;
    end else begin
        grp_fu_461_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_465_ce <= 1'b1;
    end else begin
        grp_fu_465_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_469_ce <= 1'b1;
    end else begin
        grp_fu_469_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_473_ce <= 1'b1;
    end else begin
        grp_fu_473_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_477_ce <= 1'b1;
    end else begin
        grp_fu_477_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_481_ce <= 1'b1;
    end else begin
        grp_fu_481_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_485_ce <= 1'b1;
    end else begin
        grp_fu_485_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_489_ce <= 1'b1;
    end else begin
        grp_fu_489_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_493_ce <= 1'b1;
    end else begin
        grp_fu_493_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_497_ce <= 1'b1;
    end else begin
        grp_fu_497_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_501_ce <= 1'b1;
    end else begin
        grp_fu_501_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_505_ce <= 1'b1;
    end else begin
        grp_fu_505_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_509_ce <= 1'b1;
    end else begin
        grp_fu_509_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_513_ce <= 1'b1;
    end else begin
        grp_fu_513_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_517_ce <= 1'b1;
    end else begin
        grp_fu_517_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_569_ce <= 1'b1;
    end else begin
        grp_fu_569_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_576_ce <= 1'b1;
    end else begin
        grp_fu_576_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_583_ce <= 1'b1;
    end else begin
        grp_fu_583_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_590_ce <= 1'b1;
    end else begin
        grp_fu_590_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_597_ce <= 1'b1;
    end else begin
        grp_fu_597_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_604_ce <= 1'b1;
    end else begin
        grp_fu_604_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_611_ce <= 1'b1;
    end else begin
        grp_fu_611_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_618_ce <= 1'b1;
    end else begin
        grp_fu_618_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_625_ce <= 1'b1;
    end else begin
        grp_fu_625_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_632_ce <= 1'b1;
    end else begin
        grp_fu_632_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_639_ce <= 1'b1;
    end else begin
        grp_fu_639_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_646_ce <= 1'b1;
    end else begin
        grp_fu_646_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_653_ce <= 1'b1;
    end else begin
        grp_fu_653_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_660_ce <= 1'b1;
    end else begin
        grp_fu_660_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_667_ce <= 1'b1;
    end else begin
        grp_fu_667_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_674_ce <= 1'b1;
    end else begin
        grp_fu_674_ce <= 1'b0;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln889_fu_769_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_178 <= k_2_fu_763_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_178 <= 12'd0;
        end
    end
end
always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        trunc_ln91_15_reg_1904_pp0_iter2_reg <= trunc_ln91_15_reg_1904;
        trunc_ln91_15_reg_1904_pp0_iter3_reg <= trunc_ln91_15_reg_1904_pp0_iter2_reg;
        trunc_ln91_15_reg_1904_pp0_iter4_reg <= trunc_ln91_15_reg_1904_pp0_iter3_reg;
        trunc_ln91_15_reg_1904_pp0_iter5_reg <= trunc_ln91_15_reg_1904_pp0_iter4_reg;
        trunc_ln91_15_reg_1904_pp0_iter6_reg <= trunc_ln91_15_reg_1904_pp0_iter5_reg;
        trunc_ln91_15_reg_1904_pp0_iter7_reg <= trunc_ln91_15_reg_1904_pp0_iter6_reg;
        trunc_ln91_15_reg_1904_pp0_iter8_reg <= trunc_ln91_15_reg_1904_pp0_iter7_reg;
        trunc_ln91_16_reg_1909_pp0_iter2_reg <= trunc_ln91_16_reg_1909;
        trunc_ln91_16_reg_1909_pp0_iter3_reg <= trunc_ln91_16_reg_1909_pp0_iter2_reg;
        trunc_ln91_16_reg_1909_pp0_iter4_reg <= trunc_ln91_16_reg_1909_pp0_iter3_reg;
        trunc_ln91_16_reg_1909_pp0_iter5_reg <= trunc_ln91_16_reg_1909_pp0_iter4_reg;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln91_10_reg_1879 <= {{input_stream_s_dout[227:209]}};
        trunc_ln91_11_reg_1884 <= {{input_stream_s_dout[246:228]}};
        trunc_ln91_12_reg_1889 <= {{input_stream_s_dout[265:247]}};
        trunc_ln91_13_reg_1894 <= {{input_stream_s_dout[284:266]}};
        trunc_ln91_14_reg_1899 <= {{input_stream_s_dout[303:285]}};
        trunc_ln91_15_reg_1904 <= trunc_ln91_15_fu_945_p1;
        trunc_ln91_16_reg_1909 <= {{weight_s_sum_stream_s_dout[63:32]}};
        trunc_ln91_1_reg_1864 <= {{input_stream_s_dout[170:152]}};
        trunc_ln91_2_reg_1869 <= {{input_stream_s_dout[189:171]}};
        trunc_ln91_3_reg_1859 <= {{input_stream_s_dout[151:133]}};
        trunc_ln91_4_reg_1874 <= {{input_stream_s_dout[208:190]}};
        trunc_ln91_5_reg_1829 <= {{input_stream_s_dout[37:19]}};
        trunc_ln91_6_reg_1834 <= {{input_stream_s_dout[56:38]}};
        trunc_ln91_7_reg_1839 <= {{input_stream_s_dout[75:57]}};
        trunc_ln91_8_reg_1844 <= {{input_stream_s_dout[94:76]}};
        trunc_ln91_9_reg_1849 <= {{input_stream_s_dout[113:95]}};
        trunc_ln91_reg_1824 <= trunc_ln91_fu_789_p1;
        trunc_ln91_s_reg_1854 <= {{input_stream_s_dout[132:114]}};
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        grp_fu_393_p0 <= grp_fu_521_p1;
        grp_fu_393_p1 <= s_load;
        grp_fu_397_p0 <= b_load;
        grp_fu_397_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_401_p0 <= grp_fu_524_p1;
        grp_fu_401_p1 <= s_load_1;
        grp_fu_405_p0 <= b_load_1;
        grp_fu_405_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_409_p0 <= grp_fu_527_p1;
        grp_fu_409_p1 <= s_load_2;
        grp_fu_413_p0 <= b_load_2;
        grp_fu_413_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_417_p0 <= grp_fu_530_p1;
        grp_fu_417_p1 <= s_load_3;
        grp_fu_421_p0 <= b_load_3;
        grp_fu_421_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_425_p0 <= grp_fu_533_p1;
        grp_fu_425_p1 <= s_load_4;
        grp_fu_429_p0 <= b_load_4;
        grp_fu_429_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_433_p0 <= grp_fu_536_p1;
        grp_fu_433_p1 <= s_load_5;
        grp_fu_437_p0 <= b_load_5;
        grp_fu_437_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_441_p0 <= grp_fu_539_p1;
        grp_fu_441_p1 <= s_load_6;
        grp_fu_445_p0 <= b_load_6;
        grp_fu_445_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_449_p0 <= grp_fu_542_p1;
        grp_fu_449_p1 <= s_load_7;
        grp_fu_453_p0 <= b_load_7;
        grp_fu_453_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_457_p0 <= grp_fu_545_p1;
        grp_fu_457_p1 <= s_load_8;
        grp_fu_461_p0 <= b_load_8;
        grp_fu_461_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_465_p0 <= grp_fu_548_p1;
        grp_fu_465_p1 <= s_load_9;
        grp_fu_469_p0 <= b_load_9;
        grp_fu_469_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_473_p0 <= grp_fu_551_p1;
        grp_fu_473_p1 <= s_load_10;
        grp_fu_477_p0 <= b_load_10;
        grp_fu_477_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_481_p0 <= grp_fu_554_p1;
        grp_fu_481_p1 <= s_load_11;
        grp_fu_485_p0 <= b_load_11;
        grp_fu_485_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_489_p0 <= grp_fu_557_p1;
        grp_fu_489_p1 <= s_load_12;
        grp_fu_493_p0 <= b_load_12;
        grp_fu_493_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_497_p0 <= grp_fu_560_p1;
        grp_fu_497_p1 <= s_load_13;
        grp_fu_501_p0 <= b_load_13;
        grp_fu_501_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_505_p0 <= grp_fu_563_p1;
        grp_fu_505_p1 <= s_load_14;
        grp_fu_509_p0 <= b_load_14;
        grp_fu_509_p1 <= bitcast_ln91_1_fu_1087_p1;
        grp_fu_513_p0 <= grp_fu_566_p1;
        grp_fu_513_p1 <= s_load_15;
        grp_fu_517_p0 <= b_load_15;
        grp_fu_517_p1 <= bitcast_ln91_1_fu_1087_p1;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        grp_fu_569_p1 <= grp_fu_393_p2;
        grp_fu_569_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_569_p3 <= grp_fu_397_p2;
        grp_fu_576_p1 <= grp_fu_401_p2;
        grp_fu_576_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_576_p3 <= grp_fu_405_p2;
        grp_fu_583_p1 <= grp_fu_409_p2;
        grp_fu_583_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_583_p3 <= grp_fu_413_p2;
        grp_fu_590_p1 <= grp_fu_417_p2;
        grp_fu_590_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_590_p3 <= grp_fu_421_p2;
        grp_fu_597_p1 <= grp_fu_425_p2;
        grp_fu_597_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_597_p3 <= grp_fu_429_p2;
        grp_fu_604_p1 <= grp_fu_433_p2;
        grp_fu_604_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_604_p3 <= grp_fu_437_p2;
        grp_fu_611_p1 <= grp_fu_441_p2;
        grp_fu_611_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_611_p3 <= grp_fu_445_p2;
        grp_fu_618_p1 <= grp_fu_449_p2;
        grp_fu_618_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_618_p3 <= grp_fu_453_p2;
        grp_fu_625_p1 <= grp_fu_457_p2;
        grp_fu_625_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_625_p3 <= grp_fu_461_p2;
        grp_fu_632_p1 <= grp_fu_465_p2;
        grp_fu_632_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_632_p3 <= grp_fu_469_p2;
        grp_fu_639_p1 <= grp_fu_473_p2;
        grp_fu_639_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_639_p3 <= grp_fu_477_p2;
        grp_fu_646_p1 <= grp_fu_481_p2;
        grp_fu_646_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_646_p3 <= grp_fu_485_p2;
        grp_fu_653_p1 <= grp_fu_489_p2;
        grp_fu_653_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_653_p3 <= grp_fu_493_p2;
        grp_fu_660_p1 <= grp_fu_497_p2;
        grp_fu_660_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_660_p3 <= grp_fu_501_p2;
        grp_fu_667_p1 <= grp_fu_505_p2;
        grp_fu_667_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_667_p3 <= grp_fu_509_p2;
        grp_fu_674_p1 <= grp_fu_513_p2;
        grp_fu_674_p2 <= bitcast_ln91_fu_1314_p1;
        grp_fu_674_p3 <= grp_fu_517_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_393_ce == 1'b1)) begin
        pre_grp_fu_393_p2_reg <= pre_grp_fu_393_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_397_ce == 1'b1)) begin
        pre_grp_fu_397_p2_reg <= pre_grp_fu_397_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_401_ce == 1'b1)) begin
        pre_grp_fu_401_p2_reg <= pre_grp_fu_401_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_405_ce == 1'b1)) begin
        pre_grp_fu_405_p2_reg <= pre_grp_fu_405_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_409_ce == 1'b1)) begin
        pre_grp_fu_409_p2_reg <= pre_grp_fu_409_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_413_ce == 1'b1)) begin
        pre_grp_fu_413_p2_reg <= pre_grp_fu_413_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_417_ce == 1'b1)) begin
        pre_grp_fu_417_p2_reg <= pre_grp_fu_417_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_421_ce == 1'b1)) begin
        pre_grp_fu_421_p2_reg <= pre_grp_fu_421_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_425_ce == 1'b1)) begin
        pre_grp_fu_425_p2_reg <= pre_grp_fu_425_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_429_ce == 1'b1)) begin
        pre_grp_fu_429_p2_reg <= pre_grp_fu_429_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_433_ce == 1'b1)) begin
        pre_grp_fu_433_p2_reg <= pre_grp_fu_433_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_437_ce == 1'b1)) begin
        pre_grp_fu_437_p2_reg <= pre_grp_fu_437_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_441_ce == 1'b1)) begin
        pre_grp_fu_441_p2_reg <= pre_grp_fu_441_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_445_ce == 1'b1)) begin
        pre_grp_fu_445_p2_reg <= pre_grp_fu_445_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_449_ce == 1'b1)) begin
        pre_grp_fu_449_p2_reg <= pre_grp_fu_449_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_453_ce == 1'b1)) begin
        pre_grp_fu_453_p2_reg <= pre_grp_fu_453_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_457_ce == 1'b1)) begin
        pre_grp_fu_457_p2_reg <= pre_grp_fu_457_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_461_ce == 1'b1)) begin
        pre_grp_fu_461_p2_reg <= pre_grp_fu_461_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_465_ce == 1'b1)) begin
        pre_grp_fu_465_p2_reg <= pre_grp_fu_465_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_469_ce == 1'b1)) begin
        pre_grp_fu_469_p2_reg <= pre_grp_fu_469_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_473_ce == 1'b1)) begin
        pre_grp_fu_473_p2_reg <= pre_grp_fu_473_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_477_ce == 1'b1)) begin
        pre_grp_fu_477_p2_reg <= pre_grp_fu_477_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_481_ce == 1'b1)) begin
        pre_grp_fu_481_p2_reg <= pre_grp_fu_481_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_485_ce == 1'b1)) begin
        pre_grp_fu_485_p2_reg <= pre_grp_fu_485_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_489_ce == 1'b1)) begin
        pre_grp_fu_489_p2_reg <= pre_grp_fu_489_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_493_ce == 1'b1)) begin
        pre_grp_fu_493_p2_reg <= pre_grp_fu_493_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_497_ce == 1'b1)) begin
        pre_grp_fu_497_p2_reg <= pre_grp_fu_497_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_501_ce == 1'b1)) begin
        pre_grp_fu_501_p2_reg <= pre_grp_fu_501_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_505_ce == 1'b1)) begin
        pre_grp_fu_505_p2_reg <= pre_grp_fu_505_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_509_ce == 1'b1)) begin
        pre_grp_fu_509_p2_reg <= pre_grp_fu_509_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_513_ce == 1'b1)) begin
        pre_grp_fu_513_p2_reg <= pre_grp_fu_513_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_517_ce == 1'b1)) begin
        pre_grp_fu_517_p2_reg <= pre_grp_fu_517_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_569_ce == 1'b1)) begin
        pre_grp_fu_569_p4_reg <= pre_grp_fu_569_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_576_ce == 1'b1)) begin
        pre_grp_fu_576_p4_reg <= pre_grp_fu_576_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_583_ce == 1'b1)) begin
        pre_grp_fu_583_p4_reg <= pre_grp_fu_583_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_590_ce == 1'b1)) begin
        pre_grp_fu_590_p4_reg <= pre_grp_fu_590_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_597_ce == 1'b1)) begin
        pre_grp_fu_597_p4_reg <= pre_grp_fu_597_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_604_ce == 1'b1)) begin
        pre_grp_fu_604_p4_reg <= pre_grp_fu_604_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_611_ce == 1'b1)) begin
        pre_grp_fu_611_p4_reg <= pre_grp_fu_611_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_618_ce == 1'b1)) begin
        pre_grp_fu_618_p4_reg <= pre_grp_fu_618_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_625_ce == 1'b1)) begin
        pre_grp_fu_625_p4_reg <= pre_grp_fu_625_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_632_ce == 1'b1)) begin
        pre_grp_fu_632_p4_reg <= pre_grp_fu_632_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_639_ce == 1'b1)) begin
        pre_grp_fu_639_p4_reg <= pre_grp_fu_639_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_646_ce == 1'b1)) begin
        pre_grp_fu_646_p4_reg <= pre_grp_fu_646_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_653_ce == 1'b1)) begin
        pre_grp_fu_653_p4_reg <= pre_grp_fu_653_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_660_ce == 1'b1)) begin
        pre_grp_fu_660_p4_reg <= pre_grp_fu_660_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_667_ce == 1'b1)) begin
        pre_grp_fu_667_p4_reg <= pre_grp_fu_667_p4;
    end
end
always @ (posedge ap_clk) begin
    if ((grp_fu_674_ce == 1'b1)) begin
        pre_grp_fu_674_p4_reg <= pre_grp_fu_674_p4;
    end
end
always @ (*) begin
    if (((icmp_ln889_fu_769_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end
always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end
always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end
always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_1 = 12'd0;
    end else begin
        ap_sig_allocacmp_k_1 = k_fu_178;
    end
end
always @ (*) begin
    if ((grp_fu_393_ce == 1'b1)) begin
        grp_fu_393_p2 = pre_grp_fu_393_p2;
    end else begin
        grp_fu_393_p2 = pre_grp_fu_393_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_397_ce == 1'b1)) begin
        grp_fu_397_p2 = pre_grp_fu_397_p2;
    end else begin
        grp_fu_397_p2 = pre_grp_fu_397_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_401_ce == 1'b1)) begin
        grp_fu_401_p2 = pre_grp_fu_401_p2;
    end else begin
        grp_fu_401_p2 = pre_grp_fu_401_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_405_ce == 1'b1)) begin
        grp_fu_405_p2 = pre_grp_fu_405_p2;
    end else begin
        grp_fu_405_p2 = pre_grp_fu_405_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_409_ce == 1'b1)) begin
        grp_fu_409_p2 = pre_grp_fu_409_p2;
    end else begin
        grp_fu_409_p2 = pre_grp_fu_409_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_413_ce == 1'b1)) begin
        grp_fu_413_p2 = pre_grp_fu_413_p2;
    end else begin
        grp_fu_413_p2 = pre_grp_fu_413_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_417_ce == 1'b1)) begin
        grp_fu_417_p2 = pre_grp_fu_417_p2;
    end else begin
        grp_fu_417_p2 = pre_grp_fu_417_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_421_ce == 1'b1)) begin
        grp_fu_421_p2 = pre_grp_fu_421_p2;
    end else begin
        grp_fu_421_p2 = pre_grp_fu_421_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_425_ce == 1'b1)) begin
        grp_fu_425_p2 = pre_grp_fu_425_p2;
    end else begin
        grp_fu_425_p2 = pre_grp_fu_425_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_429_ce == 1'b1)) begin
        grp_fu_429_p2 = pre_grp_fu_429_p2;
    end else begin
        grp_fu_429_p2 = pre_grp_fu_429_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_433_ce == 1'b1)) begin
        grp_fu_433_p2 = pre_grp_fu_433_p2;
    end else begin
        grp_fu_433_p2 = pre_grp_fu_433_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_437_ce == 1'b1)) begin
        grp_fu_437_p2 = pre_grp_fu_437_p2;
    end else begin
        grp_fu_437_p2 = pre_grp_fu_437_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_441_ce == 1'b1)) begin
        grp_fu_441_p2 = pre_grp_fu_441_p2;
    end else begin
        grp_fu_441_p2 = pre_grp_fu_441_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_445_ce == 1'b1)) begin
        grp_fu_445_p2 = pre_grp_fu_445_p2;
    end else begin
        grp_fu_445_p2 = pre_grp_fu_445_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_449_ce == 1'b1)) begin
        grp_fu_449_p2 = pre_grp_fu_449_p2;
    end else begin
        grp_fu_449_p2 = pre_grp_fu_449_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_453_ce == 1'b1)) begin
        grp_fu_453_p2 = pre_grp_fu_453_p2;
    end else begin
        grp_fu_453_p2 = pre_grp_fu_453_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_457_ce == 1'b1)) begin
        grp_fu_457_p2 = pre_grp_fu_457_p2;
    end else begin
        grp_fu_457_p2 = pre_grp_fu_457_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_461_ce == 1'b1)) begin
        grp_fu_461_p2 = pre_grp_fu_461_p2;
    end else begin
        grp_fu_461_p2 = pre_grp_fu_461_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_465_ce == 1'b1)) begin
        grp_fu_465_p2 = pre_grp_fu_465_p2;
    end else begin
        grp_fu_465_p2 = pre_grp_fu_465_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_469_ce == 1'b1)) begin
        grp_fu_469_p2 = pre_grp_fu_469_p2;
    end else begin
        grp_fu_469_p2 = pre_grp_fu_469_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_473_ce == 1'b1)) begin
        grp_fu_473_p2 = pre_grp_fu_473_p2;
    end else begin
        grp_fu_473_p2 = pre_grp_fu_473_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_477_ce == 1'b1)) begin
        grp_fu_477_p2 = pre_grp_fu_477_p2;
    end else begin
        grp_fu_477_p2 = pre_grp_fu_477_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_481_ce == 1'b1)) begin
        grp_fu_481_p2 = pre_grp_fu_481_p2;
    end else begin
        grp_fu_481_p2 = pre_grp_fu_481_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_485_ce == 1'b1)) begin
        grp_fu_485_p2 = pre_grp_fu_485_p2;
    end else begin
        grp_fu_485_p2 = pre_grp_fu_485_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_489_ce == 1'b1)) begin
        grp_fu_489_p2 = pre_grp_fu_489_p2;
    end else begin
        grp_fu_489_p2 = pre_grp_fu_489_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_493_ce == 1'b1)) begin
        grp_fu_493_p2 = pre_grp_fu_493_p2;
    end else begin
        grp_fu_493_p2 = pre_grp_fu_493_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_497_ce == 1'b1)) begin
        grp_fu_497_p2 = pre_grp_fu_497_p2;
    end else begin
        grp_fu_497_p2 = pre_grp_fu_497_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_501_ce == 1'b1)) begin
        grp_fu_501_p2 = pre_grp_fu_501_p2;
    end else begin
        grp_fu_501_p2 = pre_grp_fu_501_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_505_ce == 1'b1)) begin
        grp_fu_505_p2 = pre_grp_fu_505_p2;
    end else begin
        grp_fu_505_p2 = pre_grp_fu_505_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_509_ce == 1'b1)) begin
        grp_fu_509_p2 = pre_grp_fu_509_p2;
    end else begin
        grp_fu_509_p2 = pre_grp_fu_509_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_513_ce == 1'b1)) begin
        grp_fu_513_p2 = pre_grp_fu_513_p2;
    end else begin
        grp_fu_513_p2 = pre_grp_fu_513_p2_reg;
    end
end
always @ (*) begin
    if ((grp_fu_517_ce == 1'b1)) begin
        grp_fu_517_p2 = pre_grp_fu_517_p2;
    end else begin
        grp_fu_517_p2 = pre_grp_fu_517_p2_reg;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_521_ce = 1'b1;
    end else begin
        grp_fu_521_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_524_ce = 1'b1;
    end else begin
        grp_fu_524_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_527_ce = 1'b1;
    end else begin
        grp_fu_527_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_530_ce = 1'b1;
    end else begin
        grp_fu_530_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_533_ce = 1'b1;
    end else begin
        grp_fu_533_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_536_ce = 1'b1;
    end else begin
        grp_fu_536_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_539_ce = 1'b1;
    end else begin
        grp_fu_539_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_542_ce = 1'b1;
    end else begin
        grp_fu_542_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_545_ce = 1'b1;
    end else begin
        grp_fu_545_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_548_ce = 1'b1;
    end else begin
        grp_fu_548_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_551_ce = 1'b1;
    end else begin
        grp_fu_551_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_554_ce = 1'b1;
    end else begin
        grp_fu_554_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_557_ce = 1'b1;
    end else begin
        grp_fu_557_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_560_ce = 1'b1;
    end else begin
        grp_fu_560_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_563_ce = 1'b1;
    end else begin
        grp_fu_563_ce = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_566_ce = 1'b1;
    end else begin
        grp_fu_566_ce = 1'b0;
    end
end
always @ (*) begin
    if ((grp_fu_569_ce == 1'b1)) begin
        grp_fu_569_p4 = pre_grp_fu_569_p4;
    end else begin
        grp_fu_569_p4 = pre_grp_fu_569_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_576_ce == 1'b1)) begin
        grp_fu_576_p4 = pre_grp_fu_576_p4;
    end else begin
        grp_fu_576_p4 = pre_grp_fu_576_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_583_ce == 1'b1)) begin
        grp_fu_583_p4 = pre_grp_fu_583_p4;
    end else begin
        grp_fu_583_p4 = pre_grp_fu_583_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_590_ce == 1'b1)) begin
        grp_fu_590_p4 = pre_grp_fu_590_p4;
    end else begin
        grp_fu_590_p4 = pre_grp_fu_590_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_597_ce == 1'b1)) begin
        grp_fu_597_p4 = pre_grp_fu_597_p4;
    end else begin
        grp_fu_597_p4 = pre_grp_fu_597_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_604_ce == 1'b1)) begin
        grp_fu_604_p4 = pre_grp_fu_604_p4;
    end else begin
        grp_fu_604_p4 = pre_grp_fu_604_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_611_ce == 1'b1)) begin
        grp_fu_611_p4 = pre_grp_fu_611_p4;
    end else begin
        grp_fu_611_p4 = pre_grp_fu_611_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_618_ce == 1'b1)) begin
        grp_fu_618_p4 = pre_grp_fu_618_p4;
    end else begin
        grp_fu_618_p4 = pre_grp_fu_618_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_625_ce == 1'b1)) begin
        grp_fu_625_p4 = pre_grp_fu_625_p4;
    end else begin
        grp_fu_625_p4 = pre_grp_fu_625_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_632_ce == 1'b1)) begin
        grp_fu_632_p4 = pre_grp_fu_632_p4;
    end else begin
        grp_fu_632_p4 = pre_grp_fu_632_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_639_ce == 1'b1)) begin
        grp_fu_639_p4 = pre_grp_fu_639_p4;
    end else begin
        grp_fu_639_p4 = pre_grp_fu_639_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_646_ce == 1'b1)) begin
        grp_fu_646_p4 = pre_grp_fu_646_p4;
    end else begin
        grp_fu_646_p4 = pre_grp_fu_646_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_653_ce == 1'b1)) begin
        grp_fu_653_p4 = pre_grp_fu_653_p4;
    end else begin
        grp_fu_653_p4 = pre_grp_fu_653_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_660_ce == 1'b1)) begin
        grp_fu_660_p4 = pre_grp_fu_660_p4;
    end else begin
        grp_fu_660_p4 = pre_grp_fu_660_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_667_ce == 1'b1)) begin
        grp_fu_667_p4 = pre_grp_fu_667_p4;
    end else begin
        grp_fu_667_p4 = pre_grp_fu_667_p4_reg;
    end
end
always @ (*) begin
    if ((grp_fu_674_ce == 1'b1)) begin
        grp_fu_674_p4 = pre_grp_fu_674_p4;
    end else begin
        grp_fu_674_p4 = pre_grp_fu_674_p4_reg;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_s_blk_n = input_stream_s_empty_n;
    end else begin
        input_stream_s_blk_n = 1'b1;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_s_read_local = 1'b1;
    end else begin
        input_stream_s_read_local = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        output_stream_s_blk_n = output_stream_s_full_n;
    end else begin
        output_stream_s_blk_n = 1'b1;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        output_stream_s_write_local = 1'b1;
    end else begin
        output_stream_s_write_local = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_s_sum_stream_s_blk_n = weight_s_sum_stream_s_empty_n;
    end else begin
        weight_s_sum_stream_s_blk_n = 1'b1;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_s_sum_stream_s_read_local = 1'b1;
    end else begin
        weight_s_sum_stream_s_read_local = 1'b0;
    end
end
always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end
assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];
assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);
always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter12)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end
always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter12)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end
always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter12)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end
always @ (*) begin
    ap_block_state13_pp0_stage0_iter12 = (output_stream_s_full_n == 1'b0);
end
always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((weight_s_sum_stream_s_empty_n == 1'b0) | (input_stream_s_empty_n == 1'b0));
end
assign ap_done = ap_done_sig;
assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);
assign ap_enable_reg_pp0_iter0 = ap_start_int;
assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;
assign ap_ready = ap_ready_sig;
assign bitcast_ln150_10_fu_1549_p1 = grp_fu_639_p4;
assign bitcast_ln150_11_fu_1553_p1 = grp_fu_646_p4;
assign bitcast_ln150_12_fu_1557_p1 = grp_fu_653_p4;
assign bitcast_ln150_13_fu_1561_p1 = grp_fu_660_p4;
assign bitcast_ln150_14_fu_1565_p1 = grp_fu_667_p4;
assign bitcast_ln150_15_fu_1569_p1 = grp_fu_674_p4;
assign bitcast_ln150_1_fu_1513_p1 = grp_fu_576_p4;
assign bitcast_ln150_2_fu_1517_p1 = grp_fu_583_p4;
assign bitcast_ln150_3_fu_1521_p1 = grp_fu_590_p4;
assign bitcast_ln150_4_fu_1525_p1 = grp_fu_597_p4;
assign bitcast_ln150_5_fu_1529_p1 = grp_fu_604_p4;
assign bitcast_ln150_6_fu_1533_p1 = grp_fu_611_p4;
assign bitcast_ln150_7_fu_1537_p1 = grp_fu_618_p4;
assign bitcast_ln150_8_fu_1541_p1 = grp_fu_625_p4;
assign bitcast_ln150_9_fu_1545_p1 = grp_fu_632_p4;
assign bitcast_ln150_fu_1509_p1 = grp_fu_569_p4;
assign bitcast_ln91_1_fu_1087_p1 = trunc_ln91_16_reg_1909_pp0_iter5_reg;
assign bitcast_ln91_fu_1314_p1 = trunc_ln91_15_reg_1904_pp0_iter8_reg;
assign grp_fu_521_p0 = $signed(trunc_ln91_reg_1824);
assign grp_fu_524_p0 = $signed(trunc_ln91_5_reg_1829);
assign grp_fu_527_p0 = $signed(trunc_ln91_6_reg_1834);
assign grp_fu_530_p0 = $signed(trunc_ln91_7_reg_1839);
assign grp_fu_533_p0 = $signed(trunc_ln91_8_reg_1844);
assign grp_fu_536_p0 = $signed(trunc_ln91_9_reg_1849);
assign grp_fu_539_p0 = $signed(trunc_ln91_s_reg_1854);
assign grp_fu_542_p0 = $signed(trunc_ln91_3_reg_1859);
assign grp_fu_545_p0 = $signed(trunc_ln91_1_reg_1864);
assign grp_fu_548_p0 = $signed(trunc_ln91_2_reg_1869);
assign grp_fu_551_p0 = $signed(trunc_ln91_4_reg_1874);
assign grp_fu_554_p0 = $signed(trunc_ln91_10_reg_1879);
assign grp_fu_557_p0 = $signed(trunc_ln91_11_reg_1884);
assign grp_fu_560_p0 = $signed(trunc_ln91_12_reg_1889);
assign grp_fu_563_p0 = $signed(trunc_ln91_13_reg_1894);
assign grp_fu_566_p0 = $signed(trunc_ln91_14_reg_1899);
assign icmp_ln889_fu_769_p2 = ((ap_sig_allocacmp_k_1 == 12'd2048) ? 1'b1 : 1'b0);
assign input_stream_s_read = input_stream_s_read_local;
assign k_2_fu_763_p2 = (ap_sig_allocacmp_k_1 + 12'd1);
assign or_ln150_2_fu_1573_p17 = {{{{{{{{{{{{{{{{bitcast_ln150_15_fu_1569_p1}, {bitcast_ln150_14_fu_1565_p1}}, {bitcast_ln150_13_fu_1561_p1}}, {bitcast_ln150_12_fu_1557_p1}}, {bitcast_ln150_11_fu_1553_p1}}, {bitcast_ln150_10_fu_1549_p1}}, {bitcast_ln150_9_fu_1545_p1}}, {bitcast_ln150_8_fu_1541_p1}}, {bitcast_ln150_7_fu_1537_p1}}, {bitcast_ln150_6_fu_1533_p1}}, {bitcast_ln150_5_fu_1529_p1}}, {bitcast_ln150_4_fu_1525_p1}}, {bitcast_ln150_3_fu_1521_p1}}, {bitcast_ln150_2_fu_1517_p1}}, {bitcast_ln150_1_fu_1513_p1}}, {bitcast_ln150_fu_1509_p1}};
assign output_stream_s_din = zext_ln150_fu_1609_p1;
assign output_stream_s_write = output_stream_s_write_local;
assign trunc_ln91_15_fu_945_p1 = weight_s_sum_stream_s_dout[31:0];
assign trunc_ln91_fu_789_p1 = input_stream_s_dout[18:0];
assign weight_s_sum_stream_s_read = weight_s_sum_stream_s_read_local;
assign zext_ln150_fu_1609_p1 = or_ln150_2_fu_1573_p17;
endmodule