`timescale 1 ns / 1 ps
// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
 
module Linear_Layer_i4xi4_q_dataflow_parent_loop_proc (
        output_stream_s_din,
        output_stream_s_full_n,
        output_stream_s_write,
        A_address0,
        A_ce0,
        A_d0,
        A_q0,
        A_we0,
        A_address1,
        A_ce1,
        A_d1,
        A_q1,
        A_we1,
        A_1_address0,
        A_1_ce0,
        A_1_d0,
        A_1_q0,
        A_1_we0,
        A_1_address1,
        A_1_ce1,
        A_1_d1,
        A_1_q1,
        A_1_we1,
        A_2_address0,
        A_2_ce0,
        A_2_d0,
        A_2_q0,
        A_2_we0,
        A_2_address1,
        A_2_ce1,
        A_2_d1,
        A_2_q1,
        A_2_we1,
        A_3_address0,
        A_3_ce0,
        A_3_d0,
        A_3_q0,
        A_3_we0,
        A_3_address1,
        A_3_ce1,
        A_3_d1,
        A_3_q1,
        A_3_we1,
        A_4_address0,
        A_4_ce0,
        A_4_d0,
        A_4_q0,
        A_4_we0,
        A_4_address1,
        A_4_ce1,
        A_4_d1,
        A_4_q1,
        A_4_we1,
        A_5_address0,
        A_5_ce0,
        A_5_d0,
        A_5_q0,
        A_5_we0,
        A_5_address1,
        A_5_ce1,
        A_5_d1,
        A_5_q1,
        A_5_we1,
        A_6_address0,
        A_6_ce0,
        A_6_d0,
        A_6_q0,
        A_6_we0,
        A_6_address1,
        A_6_ce1,
        A_6_d1,
        A_6_q1,
        A_6_we1,
        A_7_address0,
        A_7_ce0,
        A_7_d0,
        A_7_q0,
        A_7_we0,
        A_7_address1,
        A_7_ce1,
        A_7_d1,
        A_7_q1,
        A_7_we1,
        A_8_address0,
        A_8_ce0,
        A_8_d0,
        A_8_q0,
        A_8_we0,
        A_8_address1,
        A_8_ce1,
        A_8_d1,
        A_8_q1,
        A_8_we1,
        A_9_address0,
        A_9_ce0,
        A_9_d0,
        A_9_q0,
        A_9_we0,
        A_9_address1,
        A_9_ce1,
        A_9_d1,
        A_9_q1,
        A_9_we1,
        A_10_address0,
        A_10_ce0,
        A_10_d0,
        A_10_q0,
        A_10_we0,
        A_10_address1,
        A_10_ce1,
        A_10_d1,
        A_10_q1,
        A_10_we1,
        A_11_address0,
        A_11_ce0,
        A_11_d0,
        A_11_q0,
        A_11_we0,
        A_11_address1,
        A_11_ce1,
        A_11_d1,
        A_11_q1,
        A_11_we1,
        A_12_address0,
        A_12_ce0,
        A_12_d0,
        A_12_q0,
        A_12_we0,
        A_12_address1,
        A_12_ce1,
        A_12_d1,
        A_12_q1,
        A_12_we1,
        A_13_address0,
        A_13_ce0,
        A_13_d0,
        A_13_q0,
        A_13_we0,
        A_13_address1,
        A_13_ce1,
        A_13_d1,
        A_13_q1,
        A_13_we1,
        A_14_address0,
        A_14_ce0,
        A_14_d0,
        A_14_q0,
        A_14_we0,
        A_14_address1,
        A_14_ce1,
        A_14_d1,
        A_14_q1,
        A_14_we1,
        A_15_address0,
        A_15_ce0,
        A_15_d0,
        A_15_q0,
        A_15_we0,
        A_15_address1,
        A_15_ce1,
        A_15_d1,
        A_15_q1,
        A_15_we1,
        weight_stream_s_dout,
        weight_stream_s_empty_n,
        weight_stream_s_read,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);
output  [304:0] output_stream_s_din;
input   output_stream_s_full_n;
output   output_stream_s_write;
output  [10:0] A_address0;
output   A_ce0;
output  [3:0] A_d0;
input  [3:0] A_q0;
output   A_we0;
output  [10:0] A_address1;
output   A_ce1;
output  [3:0] A_d1;
input  [3:0] A_q1;
output   A_we1;
output  [10:0] A_1_address0;
output   A_1_ce0;
output  [3:0] A_1_d0;
input  [3:0] A_1_q0;
output   A_1_we0;
output  [10:0] A_1_address1;
output   A_1_ce1;
output  [3:0] A_1_d1;
input  [3:0] A_1_q1;
output   A_1_we1;
output  [10:0] A_2_address0;
output   A_2_ce0;
output  [3:0] A_2_d0;
input  [3:0] A_2_q0;
output   A_2_we0;
output  [10:0] A_2_address1;
output   A_2_ce1;
output  [3:0] A_2_d1;
input  [3:0] A_2_q1;
output   A_2_we1;
output  [10:0] A_3_address0;
output   A_3_ce0;
output  [3:0] A_3_d0;
input  [3:0] A_3_q0;
output   A_3_we0;
output  [10:0] A_3_address1;
output   A_3_ce1;
output  [3:0] A_3_d1;
input  [3:0] A_3_q1;
output   A_3_we1;
output  [10:0] A_4_address0;
output   A_4_ce0;
output  [3:0] A_4_d0;
input  [3:0] A_4_q0;
output   A_4_we0;
output  [10:0] A_4_address1;
output   A_4_ce1;
output  [3:0] A_4_d1;
input  [3:0] A_4_q1;
output   A_4_we1;
output  [10:0] A_5_address0;
output   A_5_ce0;
output  [3:0] A_5_d0;
input  [3:0] A_5_q0;
output   A_5_we0;
output  [10:0] A_5_address1;
output   A_5_ce1;
output  [3:0] A_5_d1;
input  [3:0] A_5_q1;
output   A_5_we1;
output  [10:0] A_6_address0;
output   A_6_ce0;
output  [3:0] A_6_d0;
input  [3:0] A_6_q0;
output   A_6_we0;
output  [10:0] A_6_address1;
output   A_6_ce1;
output  [3:0] A_6_d1;
input  [3:0] A_6_q1;
output   A_6_we1;
output  [10:0] A_7_address0;
output   A_7_ce0;
output  [3:0] A_7_d0;
input  [3:0] A_7_q0;
output   A_7_we0;
output  [10:0] A_7_address1;
output   A_7_ce1;
output  [3:0] A_7_d1;
input  [3:0] A_7_q1;
output   A_7_we1;
output  [10:0] A_8_address0;
output   A_8_ce0;
output  [3:0] A_8_d0;
input  [3:0] A_8_q0;
output   A_8_we0;
output  [10:0] A_8_address1;
output   A_8_ce1;
output  [3:0] A_8_d1;
input  [3:0] A_8_q1;
output   A_8_we1;
output  [10:0] A_9_address0;
output   A_9_ce0;
output  [3:0] A_9_d0;
input  [3:0] A_9_q0;
output   A_9_we0;
output  [10:0] A_9_address1;
output   A_9_ce1;
output  [3:0] A_9_d1;
input  [3:0] A_9_q1;
output   A_9_we1;
output  [10:0] A_10_address0;
output   A_10_ce0;
output  [3:0] A_10_d0;
input  [3:0] A_10_q0;
output   A_10_we0;
output  [10:0] A_10_address1;
output   A_10_ce1;
output  [3:0] A_10_d1;
input  [3:0] A_10_q1;
output   A_10_we1;
output  [10:0] A_11_address0;
output   A_11_ce0;
output  [3:0] A_11_d0;
input  [3:0] A_11_q0;
output   A_11_we0;
output  [10:0] A_11_address1;
output   A_11_ce1;
output  [3:0] A_11_d1;
input  [3:0] A_11_q1;
output   A_11_we1;
output  [10:0] A_12_address0;
output   A_12_ce0;
output  [3:0] A_12_d0;
input  [3:0] A_12_q0;
output   A_12_we0;
output  [10:0] A_12_address1;
output   A_12_ce1;
output  [3:0] A_12_d1;
input  [3:0] A_12_q1;
output   A_12_we1;
output  [10:0] A_13_address0;
output   A_13_ce0;
output  [3:0] A_13_d0;
input  [3:0] A_13_q0;
output   A_13_we0;
output  [10:0] A_13_address1;
output   A_13_ce1;
output  [3:0] A_13_d1;
input  [3:0] A_13_q1;
output   A_13_we1;
output  [10:0] A_14_address0;
output   A_14_ce0;
output  [3:0] A_14_d0;
input  [3:0] A_14_q0;
output   A_14_we0;
output  [10:0] A_14_address1;
output   A_14_ce1;
output  [3:0] A_14_d1;
input  [3:0] A_14_q1;
output   A_14_we1;
output  [10:0] A_15_address0;
output   A_15_ce0;
output  [3:0] A_15_d0;
input  [3:0] A_15_q0;
output   A_15_we0;
output  [10:0] A_15_address1;
output   A_15_ce1;
output  [3:0] A_15_d1;
input  [3:0] A_15_q1;
output   A_15_we1;
input  [128:0] weight_stream_s_dout;
input   weight_stream_s_empty_n;
output   weight_stream_s_read;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;
reg ap_done;
reg ap_ready;
reg ap_idle;
wire   [304:0] dataflow_in_loop_weight_block_loop_U0_output_stream_s_din;
wire    dataflow_in_loop_weight_block_loop_U0_output_stream_s_write;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_0_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_0_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_0_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_0_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_0_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_0_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_0_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_0_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_1_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_1_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_1_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_1_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_1_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_1_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_1_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_1_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_2_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_2_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_2_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_2_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_2_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_2_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_2_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_2_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_3_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_3_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_3_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_3_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_3_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_3_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_3_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_3_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_4_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_4_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_4_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_4_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_4_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_4_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_4_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_4_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_5_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_5_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_5_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_5_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_5_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_5_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_5_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_5_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_6_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_6_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_6_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_6_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_6_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_6_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_6_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_6_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_7_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_7_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_7_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_7_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_7_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_7_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_7_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_7_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_8_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_8_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_8_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_8_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_8_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_8_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_8_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_8_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_9_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_9_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_9_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_9_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_9_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_9_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_9_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_9_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_10_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_10_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_10_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_10_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_10_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_10_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_10_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_10_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_11_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_11_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_11_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_11_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_11_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_11_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_11_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_11_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_12_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_12_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_12_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_12_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_12_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_12_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_12_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_12_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_13_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_13_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_13_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_13_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_13_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_13_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_13_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_13_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_14_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_14_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_14_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_14_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_14_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_14_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_14_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_14_we1;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_15_address0;
wire    dataflow_in_loop_weight_block_loop_U0_A_15_ce0;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_15_d0;
wire    dataflow_in_loop_weight_block_loop_U0_A_15_we0;
wire   [10:0] dataflow_in_loop_weight_block_loop_U0_A_15_address1;
wire    dataflow_in_loop_weight_block_loop_U0_A_15_ce1;
wire   [3:0] dataflow_in_loop_weight_block_loop_U0_A_15_d1;
wire    dataflow_in_loop_weight_block_loop_U0_A_15_we1;
wire    dataflow_in_loop_weight_block_loop_U0_weight_stream_s_read;
wire    dataflow_in_loop_weight_block_loop_U0_ap_start;
wire    dataflow_in_loop_weight_block_loop_U0_ap_done;
wire    dataflow_in_loop_weight_block_loop_U0_ap_ready;
wire    dataflow_in_loop_weight_block_loop_U0_ap_idle;
reg    dataflow_in_loop_weight_block_loop_U0_ap_continue;
reg   [6:0] loop_dataflow_input_count;
reg   [6:0] loop_dataflow_output_count;
wire   [6:0] bound_minus_1;
wire    ap_ce_reg;
// power-on initialization
initial begin
#0 loop_dataflow_input_count = 7'd0;
#0 loop_dataflow_output_count = 7'd0;
end
Linear_Layer_i4xi4_q_dataflow_in_loop_weight_block_loop dataflow_in_loop_weight_block_loop_U0(
    .output_stream_s_din(dataflow_in_loop_weight_block_loop_U0_output_stream_s_din),
    .output_stream_s_full_n(output_stream_s_full_n),
    .output_stream_s_write(dataflow_in_loop_weight_block_loop_U0_output_stream_s_write),
    .A_0_address0(dataflow_in_loop_weight_block_loop_U0_A_0_address0),
    .A_0_ce0(dataflow_in_loop_weight_block_loop_U0_A_0_ce0),
    .A_0_d0(dataflow_in_loop_weight_block_loop_U0_A_0_d0),
    .A_0_q0(A_q0),
    .A_0_we0(dataflow_in_loop_weight_block_loop_U0_A_0_we0),
    .A_0_address1(dataflow_in_loop_weight_block_loop_U0_A_0_address1),
    .A_0_ce1(dataflow_in_loop_weight_block_loop_U0_A_0_ce1),
    .A_0_d1(dataflow_in_loop_weight_block_loop_U0_A_0_d1),
    .A_0_q1(4'd0),
    .A_0_we1(dataflow_in_loop_weight_block_loop_U0_A_0_we1),
    .A_1_address0(dataflow_in_loop_weight_block_loop_U0_A_1_address0),
    .A_1_ce0(dataflow_in_loop_weight_block_loop_U0_A_1_ce0),
    .A_1_d0(dataflow_in_loop_weight_block_loop_U0_A_1_d0),
    .A_1_q0(A_1_q0),
    .A_1_we0(dataflow_in_loop_weight_block_loop_U0_A_1_we0),
    .A_1_address1(dataflow_in_loop_weight_block_loop_U0_A_1_address1),
    .A_1_ce1(dataflow_in_loop_weight_block_loop_U0_A_1_ce1),
    .A_1_d1(dataflow_in_loop_weight_block_loop_U0_A_1_d1),
    .A_1_q1(4'd0),
    .A_1_we1(dataflow_in_loop_weight_block_loop_U0_A_1_we1),
    .A_2_address0(dataflow_in_loop_weight_block_loop_U0_A_2_address0),
    .A_2_ce0(dataflow_in_loop_weight_block_loop_U0_A_2_ce0),
    .A_2_d0(dataflow_in_loop_weight_block_loop_U0_A_2_d0),
    .A_2_q0(A_2_q0),
    .A_2_we0(dataflow_in_loop_weight_block_loop_U0_A_2_we0),
    .A_2_address1(dataflow_in_loop_weight_block_loop_U0_A_2_address1),
    .A_2_ce1(dataflow_in_loop_weight_block_loop_U0_A_2_ce1),
    .A_2_d1(dataflow_in_loop_weight_block_loop_U0_A_2_d1),
    .A_2_q1(4'd0),
    .A_2_we1(dataflow_in_loop_weight_block_loop_U0_A_2_we1),
    .A_3_address0(dataflow_in_loop_weight_block_loop_U0_A_3_address0),
    .A_3_ce0(dataflow_in_loop_weight_block_loop_U0_A_3_ce0),
    .A_3_d0(dataflow_in_loop_weight_block_loop_U0_A_3_d0),
    .A_3_q0(A_3_q0),
    .A_3_we0(dataflow_in_loop_weight_block_loop_U0_A_3_we0),
    .A_3_address1(dataflow_in_loop_weight_block_loop_U0_A_3_address1),
    .A_3_ce1(dataflow_in_loop_weight_block_loop_U0_A_3_ce1),
    .A_3_d1(dataflow_in_loop_weight_block_loop_U0_A_3_d1),
    .A_3_q1(4'd0),
    .A_3_we1(dataflow_in_loop_weight_block_loop_U0_A_3_we1),
    .A_4_address0(dataflow_in_loop_weight_block_loop_U0_A_4_address0),
    .A_4_ce0(dataflow_in_loop_weight_block_loop_U0_A_4_ce0),
    .A_4_d0(dataflow_in_loop_weight_block_loop_U0_A_4_d0),
    .A_4_q0(A_4_q0),
    .A_4_we0(dataflow_in_loop_weight_block_loop_U0_A_4_we0),
    .A_4_address1(dataflow_in_loop_weight_block_loop_U0_A_4_address1),
    .A_4_ce1(dataflow_in_loop_weight_block_loop_U0_A_4_ce1),
    .A_4_d1(dataflow_in_loop_weight_block_loop_U0_A_4_d1),
    .A_4_q1(4'd0),
    .A_4_we1(dataflow_in_loop_weight_block_loop_U0_A_4_we1),
    .A_5_address0(dataflow_in_loop_weight_block_loop_U0_A_5_address0),
    .A_5_ce0(dataflow_in_loop_weight_block_loop_U0_A_5_ce0),
    .A_5_d0(dataflow_in_loop_weight_block_loop_U0_A_5_d0),
    .A_5_q0(A_5_q0),
    .A_5_we0(dataflow_in_loop_weight_block_loop_U0_A_5_we0),
    .A_5_address1(dataflow_in_loop_weight_block_loop_U0_A_5_address1),
    .A_5_ce1(dataflow_in_loop_weight_block_loop_U0_A_5_ce1),
    .A_5_d1(dataflow_in_loop_weight_block_loop_U0_A_5_d1),
    .A_5_q1(4'd0),
    .A_5_we1(dataflow_in_loop_weight_block_loop_U0_A_5_we1),
    .A_6_address0(dataflow_in_loop_weight_block_loop_U0_A_6_address0),
    .A_6_ce0(dataflow_in_loop_weight_block_loop_U0_A_6_ce0),
    .A_6_d0(dataflow_in_loop_weight_block_loop_U0_A_6_d0),
    .A_6_q0(A_6_q0),
    .A_6_we0(dataflow_in_loop_weight_block_loop_U0_A_6_we0),
    .A_6_address1(dataflow_in_loop_weight_block_loop_U0_A_6_address1),
    .A_6_ce1(dataflow_in_loop_weight_block_loop_U0_A_6_ce1),
    .A_6_d1(dataflow_in_loop_weight_block_loop_U0_A_6_d1),
    .A_6_q1(4'd0),
    .A_6_we1(dataflow_in_loop_weight_block_loop_U0_A_6_we1),
    .A_7_address0(dataflow_in_loop_weight_block_loop_U0_A_7_address0),
    .A_7_ce0(dataflow_in_loop_weight_block_loop_U0_A_7_ce0),
    .A_7_d0(dataflow_in_loop_weight_block_loop_U0_A_7_d0),
    .A_7_q0(A_7_q0),
    .A_7_we0(dataflow_in_loop_weight_block_loop_U0_A_7_we0),
    .A_7_address1(dataflow_in_loop_weight_block_loop_U0_A_7_address1),
    .A_7_ce1(dataflow_in_loop_weight_block_loop_U0_A_7_ce1),
    .A_7_d1(dataflow_in_loop_weight_block_loop_U0_A_7_d1),
    .A_7_q1(4'd0),
    .A_7_we1(dataflow_in_loop_weight_block_loop_U0_A_7_we1),
    .A_8_address0(dataflow_in_loop_weight_block_loop_U0_A_8_address0),
    .A_8_ce0(dataflow_in_loop_weight_block_loop_U0_A_8_ce0),
    .A_8_d0(dataflow_in_loop_weight_block_loop_U0_A_8_d0),
    .A_8_q0(A_8_q0),
    .A_8_we0(dataflow_in_loop_weight_block_loop_U0_A_8_we0),
    .A_8_address1(dataflow_in_loop_weight_block_loop_U0_A_8_address1),
    .A_8_ce1(dataflow_in_loop_weight_block_loop_U0_A_8_ce1),
    .A_8_d1(dataflow_in_loop_weight_block_loop_U0_A_8_d1),
    .A_8_q1(4'd0),
    .A_8_we1(dataflow_in_loop_weight_block_loop_U0_A_8_we1),
    .A_9_address0(dataflow_in_loop_weight_block_loop_U0_A_9_address0),
    .A_9_ce0(dataflow_in_loop_weight_block_loop_U0_A_9_ce0),
    .A_9_d0(dataflow_in_loop_weight_block_loop_U0_A_9_d0),
    .A_9_q0(A_9_q0),
    .A_9_we0(dataflow_in_loop_weight_block_loop_U0_A_9_we0),
    .A_9_address1(dataflow_in_loop_weight_block_loop_U0_A_9_address1),
    .A_9_ce1(dataflow_in_loop_weight_block_loop_U0_A_9_ce1),
    .A_9_d1(dataflow_in_loop_weight_block_loop_U0_A_9_d1),
    .A_9_q1(4'd0),
    .A_9_we1(dataflow_in_loop_weight_block_loop_U0_A_9_we1),
    .A_10_address0(dataflow_in_loop_weight_block_loop_U0_A_10_address0),
    .A_10_ce0(dataflow_in_loop_weight_block_loop_U0_A_10_ce0),
    .A_10_d0(dataflow_in_loop_weight_block_loop_U0_A_10_d0),
    .A_10_q0(A_10_q0),
    .A_10_we0(dataflow_in_loop_weight_block_loop_U0_A_10_we0),
    .A_10_address1(dataflow_in_loop_weight_block_loop_U0_A_10_address1),
    .A_10_ce1(dataflow_in_loop_weight_block_loop_U0_A_10_ce1),
    .A_10_d1(dataflow_in_loop_weight_block_loop_U0_A_10_d1),
    .A_10_q1(4'd0),
    .A_10_we1(dataflow_in_loop_weight_block_loop_U0_A_10_we1),
    .A_11_address0(dataflow_in_loop_weight_block_loop_U0_A_11_address0),
    .A_11_ce0(dataflow_in_loop_weight_block_loop_U0_A_11_ce0),
    .A_11_d0(dataflow_in_loop_weight_block_loop_U0_A_11_d0),
    .A_11_q0(A_11_q0),
    .A_11_we0(dataflow_in_loop_weight_block_loop_U0_A_11_we0),
    .A_11_address1(dataflow_in_loop_weight_block_loop_U0_A_11_address1),
    .A_11_ce1(dataflow_in_loop_weight_block_loop_U0_A_11_ce1),
    .A_11_d1(dataflow_in_loop_weight_block_loop_U0_A_11_d1),
    .A_11_q1(4'd0),
    .A_11_we1(dataflow_in_loop_weight_block_loop_U0_A_11_we1),
    .A_12_address0(dataflow_in_loop_weight_block_loop_U0_A_12_address0),
    .A_12_ce0(dataflow_in_loop_weight_block_loop_U0_A_12_ce0),
    .A_12_d0(dataflow_in_loop_weight_block_loop_U0_A_12_d0),
    .A_12_q0(A_12_q0),
    .A_12_we0(dataflow_in_loop_weight_block_loop_U0_A_12_we0),
    .A_12_address1(dataflow_in_loop_weight_block_loop_U0_A_12_address1),
    .A_12_ce1(dataflow_in_loop_weight_block_loop_U0_A_12_ce1),
    .A_12_d1(dataflow_in_loop_weight_block_loop_U0_A_12_d1),
    .A_12_q1(4'd0),
    .A_12_we1(dataflow_in_loop_weight_block_loop_U0_A_12_we1),
    .A_13_address0(dataflow_in_loop_weight_block_loop_U0_A_13_address0),
    .A_13_ce0(dataflow_in_loop_weight_block_loop_U0_A_13_ce0),
    .A_13_d0(dataflow_in_loop_weight_block_loop_U0_A_13_d0),
    .A_13_q0(A_13_q0),
    .A_13_we0(dataflow_in_loop_weight_block_loop_U0_A_13_we0),
    .A_13_address1(dataflow_in_loop_weight_block_loop_U0_A_13_address1),
    .A_13_ce1(dataflow_in_loop_weight_block_loop_U0_A_13_ce1),
    .A_13_d1(dataflow_in_loop_weight_block_loop_U0_A_13_d1),
    .A_13_q1(4'd0),
    .A_13_we1(dataflow_in_loop_weight_block_loop_U0_A_13_we1),
    .A_14_address0(dataflow_in_loop_weight_block_loop_U0_A_14_address0),
    .A_14_ce0(dataflow_in_loop_weight_block_loop_U0_A_14_ce0),
    .A_14_d0(dataflow_in_loop_weight_block_loop_U0_A_14_d0),
    .A_14_q0(A_14_q0),
    .A_14_we0(dataflow_in_loop_weight_block_loop_U0_A_14_we0),
    .A_14_address1(dataflow_in_loop_weight_block_loop_U0_A_14_address1),
    .A_14_ce1(dataflow_in_loop_weight_block_loop_U0_A_14_ce1),
    .A_14_d1(dataflow_in_loop_weight_block_loop_U0_A_14_d1),
    .A_14_q1(4'd0),
    .A_14_we1(dataflow_in_loop_weight_block_loop_U0_A_14_we1),
    .A_15_address0(dataflow_in_loop_weight_block_loop_U0_A_15_address0),
    .A_15_ce0(dataflow_in_loop_weight_block_loop_U0_A_15_ce0),
    .A_15_d0(dataflow_in_loop_weight_block_loop_U0_A_15_d0),
    .A_15_q0(A_15_q0),
    .A_15_we0(dataflow_in_loop_weight_block_loop_U0_A_15_we0),
    .A_15_address1(dataflow_in_loop_weight_block_loop_U0_A_15_address1),
    .A_15_ce1(dataflow_in_loop_weight_block_loop_U0_A_15_ce1),
    .A_15_d1(dataflow_in_loop_weight_block_loop_U0_A_15_d1),
    .A_15_q1(4'd0),
    .A_15_we1(dataflow_in_loop_weight_block_loop_U0_A_15_we1),
    .weight_stream_s_dout(weight_stream_s_dout),
    .weight_stream_s_empty_n(weight_stream_s_empty_n),
    .weight_stream_s_read(dataflow_in_loop_weight_block_loop_U0_weight_stream_s_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_weight_block_loop_U0_ap_start),
    .ap_done(dataflow_in_loop_weight_block_loop_U0_ap_done),
    .ap_ready(dataflow_in_loop_weight_block_loop_U0_ap_ready),
    .ap_idle(dataflow_in_loop_weight_block_loop_U0_ap_idle),
    .ap_continue(dataflow_in_loop_weight_block_loop_U0_ap_continue)
);
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 7'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_weight_block_loop_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 7'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_weight_block_loop_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= 7'd0;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 7'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_weight_block_loop_U0_ap_continue == 1'b1) & (dataflow_in_loop_weight_block_loop_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 7'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_weight_block_loop_U0_ap_continue == 1'b1) & (dataflow_in_loop_weight_block_loop_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 7'd0;
        end
    end
end
always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_weight_block_loop_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end
always @ (*) begin
    if (((loop_dataflow_output_count == 7'd0) & (ap_start == 1'b0) & (dataflow_in_loop_weight_block_loop_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end
always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_weight_block_loop_U0_ap_ready == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end
always @ (*) begin
    if ((~(loop_dataflow_output_count == bound_minus_1) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_weight_block_loop_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_weight_block_loop_U0_ap_continue = 1'b0;
    end
end
assign A_10_address0 = dataflow_in_loop_weight_block_loop_U0_A_10_address0;
assign A_10_address1 = 11'd0;
assign A_10_ce0 = dataflow_in_loop_weight_block_loop_U0_A_10_ce0;
assign A_10_ce1 = 1'b0;
assign A_10_d0 = 4'd0;
assign A_10_d1 = 4'd0;
assign A_10_we0 = 1'b0;
assign A_10_we1 = 1'b0;
assign A_11_address0 = dataflow_in_loop_weight_block_loop_U0_A_11_address0;
assign A_11_address1 = 11'd0;
assign A_11_ce0 = dataflow_in_loop_weight_block_loop_U0_A_11_ce0;
assign A_11_ce1 = 1'b0;
assign A_11_d0 = 4'd0;
assign A_11_d1 = 4'd0;
assign A_11_we0 = 1'b0;
assign A_11_we1 = 1'b0;
assign A_12_address0 = dataflow_in_loop_weight_block_loop_U0_A_12_address0;
assign A_12_address1 = 11'd0;
assign A_12_ce0 = dataflow_in_loop_weight_block_loop_U0_A_12_ce0;
assign A_12_ce1 = 1'b0;
assign A_12_d0 = 4'd0;
assign A_12_d1 = 4'd0;
assign A_12_we0 = 1'b0;
assign A_12_we1 = 1'b0;
assign A_13_address0 = dataflow_in_loop_weight_block_loop_U0_A_13_address0;
assign A_13_address1 = 11'd0;
assign A_13_ce0 = dataflow_in_loop_weight_block_loop_U0_A_13_ce0;
assign A_13_ce1 = 1'b0;
assign A_13_d0 = 4'd0;
assign A_13_d1 = 4'd0;
assign A_13_we0 = 1'b0;
assign A_13_we1 = 1'b0;
assign A_14_address0 = dataflow_in_loop_weight_block_loop_U0_A_14_address0;
assign A_14_address1 = 11'd0;
assign A_14_ce0 = dataflow_in_loop_weight_block_loop_U0_A_14_ce0;
assign A_14_ce1 = 1'b0;
assign A_14_d0 = 4'd0;
assign A_14_d1 = 4'd0;
assign A_14_we0 = 1'b0;
assign A_14_we1 = 1'b0;
assign A_15_address0 = dataflow_in_loop_weight_block_loop_U0_A_15_address0;
assign A_15_address1 = 11'd0;
assign A_15_ce0 = dataflow_in_loop_weight_block_loop_U0_A_15_ce0;
assign A_15_ce1 = 1'b0;
assign A_15_d0 = 4'd0;
assign A_15_d1 = 4'd0;
assign A_15_we0 = 1'b0;
assign A_15_we1 = 1'b0;
assign A_1_address0 = dataflow_in_loop_weight_block_loop_U0_A_1_address0;
assign A_1_address1 = 11'd0;
assign A_1_ce0 = dataflow_in_loop_weight_block_loop_U0_A_1_ce0;
assign A_1_ce1 = 1'b0;
assign A_1_d0 = 4'd0;
assign A_1_d1 = 4'd0;
assign A_1_we0 = 1'b0;
assign A_1_we1 = 1'b0;
assign A_2_address0 = dataflow_in_loop_weight_block_loop_U0_A_2_address0;
assign A_2_address1 = 11'd0;
assign A_2_ce0 = dataflow_in_loop_weight_block_loop_U0_A_2_ce0;
assign A_2_ce1 = 1'b0;
assign A_2_d0 = 4'd0;
assign A_2_d1 = 4'd0;
assign A_2_we0 = 1'b0;
assign A_2_we1 = 1'b0;
assign A_3_address0 = dataflow_in_loop_weight_block_loop_U0_A_3_address0;
assign A_3_address1 = 11'd0;
assign A_3_ce0 = dataflow_in_loop_weight_block_loop_U0_A_3_ce0;
assign A_3_ce1 = 1'b0;
assign A_3_d0 = 4'd0;
assign A_3_d1 = 4'd0;
assign A_3_we0 = 1'b0;
assign A_3_we1 = 1'b0;
assign A_4_address0 = dataflow_in_loop_weight_block_loop_U0_A_4_address0;
assign A_4_address1 = 11'd0;
assign A_4_ce0 = dataflow_in_loop_weight_block_loop_U0_A_4_ce0;
assign A_4_ce1 = 1'b0;
assign A_4_d0 = 4'd0;
assign A_4_d1 = 4'd0;
assign A_4_we0 = 1'b0;
assign A_4_we1 = 1'b0;
assign A_5_address0 = dataflow_in_loop_weight_block_loop_U0_A_5_address0;
assign A_5_address1 = 11'd0;
assign A_5_ce0 = dataflow_in_loop_weight_block_loop_U0_A_5_ce0;
assign A_5_ce1 = 1'b0;
assign A_5_d0 = 4'd0;
assign A_5_d1 = 4'd0;
assign A_5_we0 = 1'b0;
assign A_5_we1 = 1'b0;
assign A_6_address0 = dataflow_in_loop_weight_block_loop_U0_A_6_address0;
assign A_6_address1 = 11'd0;
assign A_6_ce0 = dataflow_in_loop_weight_block_loop_U0_A_6_ce0;
assign A_6_ce1 = 1'b0;
assign A_6_d0 = 4'd0;
assign A_6_d1 = 4'd0;
assign A_6_we0 = 1'b0;
assign A_6_we1 = 1'b0;
assign A_7_address0 = dataflow_in_loop_weight_block_loop_U0_A_7_address0;
assign A_7_address1 = 11'd0;
assign A_7_ce0 = dataflow_in_loop_weight_block_loop_U0_A_7_ce0;
assign A_7_ce1 = 1'b0;
assign A_7_d0 = 4'd0;
assign A_7_d1 = 4'd0;
assign A_7_we0 = 1'b0;
assign A_7_we1 = 1'b0;
assign A_8_address0 = dataflow_in_loop_weight_block_loop_U0_A_8_address0;
assign A_8_address1 = 11'd0;
assign A_8_ce0 = dataflow_in_loop_weight_block_loop_U0_A_8_ce0;
assign A_8_ce1 = 1'b0;
assign A_8_d0 = 4'd0;
assign A_8_d1 = 4'd0;
assign A_8_we0 = 1'b0;
assign A_8_we1 = 1'b0;
assign A_9_address0 = dataflow_in_loop_weight_block_loop_U0_A_9_address0;
assign A_9_address1 = 11'd0;
assign A_9_ce0 = dataflow_in_loop_weight_block_loop_U0_A_9_ce0;
assign A_9_ce1 = 1'b0;
assign A_9_d0 = 4'd0;
assign A_9_d1 = 4'd0;
assign A_9_we0 = 1'b0;
assign A_9_we1 = 1'b0;
assign A_address0 = dataflow_in_loop_weight_block_loop_U0_A_0_address0;
assign A_address1 = 11'd0;
assign A_ce0 = dataflow_in_loop_weight_block_loop_U0_A_0_ce0;
assign A_ce1 = 1'b0;
assign A_d0 = 4'd0;
assign A_d1 = 4'd0;
assign A_we0 = 1'b0;
assign A_we1 = 1'b0;
assign bound_minus_1 = (7'd64 - 7'd1);
assign dataflow_in_loop_weight_block_loop_U0_ap_start = ap_start;
assign output_stream_s_din = dataflow_in_loop_weight_block_loop_U0_output_stream_s_din;
assign output_stream_s_write = dataflow_in_loop_weight_block_loop_U0_output_stream_s_write;
assign weight_stream_s_read = dataflow_in_loop_weight_block_loop_U0_weight_stream_s_read;
endmodule