`timescale 1 ns / 1 ps
// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
 
module Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_stream_s_dout,
        input_stream_s_empty_n,
        input_stream_s_read,
        weight_stream_s_dout,
        weight_stream_s_empty_n,
        weight_stream_s_read,
        output_stream_s_din,
        output_stream_s_full_n,
        output_stream_s_write,
        seq_len
);
parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [64:0] input_stream_s_dout;
input   input_stream_s_empty_n;
output   input_stream_s_read;
input  [128:0] weight_stream_s_dout;
input   weight_stream_s_empty_n;
output   weight_stream_s_read;
output  [304:0] output_stream_s_din;
input   output_stream_s_full_n;
output   output_stream_s_write;
input  [31:0] seq_len;
reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_stream_s_read;
reg weight_stream_s_read;
reg output_stream_s_write;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] tmp_129_reg_292;
reg   [27:0] tmp_reg_297;
reg   [27:0] tmp_1_reg_302;
wire   [28:0] div_fu_242_p3;
reg   [28:0] div_reg_307;
wire    ap_CS_fsm_state2;
reg    A_ce0;
wire   [3:0] A_q0;
reg    A_ce1;
reg    A_we1;
reg    A_1_ce0;
wire   [3:0] A_1_q0;
reg    A_1_ce1;
reg    A_1_we1;
reg    A_2_ce0;
wire   [3:0] A_2_q0;
reg    A_2_ce1;
reg    A_2_we1;
reg    A_3_ce0;
wire   [3:0] A_3_q0;
reg    A_3_ce1;
reg    A_3_we1;
reg    A_4_ce0;
wire   [3:0] A_4_q0;
reg    A_4_ce1;
reg    A_4_we1;
reg    A_5_ce0;
wire   [3:0] A_5_q0;
reg    A_5_ce1;
reg    A_5_we1;
reg    A_6_ce0;
wire   [3:0] A_6_q0;
reg    A_6_ce1;
reg    A_6_we1;
reg    A_7_ce0;
wire   [3:0] A_7_q0;
reg    A_7_ce1;
reg    A_7_we1;
reg    A_8_ce0;
wire   [3:0] A_8_q0;
reg    A_8_ce1;
reg    A_8_we1;
reg    A_9_ce0;
wire   [3:0] A_9_q0;
reg    A_9_ce1;
reg    A_9_we1;
reg    A_10_ce0;
wire   [3:0] A_10_q0;
reg    A_10_ce1;
reg    A_10_we1;
reg    A_11_ce0;
wire   [3:0] A_11_q0;
reg    A_11_ce1;
reg    A_11_we1;
reg    A_12_ce0;
wire   [3:0] A_12_q0;
reg    A_12_ce1;
reg    A_12_we1;
reg    A_13_ce0;
wire   [3:0] A_13_q0;
reg    A_13_ce1;
reg    A_13_we1;
reg    A_14_ce0;
wire   [3:0] A_14_q0;
reg    A_14_ce1;
reg    A_14_we1;
reg    A_15_ce0;
wire   [3:0] A_15_q0;
reg    A_15_ce1;
reg    A_15_we1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_done;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_idle;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_ready;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_input_stream_s_read;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_d1;
wire   [10:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_address1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_ce1;
wire    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_we1;
wire   [3:0] grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_d1;
wire   [304:0] grp_dataflow_parent_loop_proc_fu_158_output_stream_s_din;
wire    grp_dataflow_parent_loop_proc_fu_158_output_stream_s_write;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_1_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_1_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_1_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_1_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_1_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_1_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_1_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_1_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_2_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_2_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_2_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_2_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_2_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_2_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_2_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_2_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_3_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_3_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_3_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_3_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_3_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_3_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_3_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_3_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_4_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_4_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_4_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_4_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_4_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_4_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_4_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_4_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_5_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_5_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_5_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_5_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_5_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_5_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_5_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_5_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_6_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_6_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_6_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_6_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_6_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_6_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_6_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_6_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_7_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_7_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_7_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_7_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_7_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_7_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_7_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_7_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_8_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_8_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_8_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_8_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_8_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_8_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_8_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_8_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_9_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_9_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_9_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_9_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_9_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_9_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_9_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_9_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_10_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_10_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_10_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_10_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_10_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_10_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_10_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_10_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_11_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_11_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_11_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_11_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_11_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_11_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_11_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_11_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_12_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_12_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_12_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_12_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_12_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_12_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_12_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_12_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_13_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_13_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_13_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_13_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_13_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_13_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_13_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_13_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_14_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_14_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_14_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_14_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_14_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_14_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_14_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_14_we1;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_15_address0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_15_ce0;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_15_d0;
wire    grp_dataflow_parent_loop_proc_fu_158_A_15_we0;
wire   [10:0] grp_dataflow_parent_loop_proc_fu_158_A_15_address1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_15_ce1;
wire   [3:0] grp_dataflow_parent_loop_proc_fu_158_A_15_d1;
wire    grp_dataflow_parent_loop_proc_fu_158_A_15_we1;
wire    grp_dataflow_parent_loop_proc_fu_158_weight_stream_s_read;
wire    grp_dataflow_parent_loop_proc_fu_158_ap_start;
wire    grp_dataflow_parent_loop_proc_fu_158_ap_done;
wire    grp_dataflow_parent_loop_proc_fu_158_ap_ready;
wire    grp_dataflow_parent_loop_proc_fu_158_ap_idle;
reg    grp_dataflow_parent_loop_proc_fu_158_ap_continue;
reg    grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln2598_fu_265_p2;
wire    ap_CS_fsm_state4;
reg    grp_dataflow_parent_loop_proc_fu_158_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_ready;
reg    ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_done;
reg    ap_block_state6_on_subcall_done;
wire    ap_sync_grp_dataflow_parent_loop_proc_fu_158_ap_ready;
reg   [27:0] M_fu_62;
wire   [27:0] add_ln2598_fu_255_p2;
wire   [31:0] p_neg_fu_192_p2;
wire   [28:0] p_lshr_cast_fu_230_p1;
wire   [28:0] p_neg_t_fu_233_p2;
wire   [28:0] p_lshr_f_cast_fu_239_p1;
wire   [28:0] zext_ln2598_fu_261_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;
// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start_reg = 1'b0;
#0 grp_dataflow_parent_loop_proc_fu_158_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_ready = 1'b0;
#0 ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_done = 1'b0;
#0 M_fu_62 = 28'd0;
end
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_address0),
    .ce0(A_ce0),
    .q0(A_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_address1),
    .ce1(A_ce1),
    .we1(A_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_1_address0),
    .ce0(A_1_ce0),
    .q0(A_1_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_address1),
    .ce1(A_1_ce1),
    .we1(A_1_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_2_address0),
    .ce0(A_2_ce0),
    .q0(A_2_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_address1),
    .ce1(A_2_ce1),
    .we1(A_2_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_3_address0),
    .ce0(A_3_ce0),
    .q0(A_3_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_address1),
    .ce1(A_3_ce1),
    .we1(A_3_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_4_address0),
    .ce0(A_4_ce0),
    .q0(A_4_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_address1),
    .ce1(A_4_ce1),
    .we1(A_4_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_5_address0),
    .ce0(A_5_ce0),
    .q0(A_5_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_address1),
    .ce1(A_5_ce1),
    .we1(A_5_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_6_address0),
    .ce0(A_6_ce0),
    .q0(A_6_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_address1),
    .ce1(A_6_ce1),
    .we1(A_6_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_7_address0),
    .ce0(A_7_ce0),
    .q0(A_7_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_address1),
    .ce1(A_7_ce1),
    .we1(A_7_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_8_address0),
    .ce0(A_8_ce0),
    .q0(A_8_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_address1),
    .ce1(A_8_ce1),
    .we1(A_8_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_9_address0),
    .ce0(A_9_ce0),
    .q0(A_9_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_address1),
    .ce1(A_9_ce1),
    .we1(A_9_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_10_address0),
    .ce0(A_10_ce0),
    .q0(A_10_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_address1),
    .ce1(A_10_ce1),
    .we1(A_10_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_11_address0),
    .ce0(A_11_ce0),
    .q0(A_11_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_address1),
    .ce1(A_11_ce1),
    .we1(A_11_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_12_address0),
    .ce0(A_12_ce0),
    .q0(A_12_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_address1),
    .ce1(A_12_ce1),
    .we1(A_12_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_13_address0),
    .ce0(A_13_ce0),
    .q0(A_13_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_address1),
    .ce1(A_13_ce1),
    .we1(A_13_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_14_address0),
    .ce0(A_14_ce0),
    .q0(A_14_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_address1),
    .ce1(A_14_ce1),
    .we1(A_14_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
A_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_dataflow_parent_loop_proc_fu_158_A_15_address0),
    .ce0(A_15_ce0),
    .q0(A_15_q0),
    .address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_address1),
    .ce1(A_15_ce1),
    .we1(A_15_we1),
    .d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_d1)
);
Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start),
    .ap_done(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_done),
    .ap_idle(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_idle),
    .ap_ready(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_ready),
    .input_stream_s_dout(input_stream_s_dout),
    .input_stream_s_empty_n(input_stream_s_empty_n),
    .input_stream_s_read(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_input_stream_s_read),
    .A_15_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_address1),
    .A_15_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_ce1),
    .A_15_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_we1),
    .A_15_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_d1),
    .A_14_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_address1),
    .A_14_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_ce1),
    .A_14_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_we1),
    .A_14_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_d1),
    .A_13_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_address1),
    .A_13_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_ce1),
    .A_13_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_we1),
    .A_13_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_d1),
    .A_12_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_address1),
    .A_12_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_ce1),
    .A_12_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_we1),
    .A_12_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_d1),
    .A_11_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_address1),
    .A_11_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_ce1),
    .A_11_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_we1),
    .A_11_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_d1),
    .A_10_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_address1),
    .A_10_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_ce1),
    .A_10_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_we1),
    .A_10_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_d1),
    .A_9_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_address1),
    .A_9_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_ce1),
    .A_9_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_we1),
    .A_9_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_d1),
    .A_8_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_address1),
    .A_8_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_ce1),
    .A_8_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_we1),
    .A_8_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_d1),
    .A_7_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_address1),
    .A_7_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_ce1),
    .A_7_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_we1),
    .A_7_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_d1),
    .A_6_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_address1),
    .A_6_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_ce1),
    .A_6_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_we1),
    .A_6_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_d1),
    .A_5_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_address1),
    .A_5_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_ce1),
    .A_5_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_we1),
    .A_5_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_d1),
    .A_4_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_address1),
    .A_4_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_ce1),
    .A_4_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_we1),
    .A_4_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_d1),
    .A_3_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_address1),
    .A_3_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_ce1),
    .A_3_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_we1),
    .A_3_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_d1),
    .A_2_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_address1),
    .A_2_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_ce1),
    .A_2_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_we1),
    .A_2_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_d1),
    .A_1_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_address1),
    .A_1_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_ce1),
    .A_1_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_we1),
    .A_1_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_d1),
    .A_address1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_address1),
    .A_ce1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_ce1),
    .A_we1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_we1),
    .A_d1(grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_d1)
);
Linear_Layer_i4xi4_q_dataflow_parent_loop_proc grp_dataflow_parent_loop_proc_fu_158(
    .output_stream_s_din(grp_dataflow_parent_loop_proc_fu_158_output_stream_s_din),
    .output_stream_s_full_n(output_stream_s_full_n),
    .output_stream_s_write(grp_dataflow_parent_loop_proc_fu_158_output_stream_s_write),
    .A_address0(grp_dataflow_parent_loop_proc_fu_158_A_address0),
    .A_ce0(grp_dataflow_parent_loop_proc_fu_158_A_ce0),
    .A_d0(grp_dataflow_parent_loop_proc_fu_158_A_d0),
    .A_q0(A_q0),
    .A_we0(grp_dataflow_parent_loop_proc_fu_158_A_we0),
    .A_address1(grp_dataflow_parent_loop_proc_fu_158_A_address1),
    .A_ce1(grp_dataflow_parent_loop_proc_fu_158_A_ce1),
    .A_d1(grp_dataflow_parent_loop_proc_fu_158_A_d1),
    .A_q1(4'd0),
    .A_we1(grp_dataflow_parent_loop_proc_fu_158_A_we1),
    .A_1_address0(grp_dataflow_parent_loop_proc_fu_158_A_1_address0),
    .A_1_ce0(grp_dataflow_parent_loop_proc_fu_158_A_1_ce0),
    .A_1_d0(grp_dataflow_parent_loop_proc_fu_158_A_1_d0),
    .A_1_q0(A_1_q0),
    .A_1_we0(grp_dataflow_parent_loop_proc_fu_158_A_1_we0),
    .A_1_address1(grp_dataflow_parent_loop_proc_fu_158_A_1_address1),
    .A_1_ce1(grp_dataflow_parent_loop_proc_fu_158_A_1_ce1),
    .A_1_d1(grp_dataflow_parent_loop_proc_fu_158_A_1_d1),
    .A_1_q1(4'd0),
    .A_1_we1(grp_dataflow_parent_loop_proc_fu_158_A_1_we1),
    .A_2_address0(grp_dataflow_parent_loop_proc_fu_158_A_2_address0),
    .A_2_ce0(grp_dataflow_parent_loop_proc_fu_158_A_2_ce0),
    .A_2_d0(grp_dataflow_parent_loop_proc_fu_158_A_2_d0),
    .A_2_q0(A_2_q0),
    .A_2_we0(grp_dataflow_parent_loop_proc_fu_158_A_2_we0),
    .A_2_address1(grp_dataflow_parent_loop_proc_fu_158_A_2_address1),
    .A_2_ce1(grp_dataflow_parent_loop_proc_fu_158_A_2_ce1),
    .A_2_d1(grp_dataflow_parent_loop_proc_fu_158_A_2_d1),
    .A_2_q1(4'd0),
    .A_2_we1(grp_dataflow_parent_loop_proc_fu_158_A_2_we1),
    .A_3_address0(grp_dataflow_parent_loop_proc_fu_158_A_3_address0),
    .A_3_ce0(grp_dataflow_parent_loop_proc_fu_158_A_3_ce0),
    .A_3_d0(grp_dataflow_parent_loop_proc_fu_158_A_3_d0),
    .A_3_q0(A_3_q0),
    .A_3_we0(grp_dataflow_parent_loop_proc_fu_158_A_3_we0),
    .A_3_address1(grp_dataflow_parent_loop_proc_fu_158_A_3_address1),
    .A_3_ce1(grp_dataflow_parent_loop_proc_fu_158_A_3_ce1),
    .A_3_d1(grp_dataflow_parent_loop_proc_fu_158_A_3_d1),
    .A_3_q1(4'd0),
    .A_3_we1(grp_dataflow_parent_loop_proc_fu_158_A_3_we1),
    .A_4_address0(grp_dataflow_parent_loop_proc_fu_158_A_4_address0),
    .A_4_ce0(grp_dataflow_parent_loop_proc_fu_158_A_4_ce0),
    .A_4_d0(grp_dataflow_parent_loop_proc_fu_158_A_4_d0),
    .A_4_q0(A_4_q0),
    .A_4_we0(grp_dataflow_parent_loop_proc_fu_158_A_4_we0),
    .A_4_address1(grp_dataflow_parent_loop_proc_fu_158_A_4_address1),
    .A_4_ce1(grp_dataflow_parent_loop_proc_fu_158_A_4_ce1),
    .A_4_d1(grp_dataflow_parent_loop_proc_fu_158_A_4_d1),
    .A_4_q1(4'd0),
    .A_4_we1(grp_dataflow_parent_loop_proc_fu_158_A_4_we1),
    .A_5_address0(grp_dataflow_parent_loop_proc_fu_158_A_5_address0),
    .A_5_ce0(grp_dataflow_parent_loop_proc_fu_158_A_5_ce0),
    .A_5_d0(grp_dataflow_parent_loop_proc_fu_158_A_5_d0),
    .A_5_q0(A_5_q0),
    .A_5_we0(grp_dataflow_parent_loop_proc_fu_158_A_5_we0),
    .A_5_address1(grp_dataflow_parent_loop_proc_fu_158_A_5_address1),
    .A_5_ce1(grp_dataflow_parent_loop_proc_fu_158_A_5_ce1),
    .A_5_d1(grp_dataflow_parent_loop_proc_fu_158_A_5_d1),
    .A_5_q1(4'd0),
    .A_5_we1(grp_dataflow_parent_loop_proc_fu_158_A_5_we1),
    .A_6_address0(grp_dataflow_parent_loop_proc_fu_158_A_6_address0),
    .A_6_ce0(grp_dataflow_parent_loop_proc_fu_158_A_6_ce0),
    .A_6_d0(grp_dataflow_parent_loop_proc_fu_158_A_6_d0),
    .A_6_q0(A_6_q0),
    .A_6_we0(grp_dataflow_parent_loop_proc_fu_158_A_6_we0),
    .A_6_address1(grp_dataflow_parent_loop_proc_fu_158_A_6_address1),
    .A_6_ce1(grp_dataflow_parent_loop_proc_fu_158_A_6_ce1),
    .A_6_d1(grp_dataflow_parent_loop_proc_fu_158_A_6_d1),
    .A_6_q1(4'd0),
    .A_6_we1(grp_dataflow_parent_loop_proc_fu_158_A_6_we1),
    .A_7_address0(grp_dataflow_parent_loop_proc_fu_158_A_7_address0),
    .A_7_ce0(grp_dataflow_parent_loop_proc_fu_158_A_7_ce0),
    .A_7_d0(grp_dataflow_parent_loop_proc_fu_158_A_7_d0),
    .A_7_q0(A_7_q0),
    .A_7_we0(grp_dataflow_parent_loop_proc_fu_158_A_7_we0),
    .A_7_address1(grp_dataflow_parent_loop_proc_fu_158_A_7_address1),
    .A_7_ce1(grp_dataflow_parent_loop_proc_fu_158_A_7_ce1),
    .A_7_d1(grp_dataflow_parent_loop_proc_fu_158_A_7_d1),
    .A_7_q1(4'd0),
    .A_7_we1(grp_dataflow_parent_loop_proc_fu_158_A_7_we1),
    .A_8_address0(grp_dataflow_parent_loop_proc_fu_158_A_8_address0),
    .A_8_ce0(grp_dataflow_parent_loop_proc_fu_158_A_8_ce0),
    .A_8_d0(grp_dataflow_parent_loop_proc_fu_158_A_8_d0),
    .A_8_q0(A_8_q0),
    .A_8_we0(grp_dataflow_parent_loop_proc_fu_158_A_8_we0),
    .A_8_address1(grp_dataflow_parent_loop_proc_fu_158_A_8_address1),
    .A_8_ce1(grp_dataflow_parent_loop_proc_fu_158_A_8_ce1),
    .A_8_d1(grp_dataflow_parent_loop_proc_fu_158_A_8_d1),
    .A_8_q1(4'd0),
    .A_8_we1(grp_dataflow_parent_loop_proc_fu_158_A_8_we1),
    .A_9_address0(grp_dataflow_parent_loop_proc_fu_158_A_9_address0),
    .A_9_ce0(grp_dataflow_parent_loop_proc_fu_158_A_9_ce0),
    .A_9_d0(grp_dataflow_parent_loop_proc_fu_158_A_9_d0),
    .A_9_q0(A_9_q0),
    .A_9_we0(grp_dataflow_parent_loop_proc_fu_158_A_9_we0),
    .A_9_address1(grp_dataflow_parent_loop_proc_fu_158_A_9_address1),
    .A_9_ce1(grp_dataflow_parent_loop_proc_fu_158_A_9_ce1),
    .A_9_d1(grp_dataflow_parent_loop_proc_fu_158_A_9_d1),
    .A_9_q1(4'd0),
    .A_9_we1(grp_dataflow_parent_loop_proc_fu_158_A_9_we1),
    .A_10_address0(grp_dataflow_parent_loop_proc_fu_158_A_10_address0),
    .A_10_ce0(grp_dataflow_parent_loop_proc_fu_158_A_10_ce0),
    .A_10_d0(grp_dataflow_parent_loop_proc_fu_158_A_10_d0),
    .A_10_q0(A_10_q0),
    .A_10_we0(grp_dataflow_parent_loop_proc_fu_158_A_10_we0),
    .A_10_address1(grp_dataflow_parent_loop_proc_fu_158_A_10_address1),
    .A_10_ce1(grp_dataflow_parent_loop_proc_fu_158_A_10_ce1),
    .A_10_d1(grp_dataflow_parent_loop_proc_fu_158_A_10_d1),
    .A_10_q1(4'd0),
    .A_10_we1(grp_dataflow_parent_loop_proc_fu_158_A_10_we1),
    .A_11_address0(grp_dataflow_parent_loop_proc_fu_158_A_11_address0),
    .A_11_ce0(grp_dataflow_parent_loop_proc_fu_158_A_11_ce0),
    .A_11_d0(grp_dataflow_parent_loop_proc_fu_158_A_11_d0),
    .A_11_q0(A_11_q0),
    .A_11_we0(grp_dataflow_parent_loop_proc_fu_158_A_11_we0),
    .A_11_address1(grp_dataflow_parent_loop_proc_fu_158_A_11_address1),
    .A_11_ce1(grp_dataflow_parent_loop_proc_fu_158_A_11_ce1),
    .A_11_d1(grp_dataflow_parent_loop_proc_fu_158_A_11_d1),
    .A_11_q1(4'd0),
    .A_11_we1(grp_dataflow_parent_loop_proc_fu_158_A_11_we1),
    .A_12_address0(grp_dataflow_parent_loop_proc_fu_158_A_12_address0),
    .A_12_ce0(grp_dataflow_parent_loop_proc_fu_158_A_12_ce0),
    .A_12_d0(grp_dataflow_parent_loop_proc_fu_158_A_12_d0),
    .A_12_q0(A_12_q0),
    .A_12_we0(grp_dataflow_parent_loop_proc_fu_158_A_12_we0),
    .A_12_address1(grp_dataflow_parent_loop_proc_fu_158_A_12_address1),
    .A_12_ce1(grp_dataflow_parent_loop_proc_fu_158_A_12_ce1),
    .A_12_d1(grp_dataflow_parent_loop_proc_fu_158_A_12_d1),
    .A_12_q1(4'd0),
    .A_12_we1(grp_dataflow_parent_loop_proc_fu_158_A_12_we1),
    .A_13_address0(grp_dataflow_parent_loop_proc_fu_158_A_13_address0),
    .A_13_ce0(grp_dataflow_parent_loop_proc_fu_158_A_13_ce0),
    .A_13_d0(grp_dataflow_parent_loop_proc_fu_158_A_13_d0),
    .A_13_q0(A_13_q0),
    .A_13_we0(grp_dataflow_parent_loop_proc_fu_158_A_13_we0),
    .A_13_address1(grp_dataflow_parent_loop_proc_fu_158_A_13_address1),
    .A_13_ce1(grp_dataflow_parent_loop_proc_fu_158_A_13_ce1),
    .A_13_d1(grp_dataflow_parent_loop_proc_fu_158_A_13_d1),
    .A_13_q1(4'd0),
    .A_13_we1(grp_dataflow_parent_loop_proc_fu_158_A_13_we1),
    .A_14_address0(grp_dataflow_parent_loop_proc_fu_158_A_14_address0),
    .A_14_ce0(grp_dataflow_parent_loop_proc_fu_158_A_14_ce0),
    .A_14_d0(grp_dataflow_parent_loop_proc_fu_158_A_14_d0),
    .A_14_q0(A_14_q0),
    .A_14_we0(grp_dataflow_parent_loop_proc_fu_158_A_14_we0),
    .A_14_address1(grp_dataflow_parent_loop_proc_fu_158_A_14_address1),
    .A_14_ce1(grp_dataflow_parent_loop_proc_fu_158_A_14_ce1),
    .A_14_d1(grp_dataflow_parent_loop_proc_fu_158_A_14_d1),
    .A_14_q1(4'd0),
    .A_14_we1(grp_dataflow_parent_loop_proc_fu_158_A_14_we1),
    .A_15_address0(grp_dataflow_parent_loop_proc_fu_158_A_15_address0),
    .A_15_ce0(grp_dataflow_parent_loop_proc_fu_158_A_15_ce0),
    .A_15_d0(grp_dataflow_parent_loop_proc_fu_158_A_15_d0),
    .A_15_q0(A_15_q0),
    .A_15_we0(grp_dataflow_parent_loop_proc_fu_158_A_15_we0),
    .A_15_address1(grp_dataflow_parent_loop_proc_fu_158_A_15_address1),
    .A_15_ce1(grp_dataflow_parent_loop_proc_fu_158_A_15_ce1),
    .A_15_d1(grp_dataflow_parent_loop_proc_fu_158_A_15_d1),
    .A_15_q1(4'd0),
    .A_15_we1(grp_dataflow_parent_loop_proc_fu_158_A_15_we1),
    .weight_stream_s_dout(weight_stream_s_dout),
    .weight_stream_s_empty_n(weight_stream_s_empty_n),
    .weight_stream_s_read(grp_dataflow_parent_loop_proc_fu_158_weight_stream_s_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dataflow_parent_loop_proc_fu_158_ap_start),
    .ap_done(grp_dataflow_parent_loop_proc_fu_158_ap_done),
    .ap_ready(grp_dataflow_parent_loop_proc_fu_158_ap_ready),
    .ap_idle(grp_dataflow_parent_loop_proc_fu_158_ap_idle),
    .ap_continue(grp_dataflow_parent_loop_proc_fu_158_ap_continue)
);
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_done <= 1'b0;
        end else if ((grp_dataflow_parent_loop_proc_fu_158_ap_done == 1'b1)) begin
            ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_done <= 1'b1;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_ready <= 1'b0;
        end else if ((grp_dataflow_parent_loop_proc_fu_158_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_ready <= 1'b1;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln2598_fu_265_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start_reg <= 1'b1;
        end else if ((grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_ready == 1'b1)) begin
            grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start_reg <= 1'b0;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dataflow_parent_loop_proc_fu_158_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) | ((ap_sync_grp_dataflow_parent_loop_proc_fu_158_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state6)))) begin
            grp_dataflow_parent_loop_proc_fu_158_ap_start_reg <= 1'b1;
        end else if ((grp_dataflow_parent_loop_proc_fu_158_ap_ready == 1'b1)) begin
            grp_dataflow_parent_loop_proc_fu_158_ap_start_reg <= 1'b0;
        end
    end
end
always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        M_fu_62 <= 28'd0;
    end else if (((icmp_ln2598_fu_265_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        M_fu_62 <= add_ln2598_fu_255_p2;
    end
end
always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        div_reg_307 <= div_fu_242_p3;
    end
end
always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_129_reg_292 <= seq_len[32'd31];
        tmp_1_reg_302 <= {{seq_len[31:4]}};
        tmp_reg_297 <= {{p_neg_fu_192_p2[31:4]}};
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_10_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_10_ce0;
    end else begin
        A_10_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_10_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_ce1;
    end else begin
        A_10_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_10_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_10_we1;
    end else begin
        A_10_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_11_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_11_ce0;
    end else begin
        A_11_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_11_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_ce1;
    end else begin
        A_11_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_11_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_11_we1;
    end else begin
        A_11_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_12_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_12_ce0;
    end else begin
        A_12_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_12_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_ce1;
    end else begin
        A_12_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_12_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_12_we1;
    end else begin
        A_12_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_13_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_13_ce0;
    end else begin
        A_13_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_13_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_ce1;
    end else begin
        A_13_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_13_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_13_we1;
    end else begin
        A_13_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_14_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_14_ce0;
    end else begin
        A_14_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_14_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_ce1;
    end else begin
        A_14_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_14_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_14_we1;
    end else begin
        A_14_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_15_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_15_ce0;
    end else begin
        A_15_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_15_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_ce1;
    end else begin
        A_15_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_15_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_15_we1;
    end else begin
        A_15_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_1_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_1_ce0;
    end else begin
        A_1_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_ce1;
    end else begin
        A_1_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_1_we1;
    end else begin
        A_1_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_2_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_2_ce0;
    end else begin
        A_2_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_ce1;
    end else begin
        A_2_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_2_we1;
    end else begin
        A_2_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_3_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_3_ce0;
    end else begin
        A_3_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_ce1;
    end else begin
        A_3_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_3_we1;
    end else begin
        A_3_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_4_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_4_ce0;
    end else begin
        A_4_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_4_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_ce1;
    end else begin
        A_4_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_4_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_4_we1;
    end else begin
        A_4_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_5_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_5_ce0;
    end else begin
        A_5_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_5_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_ce1;
    end else begin
        A_5_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_5_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_5_we1;
    end else begin
        A_5_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_6_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_6_ce0;
    end else begin
        A_6_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_6_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_ce1;
    end else begin
        A_6_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_6_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_6_we1;
    end else begin
        A_6_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_7_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_7_ce0;
    end else begin
        A_7_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_7_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_ce1;
    end else begin
        A_7_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_7_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_7_we1;
    end else begin
        A_7_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_8_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_8_ce0;
    end else begin
        A_8_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_8_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_ce1;
    end else begin
        A_8_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_8_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_8_we1;
    end else begin
        A_8_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_9_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_9_ce0;
    end else begin
        A_9_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_9_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_ce1;
    end else begin
        A_9_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_9_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_9_we1;
    end else begin
        A_9_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_ce0 = grp_dataflow_parent_loop_proc_fu_158_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_ce1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_ce1;
    end else begin
        A_ce1 = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_we1 = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_A_we1;
    end else begin
        A_we1 = 1'b0;
    end
end
always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end
assign ap_ST_fsm_state2_blk = 1'b0;
assign ap_ST_fsm_state3_blk = 1'b0;
always @ (*) begin
    if ((grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end
assign ap_ST_fsm_state5_blk = 1'b0;
always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end
always @ (*) begin
    if ((((icmp_ln2598_fu_265_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end
always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end
always @ (*) begin
    if (((icmp_ln2598_fu_265_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end
always @ (*) begin
    if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
        grp_dataflow_parent_loop_proc_fu_158_ap_continue = 1'b1;
    end else begin
        grp_dataflow_parent_loop_proc_fu_158_ap_continue = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_stream_s_read = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_input_stream_s_read;
    end else begin
        input_stream_s_read = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        output_stream_s_write = grp_dataflow_parent_loop_proc_fu_158_output_stream_s_write;
    end else begin
        output_stream_s_write = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        weight_stream_s_read = grp_dataflow_parent_loop_proc_fu_158_weight_stream_s_read;
    end else begin
        weight_stream_s_read = 1'b0;
    end
end
always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln2598_fu_265_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end
assign add_ln2598_fu_255_p2 = (M_fu_62 + 28'd1);
assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];
assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];
assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];
assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];
assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];
assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];
always @ (*) begin
    ap_block_state6_on_subcall_done = ((ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_ready & ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_done) == 1'b0);
end
assign ap_sync_grp_dataflow_parent_loop_proc_fu_158_ap_ready = (grp_dataflow_parent_loop_proc_fu_158_ap_ready | ap_sync_reg_grp_dataflow_parent_loop_proc_fu_158_ap_ready);
assign div_fu_242_p3 = ((tmp_129_reg_292[0:0] == 1'b1) ? p_neg_t_fu_233_p2 : p_lshr_f_cast_fu_239_p1);
assign grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start = grp_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_Pipeline_in_buf_loop_fu_136_ap_start_reg;
assign grp_dataflow_parent_loop_proc_fu_158_ap_start = grp_dataflow_parent_loop_proc_fu_158_ap_start_reg;
assign icmp_ln2598_fu_265_p2 = (($signed(zext_ln2598_fu_261_p1) < $signed(div_reg_307)) ? 1'b1 : 1'b0);
assign output_stream_s_din = grp_dataflow_parent_loop_proc_fu_158_output_stream_s_din;
assign p_lshr_cast_fu_230_p1 = tmp_reg_297;
assign p_lshr_f_cast_fu_239_p1 = tmp_1_reg_302;
assign p_neg_fu_192_p2 = (32'd0 - seq_len);
assign p_neg_t_fu_233_p2 = (29'd0 - p_lshr_cast_fu_230_p1);
assign zext_ln2598_fu_261_p1 = M_fu_62;
endmodule