`timescale 1 ns / 1 ps
// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
 
module Linear_Layer_i4xi4_q_dataflow_in_loop_weight_block_loop (
        output_stream_s_din,
        output_stream_s_full_n,
        output_stream_s_write,
        A_0_address0,
        A_0_ce0,
        A_0_d0,
        A_0_q0,
        A_0_we0,
        A_0_address1,
        A_0_ce1,
        A_0_d1,
        A_0_q1,
        A_0_we1,
        A_1_address0,
        A_1_ce0,
        A_1_d0,
        A_1_q0,
        A_1_we0,
        A_1_address1,
        A_1_ce1,
        A_1_d1,
        A_1_q1,
        A_1_we1,
        A_2_address0,
        A_2_ce0,
        A_2_d0,
        A_2_q0,
        A_2_we0,
        A_2_address1,
        A_2_ce1,
        A_2_d1,
        A_2_q1,
        A_2_we1,
        A_3_address0,
        A_3_ce0,
        A_3_d0,
        A_3_q0,
        A_3_we0,
        A_3_address1,
        A_3_ce1,
        A_3_d1,
        A_3_q1,
        A_3_we1,
        A_4_address0,
        A_4_ce0,
        A_4_d0,
        A_4_q0,
        A_4_we0,
        A_4_address1,
        A_4_ce1,
        A_4_d1,
        A_4_q1,
        A_4_we1,
        A_5_address0,
        A_5_ce0,
        A_5_d0,
        A_5_q0,
        A_5_we0,
        A_5_address1,
        A_5_ce1,
        A_5_d1,
        A_5_q1,
        A_5_we1,
        A_6_address0,
        A_6_ce0,
        A_6_d0,
        A_6_q0,
        A_6_we0,
        A_6_address1,
        A_6_ce1,
        A_6_d1,
        A_6_q1,
        A_6_we1,
        A_7_address0,
        A_7_ce0,
        A_7_d0,
        A_7_q0,
        A_7_we0,
        A_7_address1,
        A_7_ce1,
        A_7_d1,
        A_7_q1,
        A_7_we1,
        A_8_address0,
        A_8_ce0,
        A_8_d0,
        A_8_q0,
        A_8_we0,
        A_8_address1,
        A_8_ce1,
        A_8_d1,
        A_8_q1,
        A_8_we1,
        A_9_address0,
        A_9_ce0,
        A_9_d0,
        A_9_q0,
        A_9_we0,
        A_9_address1,
        A_9_ce1,
        A_9_d1,
        A_9_q1,
        A_9_we1,
        A_10_address0,
        A_10_ce0,
        A_10_d0,
        A_10_q0,
        A_10_we0,
        A_10_address1,
        A_10_ce1,
        A_10_d1,
        A_10_q1,
        A_10_we1,
        A_11_address0,
        A_11_ce0,
        A_11_d0,
        A_11_q0,
        A_11_we0,
        A_11_address1,
        A_11_ce1,
        A_11_d1,
        A_11_q1,
        A_11_we1,
        A_12_address0,
        A_12_ce0,
        A_12_d0,
        A_12_q0,
        A_12_we0,
        A_12_address1,
        A_12_ce1,
        A_12_d1,
        A_12_q1,
        A_12_we1,
        A_13_address0,
        A_13_ce0,
        A_13_d0,
        A_13_q0,
        A_13_we0,
        A_13_address1,
        A_13_ce1,
        A_13_d1,
        A_13_q1,
        A_13_we1,
        A_14_address0,
        A_14_ce0,
        A_14_d0,
        A_14_q0,
        A_14_we0,
        A_14_address1,
        A_14_ce1,
        A_14_d1,
        A_14_q1,
        A_14_we1,
        A_15_address0,
        A_15_ce0,
        A_15_d0,
        A_15_q0,
        A_15_we0,
        A_15_address1,
        A_15_ce1,
        A_15_d1,
        A_15_q1,
        A_15_we1,
        weight_stream_s_dout,
        weight_stream_s_empty_n,
        weight_stream_s_read,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);
output  [304:0] output_stream_s_din;
input   output_stream_s_full_n;
output   output_stream_s_write;
output  [10:0] A_0_address0;
output   A_0_ce0;
output  [3:0] A_0_d0;
input  [3:0] A_0_q0;
output   A_0_we0;
output  [10:0] A_0_address1;
output   A_0_ce1;
output  [3:0] A_0_d1;
input  [3:0] A_0_q1;
output   A_0_we1;
output  [10:0] A_1_address0;
output   A_1_ce0;
output  [3:0] A_1_d0;
input  [3:0] A_1_q0;
output   A_1_we0;
output  [10:0] A_1_address1;
output   A_1_ce1;
output  [3:0] A_1_d1;
input  [3:0] A_1_q1;
output   A_1_we1;
output  [10:0] A_2_address0;
output   A_2_ce0;
output  [3:0] A_2_d0;
input  [3:0] A_2_q0;
output   A_2_we0;
output  [10:0] A_2_address1;
output   A_2_ce1;
output  [3:0] A_2_d1;
input  [3:0] A_2_q1;
output   A_2_we1;
output  [10:0] A_3_address0;
output   A_3_ce0;
output  [3:0] A_3_d0;
input  [3:0] A_3_q0;
output   A_3_we0;
output  [10:0] A_3_address1;
output   A_3_ce1;
output  [3:0] A_3_d1;
input  [3:0] A_3_q1;
output   A_3_we1;
output  [10:0] A_4_address0;
output   A_4_ce0;
output  [3:0] A_4_d0;
input  [3:0] A_4_q0;
output   A_4_we0;
output  [10:0] A_4_address1;
output   A_4_ce1;
output  [3:0] A_4_d1;
input  [3:0] A_4_q1;
output   A_4_we1;
output  [10:0] A_5_address0;
output   A_5_ce0;
output  [3:0] A_5_d0;
input  [3:0] A_5_q0;
output   A_5_we0;
output  [10:0] A_5_address1;
output   A_5_ce1;
output  [3:0] A_5_d1;
input  [3:0] A_5_q1;
output   A_5_we1;
output  [10:0] A_6_address0;
output   A_6_ce0;
output  [3:0] A_6_d0;
input  [3:0] A_6_q0;
output   A_6_we0;
output  [10:0] A_6_address1;
output   A_6_ce1;
output  [3:0] A_6_d1;
input  [3:0] A_6_q1;
output   A_6_we1;
output  [10:0] A_7_address0;
output   A_7_ce0;
output  [3:0] A_7_d0;
input  [3:0] A_7_q0;
output   A_7_we0;
output  [10:0] A_7_address1;
output   A_7_ce1;
output  [3:0] A_7_d1;
input  [3:0] A_7_q1;
output   A_7_we1;
output  [10:0] A_8_address0;
output   A_8_ce0;
output  [3:0] A_8_d0;
input  [3:0] A_8_q0;
output   A_8_we0;
output  [10:0] A_8_address1;
output   A_8_ce1;
output  [3:0] A_8_d1;
input  [3:0] A_8_q1;
output   A_8_we1;
output  [10:0] A_9_address0;
output   A_9_ce0;
output  [3:0] A_9_d0;
input  [3:0] A_9_q0;
output   A_9_we0;
output  [10:0] A_9_address1;
output   A_9_ce1;
output  [3:0] A_9_d1;
input  [3:0] A_9_q1;
output   A_9_we1;
output  [10:0] A_10_address0;
output   A_10_ce0;
output  [3:0] A_10_d0;
input  [3:0] A_10_q0;
output   A_10_we0;
output  [10:0] A_10_address1;
output   A_10_ce1;
output  [3:0] A_10_d1;
input  [3:0] A_10_q1;
output   A_10_we1;
output  [10:0] A_11_address0;
output   A_11_ce0;
output  [3:0] A_11_d0;
input  [3:0] A_11_q0;
output   A_11_we0;
output  [10:0] A_11_address1;
output   A_11_ce1;
output  [3:0] A_11_d1;
input  [3:0] A_11_q1;
output   A_11_we1;
output  [10:0] A_12_address0;
output   A_12_ce0;
output  [3:0] A_12_d0;
input  [3:0] A_12_q0;
output   A_12_we0;
output  [10:0] A_12_address1;
output   A_12_ce1;
output  [3:0] A_12_d1;
input  [3:0] A_12_q1;
output   A_12_we1;
output  [10:0] A_13_address0;
output   A_13_ce0;
output  [3:0] A_13_d0;
input  [3:0] A_13_q0;
output   A_13_we0;
output  [10:0] A_13_address1;
output   A_13_ce1;
output  [3:0] A_13_d1;
input  [3:0] A_13_q1;
output   A_13_we1;
output  [10:0] A_14_address0;
output   A_14_ce0;
output  [3:0] A_14_d0;
input  [3:0] A_14_q0;
output   A_14_we0;
output  [10:0] A_14_address1;
output   A_14_ce1;
output  [3:0] A_14_d1;
input  [3:0] A_14_q1;
output   A_14_we1;
output  [10:0] A_15_address0;
output   A_15_ce0;
output  [3:0] A_15_d0;
input  [3:0] A_15_q0;
output   A_15_we0;
output  [10:0] A_15_address1;
output   A_15_ce1;
output  [3:0] A_15_d1;
input  [3:0] A_15_q1;
output   A_15_we1;
input  [128:0] weight_stream_s_dout;
input   weight_stream_s_empty_n;
output   weight_stream_s_read;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_start;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_done;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_continue;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_idle;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_ready;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_weight_stream_s_read;
wire   [63:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_A_loader_din;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_A_loader_write;
wire   [127:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_B_loader_din;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_B_loader_write;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_start_out;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_start_write;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_0_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_0_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_1_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_1_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_2_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_2_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_3_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_3_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_4_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_4_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_5_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_5_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_6_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_6_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_7_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_7_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_8_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_8_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_9_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_9_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_10_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_10_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_11_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_11_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_12_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_12_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_13_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_13_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_14_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_14_ce0;
wire   [10:0] dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_15_address0;
wire    dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_15_ce0;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_start;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_start_out;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_start_write;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_A_loader_read;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_B_loader_read;
wire   [303:0] systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_C_drainer_din;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_C_drainer_write;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_done;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_ready;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_idle;
wire    systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_continue;
wire    dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_start;
wire    dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_done;
wire    dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_continue;
wire    dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_idle;
wire    dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_ready;
wire    dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_block_C_drainer_read;
wire   [304:0] dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_output_stream_s_din;
wire    dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_output_stream_s_write;
wire    block_A_loader_full_n;
wire   [63:0] block_A_loader_dout;
wire   [2:0] block_A_loader_num_data_valid;
wire   [2:0] block_A_loader_fifo_cap;
wire    block_A_loader_empty_n;
wire    block_B_loader_full_n;
wire   [127:0] block_B_loader_dout;
wire   [2:0] block_B_loader_num_data_valid;
wire   [2:0] block_B_loader_fifo_cap;
wire    block_B_loader_empty_n;
wire    block_C_drainer_full_n;
wire   [303:0] block_C_drainer_dout;
wire   [2:0] block_C_drainer_num_data_valid;
wire   [2:0] block_C_drainer_fifo_cap;
wire    block_C_drainer_empty_n;
wire   [0:0] start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_din;
wire    start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_full_n;
wire   [0:0] start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_dout;
wire    start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_empty_n;
wire   [0:0] start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_din;
wire    start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_full_n;
wire   [0:0] start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_dout;
wire    start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_empty_n;
Linear_Layer_i4xi4_q_dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3 dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_start),
    .start_full_n(start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_full_n),
    .ap_done(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_done),
    .ap_continue(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_continue),
    .ap_idle(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_idle),
    .ap_ready(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_ready),
    .weight_stream_s_dout(weight_stream_s_dout),
    .weight_stream_s_empty_n(weight_stream_s_empty_n),
    .weight_stream_s_read(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_weight_stream_s_read),
    .block_A_loader_din(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_A_loader_din),
    .block_A_loader_num_data_valid(block_A_loader_num_data_valid),
    .block_A_loader_fifo_cap(block_A_loader_fifo_cap),
    .block_A_loader_full_n(block_A_loader_full_n),
    .block_A_loader_write(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_A_loader_write),
    .block_B_loader_din(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_B_loader_din),
    .block_B_loader_num_data_valid(block_B_loader_num_data_valid),
    .block_B_loader_fifo_cap(block_B_loader_fifo_cap),
    .block_B_loader_full_n(block_B_loader_full_n),
    .block_B_loader_write(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_B_loader_write),
    .start_out(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_start_out),
    .start_write(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_start_write),
    .A_0_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_0_address0),
    .A_0_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_0_ce0),
    .A_0_q0(A_0_q0),
    .A_1_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_1_address0),
    .A_1_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_2_address0),
    .A_2_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_3_address0),
    .A_3_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_3_ce0),
    .A_3_q0(A_3_q0),
    .A_4_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_4_address0),
    .A_4_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_4_ce0),
    .A_4_q0(A_4_q0),
    .A_5_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_5_address0),
    .A_5_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_5_ce0),
    .A_5_q0(A_5_q0),
    .A_6_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_6_address0),
    .A_6_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_6_ce0),
    .A_6_q0(A_6_q0),
    .A_7_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_7_address0),
    .A_7_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_7_ce0),
    .A_7_q0(A_7_q0),
    .A_8_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_8_address0),
    .A_8_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_8_ce0),
    .A_8_q0(A_8_q0),
    .A_9_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_9_address0),
    .A_9_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_9_ce0),
    .A_9_q0(A_9_q0),
    .A_10_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_10_address0),
    .A_10_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_10_ce0),
    .A_10_q0(A_10_q0),
    .A_11_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_11_address0),
    .A_11_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_11_ce0),
    .A_11_q0(A_11_q0),
    .A_12_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_12_address0),
    .A_12_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_12_ce0),
    .A_12_q0(A_12_q0),
    .A_13_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_13_address0),
    .A_13_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_13_ce0),
    .A_13_q0(A_13_q0),
    .A_14_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_14_address0),
    .A_14_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_14_ce0),
    .A_14_q0(A_14_q0),
    .A_15_address0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_15_address0),
    .A_15_ce0(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_15_ce0),
    .A_15_q0(A_15_q0)
);
Linear_Layer_i4xi4_q_systolic_array_i4xi4_pack_2x2_16_32_11_true_s systolic_array_i4xi4_pack_2x2_16_32_11_true_U0(
    .ap_start(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_start),
    .start_full_n(start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_full_n),
    .start_out(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_start_out),
    .start_write(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_start_write),
    .block_A_loader_dout(block_A_loader_dout),
    .block_A_loader_empty_n(block_A_loader_empty_n),
    .block_A_loader_read(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_A_loader_read),
    .block_B_loader_dout(block_B_loader_dout),
    .block_B_loader_empty_n(block_B_loader_empty_n),
    .block_B_loader_read(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_B_loader_read),
    .block_C_drainer_din(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_C_drainer_din),
    .block_C_drainer_full_n(block_C_drainer_full_n),
    .block_C_drainer_write(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_C_drainer_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_done(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_done),
    .ap_ready(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_ready),
    .ap_idle(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_idle),
    .ap_continue(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_continue)
);
Linear_Layer_i4xi4_q_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4 dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_start),
    .ap_done(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_done),
    .ap_continue(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_continue),
    .ap_idle(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_idle),
    .ap_ready(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_ready),
    .block_C_drainer_dout(block_C_drainer_dout),
    .block_C_drainer_num_data_valid(block_C_drainer_num_data_valid),
    .block_C_drainer_fifo_cap(block_C_drainer_fifo_cap),
    .block_C_drainer_empty_n(block_C_drainer_empty_n),
    .block_C_drainer_read(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_block_C_drainer_read),
    .output_stream_s_din(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_output_stream_s_din),
    .output_stream_s_full_n(output_stream_s_full_n),
    .output_stream_s_write(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_output_stream_s_write)
);
Linear_Layer_i4xi4_q_fifo_w64_d2_S block_A_loader_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_A_loader_din),
    .if_full_n(block_A_loader_full_n),
    .if_write(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_A_loader_write),
    .if_dout(block_A_loader_dout),
    .if_num_data_valid(block_A_loader_num_data_valid),
    .if_fifo_cap(block_A_loader_fifo_cap),
    .if_empty_n(block_A_loader_empty_n),
    .if_read(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_A_loader_read)
);
Linear_Layer_i4xi4_q_fifo_w128_d2_S block_B_loader_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_B_loader_din),
    .if_full_n(block_B_loader_full_n),
    .if_write(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_block_B_loader_write),
    .if_dout(block_B_loader_dout),
    .if_num_data_valid(block_B_loader_num_data_valid),
    .if_fifo_cap(block_B_loader_fifo_cap),
    .if_empty_n(block_B_loader_empty_n),
    .if_read(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_B_loader_read)
);
Linear_Layer_i4xi4_q_fifo_w304_d2_S block_C_drainer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_C_drainer_din),
    .if_full_n(block_C_drainer_full_n),
    .if_write(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_block_C_drainer_write),
    .if_dout(block_C_drainer_dout),
    .if_num_data_valid(block_C_drainer_num_data_valid),
    .if_fifo_cap(block_C_drainer_fifo_cap),
    .if_empty_n(block_C_drainer_empty_n),
    .if_read(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_block_C_drainer_read)
);
Linear_Layer_i4xi4_q_start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0 start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_din),
    .if_full_n(start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_full_n),
    .if_write(dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_start_write),
    .if_dout(start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_dout),
    .if_empty_n(start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_empty_n),
    .if_read(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_ready)
);
Linear_Layer_i4xi4_q_start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0 start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_din),
    .if_full_n(start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_full_n),
    .if_write(systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_start_write),
    .if_dout(start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_dout),
    .if_empty_n(start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_empty_n),
    .if_read(dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_ready)
);
assign A_0_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_0_address0;
assign A_0_address1 = 11'd0;
assign A_0_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_0_ce0;
assign A_0_ce1 = 1'b0;
assign A_0_d0 = 4'd0;
assign A_0_d1 = 4'd0;
assign A_0_we0 = 1'b0;
assign A_0_we1 = 1'b0;
assign A_10_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_10_address0;
assign A_10_address1 = 11'd0;
assign A_10_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_10_ce0;
assign A_10_ce1 = 1'b0;
assign A_10_d0 = 4'd0;
assign A_10_d1 = 4'd0;
assign A_10_we0 = 1'b0;
assign A_10_we1 = 1'b0;
assign A_11_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_11_address0;
assign A_11_address1 = 11'd0;
assign A_11_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_11_ce0;
assign A_11_ce1 = 1'b0;
assign A_11_d0 = 4'd0;
assign A_11_d1 = 4'd0;
assign A_11_we0 = 1'b0;
assign A_11_we1 = 1'b0;
assign A_12_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_12_address0;
assign A_12_address1 = 11'd0;
assign A_12_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_12_ce0;
assign A_12_ce1 = 1'b0;
assign A_12_d0 = 4'd0;
assign A_12_d1 = 4'd0;
assign A_12_we0 = 1'b0;
assign A_12_we1 = 1'b0;
assign A_13_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_13_address0;
assign A_13_address1 = 11'd0;
assign A_13_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_13_ce0;
assign A_13_ce1 = 1'b0;
assign A_13_d0 = 4'd0;
assign A_13_d1 = 4'd0;
assign A_13_we0 = 1'b0;
assign A_13_we1 = 1'b0;
assign A_14_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_14_address0;
assign A_14_address1 = 11'd0;
assign A_14_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_14_ce0;
assign A_14_ce1 = 1'b0;
assign A_14_d0 = 4'd0;
assign A_14_d1 = 4'd0;
assign A_14_we0 = 1'b0;
assign A_14_we1 = 1'b0;
assign A_15_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_15_address0;
assign A_15_address1 = 11'd0;
assign A_15_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_15_ce0;
assign A_15_ce1 = 1'b0;
assign A_15_d0 = 4'd0;
assign A_15_d1 = 4'd0;
assign A_15_we0 = 1'b0;
assign A_15_we1 = 1'b0;
assign A_1_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_1_address0;
assign A_1_address1 = 11'd0;
assign A_1_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_1_ce0;
assign A_1_ce1 = 1'b0;
assign A_1_d0 = 4'd0;
assign A_1_d1 = 4'd0;
assign A_1_we0 = 1'b0;
assign A_1_we1 = 1'b0;
assign A_2_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_2_address0;
assign A_2_address1 = 11'd0;
assign A_2_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_2_ce0;
assign A_2_ce1 = 1'b0;
assign A_2_d0 = 4'd0;
assign A_2_d1 = 4'd0;
assign A_2_we0 = 1'b0;
assign A_2_we1 = 1'b0;
assign A_3_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_3_address0;
assign A_3_address1 = 11'd0;
assign A_3_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_3_ce0;
assign A_3_ce1 = 1'b0;
assign A_3_d0 = 4'd0;
assign A_3_d1 = 4'd0;
assign A_3_we0 = 1'b0;
assign A_3_we1 = 1'b0;
assign A_4_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_4_address0;
assign A_4_address1 = 11'd0;
assign A_4_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_4_ce0;
assign A_4_ce1 = 1'b0;
assign A_4_d0 = 4'd0;
assign A_4_d1 = 4'd0;
assign A_4_we0 = 1'b0;
assign A_4_we1 = 1'b0;
assign A_5_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_5_address0;
assign A_5_address1 = 11'd0;
assign A_5_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_5_ce0;
assign A_5_ce1 = 1'b0;
assign A_5_d0 = 4'd0;
assign A_5_d1 = 4'd0;
assign A_5_we0 = 1'b0;
assign A_5_we1 = 1'b0;
assign A_6_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_6_address0;
assign A_6_address1 = 11'd0;
assign A_6_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_6_ce0;
assign A_6_ce1 = 1'b0;
assign A_6_d0 = 4'd0;
assign A_6_d1 = 4'd0;
assign A_6_we0 = 1'b0;
assign A_6_we1 = 1'b0;
assign A_7_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_7_address0;
assign A_7_address1 = 11'd0;
assign A_7_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_7_ce0;
assign A_7_ce1 = 1'b0;
assign A_7_d0 = 4'd0;
assign A_7_d1 = 4'd0;
assign A_7_we0 = 1'b0;
assign A_7_we1 = 1'b0;
assign A_8_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_8_address0;
assign A_8_address1 = 11'd0;
assign A_8_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_8_ce0;
assign A_8_ce1 = 1'b0;
assign A_8_d0 = 4'd0;
assign A_8_d1 = 4'd0;
assign A_8_we0 = 1'b0;
assign A_8_we1 = 1'b0;
assign A_9_address0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_9_address0;
assign A_9_address1 = 11'd0;
assign A_9_ce0 = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_A_9_ce0;
assign A_9_ce1 = 1'b0;
assign A_9_d0 = 4'd0;
assign A_9_d1 = 4'd0;
assign A_9_we0 = 1'b0;
assign A_9_we1 = 1'b0;
assign ap_done = dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_done;
assign ap_idle = (systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_idle & dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_idle & dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_idle);
assign ap_ready = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_ready;
assign dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_continue = ap_continue;
assign dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_ap_start = start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_empty_n;
assign dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_continue = 1'b1;
assign dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_ap_start = ap_start;
assign output_stream_s_din = dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_output_stream_s_din;
assign output_stream_s_write = dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_output_stream_s_write;
assign start_for_dataflow_in_loop_weight_block_loop_Loop_bias_loop_proc4_U0_din = 1'b1;
assign start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_din = 1'b1;
assign systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_continue = 1'b1;
assign systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_ap_start = start_for_systolic_array_i4xi4_pack_2x2_16_32_11_true_U0_empty_n;
assign weight_stream_s_read = dataflow_in_loop_weight_block_loop_Loop_init_block_AB_proc3_U0_weight_stream_s_read;
endmodule