`timescale 1 ns / 1 ps
// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
module Linear_Layer_i4xi4_q_Linear_Layer_i4xi4_16_32_2048_11_2048_1024_true_s_A_RAM_2P_URAM_1R1W (
     
    address0, ce0,
    
    q0, 
      
    address1, ce1,
    d1, we1, 
    
     
    reset, clk);
parameter DataWidth = 4;
parameter AddressWidth = 11;
parameter AddressRange = 2048;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0; 
 
input[AddressWidth-1:0] address1;
input ce1;
input[DataWidth-1:0] d1;
input we1; 
input reset;
input clk;
(* ram_style = "hls_ultra" , cascade_height = 1 *)reg [DataWidth-1:0] ram[0:AddressRange-1];
 
always @(posedge clk) 
begin 
    if (ce0) begin
        q0 <= ram[address0];
    end
end 
 
  
always @(posedge clk)  
begin 
    if (ce1) begin
        if (we1) 
            ram[address1] <= d1; 
    end
end 
 
 
endmodule