`timescale 1 ns / 1 ps
// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
 
module Linear_Layer_i4xi4_q_PE_i4xi4_pack_2x2_true_11_false_false_86 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        A_fifo_5_5_dout,
        A_fifo_5_5_num_data_valid,
        A_fifo_5_5_fifo_cap,
        A_fifo_5_5_empty_n,
        A_fifo_5_5_read,
        A_fifo_5_6_din,
        A_fifo_5_6_num_data_valid,
        A_fifo_5_6_fifo_cap,
        A_fifo_5_6_full_n,
        A_fifo_5_6_write,
        B_fifo_5_5_dout,
        B_fifo_5_5_num_data_valid,
        B_fifo_5_5_fifo_cap,
        B_fifo_5_5_empty_n,
        B_fifo_5_5_read,
        B_fifo_5_6_din,
        B_fifo_5_6_num_data_valid,
        B_fifo_5_6_fifo_cap,
        B_fifo_5_6_full_n,
        B_fifo_5_6_write,
        C_fifo_5_5_din,
        C_fifo_5_5_num_data_valid,
        C_fifo_5_5_fifo_cap,
        C_fifo_5_5_full_n,
        C_fifo_5_5_write
);
parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] A_fifo_5_5_dout;
input  [4:0] A_fifo_5_5_num_data_valid;
input  [4:0] A_fifo_5_5_fifo_cap;
input   A_fifo_5_5_empty_n;
output   A_fifo_5_5_read;
output  [7:0] A_fifo_5_6_din;
input  [4:0] A_fifo_5_6_num_data_valid;
input  [4:0] A_fifo_5_6_fifo_cap;
input   A_fifo_5_6_full_n;
output   A_fifo_5_6_write;
input  [7:0] B_fifo_5_5_dout;
input  [5:0] B_fifo_5_5_num_data_valid;
input  [5:0] B_fifo_5_5_fifo_cap;
input   B_fifo_5_5_empty_n;
output   B_fifo_5_5_read;
output  [7:0] B_fifo_5_6_din;
input  [5:0] B_fifo_5_6_num_data_valid;
input  [5:0] B_fifo_5_6_fifo_cap;
input   B_fifo_5_6_full_n;
output   B_fifo_5_6_write;
output  [37:0] C_fifo_5_5_din;
input  [4:0] C_fifo_5_5_num_data_valid;
input  [4:0] C_fifo_5_5_fifo_cap;
input   C_fifo_5_5_full_n;
output   C_fifo_5_5_write;
reg ap_done;
reg ap_idle;
reg ap_ready;
reg A_fifo_5_5_read;
reg A_fifo_5_6_write;
reg B_fifo_5_5_read;
reg B_fifo_5_6_write;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    C_fifo_5_5_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [18:0] c_01_37_fu_129_p2;
reg   [18:0] c_01_37_reg_191;
wire   [18:0] c_11_37_fu_147_p2;
reg   [18:0] c_11_37_reg_196;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_done;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_idle;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_ready;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_5_read;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_5_read;
wire   [7:0] grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_6_din;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_6_write;
wire   [7:0] grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_6_din;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_6_write;
wire   [37:0] grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_0_out;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_0_out_ap_vld;
wire   [37:0] grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_1_out;
wire    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_1_out_ap_vld;
reg    grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start_reg;
reg    ap_block_state1_ignore_call12;
wire    ap_CS_fsm_state2;
reg   [37:0] pack_c_0_loc_fu_52;
reg   [37:0] pack_c_1_loc_fu_48;
wire   [37:0] p_s_fu_153_p3;
reg   [37:0] C_fifo_5_5_din_local;
wire   [37:0] p_0_fu_166_p3;
reg    C_fifo_5_5_write_local;
wire   [0:0] tmp_fu_117_p3;
wire   [18:0] c_01_fu_93_p4;
wire   [18:0] zext_ln1459_fu_125_p1;
wire   [0:0] tmp_37_fu_135_p3;
wire   [18:0] c_11_fu_107_p4;
wire   [18:0] zext_ln1460_fu_143_p1;
wire   [18:0] c_10_fu_103_p1;
wire   [18:0] c_00_fu_89_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;
// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start_reg = 1'b0;
end
Linear_Layer_i4xi4_q_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start),
    .ap_done(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_done),
    .ap_idle(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_idle),
    .ap_ready(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_ready),
    .A_fifo_5_5_dout(A_fifo_5_5_dout),
    .A_fifo_5_5_num_data_valid(5'd0),
    .A_fifo_5_5_fifo_cap(5'd0),
    .A_fifo_5_5_empty_n(A_fifo_5_5_empty_n),
    .A_fifo_5_5_read(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_5_read),
    .B_fifo_5_5_dout(B_fifo_5_5_dout),
    .B_fifo_5_5_num_data_valid(6'd0),
    .B_fifo_5_5_fifo_cap(6'd0),
    .B_fifo_5_5_empty_n(B_fifo_5_5_empty_n),
    .B_fifo_5_5_read(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_5_read),
    .A_fifo_5_6_din(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_6_din),
    .A_fifo_5_6_num_data_valid(5'd0),
    .A_fifo_5_6_fifo_cap(5'd0),
    .A_fifo_5_6_full_n(A_fifo_5_6_full_n),
    .A_fifo_5_6_write(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_6_write),
    .B_fifo_5_6_din(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_6_din),
    .B_fifo_5_6_num_data_valid(6'd0),
    .B_fifo_5_6_fifo_cap(6'd0),
    .B_fifo_5_6_full_n(B_fifo_5_6_full_n),
    .B_fifo_5_6_write(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_6_write),
    .pack_c_0_out(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_0_out),
    .pack_c_0_out_ap_vld(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_0_out_ap_vld),
    .pack_c_1_out(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_1_out),
    .pack_c_1_out_ap_vld(grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_1_out_ap_vld)
);
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (1'b1 == C_fifo_5_5_full_n))) begin
            ap_done_reg <= 1'b1;
        end
    end
end
always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call12))) begin
            grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start_reg <= 1'b1;
        end else if ((grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_ready == 1'b1)) begin
            grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start_reg <= 1'b0;
        end
    end
end
always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == C_fifo_5_5_full_n))) begin
        c_01_37_reg_191 <= c_01_37_fu_129_p2;
        c_11_37_reg_196 <= c_11_37_fu_147_p2;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_0_out_ap_vld == 1'b1))) begin
        pack_c_0_loc_fu_52 <= grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_0_out;
    end
end
always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_1_out_ap_vld == 1'b1))) begin
        pack_c_1_loc_fu_48 <= grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_pack_c_1_out;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_fifo_5_5_read = grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_5_read;
    end else begin
        A_fifo_5_5_read = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_fifo_5_6_write = grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_6_write;
    end else begin
        A_fifo_5_6_write = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B_fifo_5_5_read = grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_5_read;
    end else begin
        B_fifo_5_5_read = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B_fifo_5_6_write = grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_6_write;
    end else begin
        B_fifo_5_6_write = 1'b0;
    end
end
always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        C_fifo_5_5_blk_n = C_fifo_5_5_full_n;
    end else begin
        C_fifo_5_5_blk_n = 1'b1;
    end
end
always @ (*) begin
    if ((1'b1 == C_fifo_5_5_full_n)) begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            C_fifo_5_5_din_local = p_0_fu_166_p3;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            C_fifo_5_5_din_local = p_s_fu_153_p3;
        end else begin
            C_fifo_5_5_din_local = 'bx;
        end
    end else begin
        C_fifo_5_5_din_local = 'bx;
    end
end
always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (1'b1 == C_fifo_5_5_full_n)) | ((1'b1 == ap_CS_fsm_state3) & (1'b1 == C_fifo_5_5_full_n)))) begin
        C_fifo_5_5_write_local = 1'b1;
    end else begin
        C_fifo_5_5_write_local = 1'b0;
    end
end
always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end
always @ (*) begin
    if ((grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end
always @ (*) begin
    if ((1'b0 == C_fifo_5_5_full_n)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end
always @ (*) begin
    if ((1'b0 == C_fifo_5_5_full_n)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end
always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b1 == C_fifo_5_5_full_n))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end
always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end
always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b1 == C_fifo_5_5_full_n))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end
always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == C_fifo_5_5_full_n))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'b1 == C_fifo_5_5_full_n))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end
assign A_fifo_5_6_din = grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_A_fifo_5_6_din;
assign B_fifo_5_6_din = grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_B_fifo_5_6_din;
assign C_fifo_5_5_din = C_fifo_5_5_din_local;
assign C_fifo_5_5_write = C_fifo_5_5_write_local;
assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];
assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];
assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];
assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];
always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end
always @ (*) begin
    ap_block_state1_ignore_call12 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end
assign c_00_fu_89_p1 = pack_c_0_loc_fu_52[18:0];
assign c_01_37_fu_129_p2 = (c_01_fu_93_p4 + zext_ln1459_fu_125_p1);
assign c_01_fu_93_p4 = {{pack_c_0_loc_fu_52[37:19]}};
assign c_10_fu_103_p1 = pack_c_1_loc_fu_48[18:0];
assign c_11_37_fu_147_p2 = (c_11_fu_107_p4 + zext_ln1460_fu_143_p1);
assign c_11_fu_107_p4 = {{pack_c_1_loc_fu_48[37:19]}};
assign grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start = grp_PE_i4xi4_pack_2x2_true_11_false_false_86_Pipeline_PE_LOOP_fu_63_ap_start_reg;
assign p_0_fu_166_p3 = {{c_11_37_reg_196}, {c_01_37_reg_191}};
assign p_s_fu_153_p3 = {{c_10_fu_103_p1}, {c_00_fu_89_p1}};
assign tmp_37_fu_135_p3 = pack_c_1_loc_fu_48[32'd18];
assign tmp_fu_117_p3 = pack_c_0_loc_fu_52[32'd18];
assign zext_ln1459_fu_125_p1 = tmp_fu_117_p3;
assign zext_ln1460_fu_143_p1 = tmp_37_fu_135_p3;
endmodule