// ==================================================
// RTL generated by RapidStream
//
// Copyright 2024 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
/**   Generated by RapidStream   **/
module QuantWrapper_Linear_Layer_q_tb_fsm (
    output wire [31:0] Linear_Layer_i4xi4_q_0___seq_len__q0,
    input wire         Linear_Layer_i4xi4_q_0__ap_done,
    input wire         Linear_Layer_i4xi4_q_0__ap_idle,
    input wire         Linear_Layer_i4xi4_q_0__ap_ready,
    output wire        Linear_Layer_i4xi4_q_0__ap_start,
    input wire         ap_clk,
    output wire        ap_done,
    output wire        ap_idle,
    output wire        ap_ready,
    input wire         ap_rst_n,
    input wire         ap_start,
    output wire [31:0] dequant_layer_q_int_fp32_0___seq_len__q0,
    input wire         dequant_layer_q_int_fp32_0__ap_done,
    input wire         dequant_layer_q_int_fp32_0__ap_idle,
    input wire         dequant_layer_q_int_fp32_0__ap_ready,
    output wire        dequant_layer_q_int_fp32_0__ap_start,
    output wire [63:0] input_loader_r1_ln_iembed_fp32_0___input_mmap_offset__q0,
    output wire [31:0] input_loader_r1_ln_iembed_fp32_0___seq_len__q0,
    input wire         input_loader_r1_ln_iembed_fp32_0__ap_done,
    input wire         input_loader_r1_ln_iembed_fp32_0__ap_idle,
    input wire         input_loader_r1_ln_iembed_fp32_0__ap_ready,
    output wire        input_loader_r1_ln_iembed_fp32_0__ap_start,
    input wire  [63:0] input_mmap_offset,
    output wire [63:0] output_drainer_q_fp32_0___output_mmap_offset__q0,
    output wire [31:0] output_drainer_q_fp32_0___seq_len__q0,
    input wire         output_drainer_q_fp32_0__ap_done,
    input wire         output_drainer_q_fp32_0__ap_idle,
    input wire         output_drainer_q_fp32_0__ap_ready,
    output wire        output_drainer_q_fp32_0__ap_start,
    input wire  [63:0] output_mmap_offset,
    output wire [31:0] quant_layer_r1_ln_iembed_fp32_int4_0___seq_len__q0,
    input wire         quant_layer_r1_ln_iembed_fp32_int4_0__ap_done,
    input wire         quant_layer_r1_ln_iembed_fp32_int4_0__ap_idle,
    input wire         quant_layer_r1_ln_iembed_fp32_int4_0__ap_ready,
    output wire        quant_layer_r1_ln_iembed_fp32_int4_0__ap_start,
    input wire  [63:0] quant_weight_mmap_offset,
    input wire  [31:0] seq_len,
    output wire [63:0] weight_loader_wq_0___quant_weight_mmap_offset__q0,
    output wire [31:0] weight_loader_wq_0___seq_len__q0,
    input wire         weight_loader_wq_0__ap_done,
    input wire         weight_loader_wq_0__ap_idle,
    input wire         weight_loader_wq_0__ap_ready,
    output wire        weight_loader_wq_0__ap_start,
    output wire [31:0] weight_s_loader_wq_0___seq_len__q0,
    output wire [63:0] weight_s_loader_wq_0___weight_s_sum_mmap_offset__q0,
    input wire         weight_s_loader_wq_0__ap_done,
    input wire         weight_s_loader_wq_0__ap_idle,
    input wire         weight_s_loader_wq_0__ap_ready,
    output wire        weight_s_loader_wq_0__ap_start,
    input wire  [63:0] weight_s_sum_mmap_offset
);

wire        global_fsm_ap_done;
wire        global_fsm_ap_start;
wire [63:0] global_fsm_s_input_mmap_offset;
wire [63:0] global_fsm_s_output_mmap_offset;
wire [63:0] global_fsm_s_quant_weight_mmap_offset;
wire [31:0] global_fsm_s_seq_len;
wire [63:0] global_fsm_s_weight_s_sum_mmap_offset;
wire        is_done_Linear_Layer_i4xi4_q_0;
wire        is_done_dequant_layer_q_int_fp32_0;
wire        is_done_input_loader_r1_ln_iembed_fp32_0;
wire        is_done_output_drainer_q_fp32_0;
wire        is_done_quant_layer_r1_ln_iembed_fp32_int4_0;
wire        is_done_weight_loader_wq_0;
wire        is_done_weight_s_loader_wq_0;



__task_fsm_Linear_Layer_i4xi4_q_0 Linear_Layer_i4xi4_q_0 /**   Generated by RapidStream   **/ (
    .ap_clk                (ap_clk),
    .ap_rst_n              (ap_rst_n),
    .global_fsm_ap_done    (global_fsm_ap_done),
    .global_fsm_ap_start   (global_fsm_ap_start),
    .global_fsm_s_seq_len  (global_fsm_s_seq_len),
    .task_ap_done          (Linear_Layer_i4xi4_q_0__ap_done),
    .task_ap_idle          (Linear_Layer_i4xi4_q_0__ap_idle),
    .task_ap_ready         (Linear_Layer_i4xi4_q_0__ap_ready),
    .task_ap_start         (Linear_Layer_i4xi4_q_0__ap_start),
    .task_s_seq_len        (Linear_Layer_i4xi4_q_0___seq_len__q0),
    .to_global_fsm_is_done (is_done_Linear_Layer_i4xi4_q_0)
);


__global_fsm_QuantWrapper_Linear_Layer_q_tb_fsm _ /**   Generated by RapidStream   **/ (
    .ap_clk                                       (ap_clk),
    .ap_done                                      (ap_done),
    .ap_idle                                      (ap_idle),
    .ap_ready                                     (ap_ready),
    .ap_rst_n                                     (ap_rst_n),
    .ap_start                                     (ap_start),
    .global_fsm_ap_done                           (global_fsm_ap_done),
    .global_fsm_ap_start                          (global_fsm_ap_start),
    .global_fsm_s_input_mmap_offset               (global_fsm_s_input_mmap_offset),
    .global_fsm_s_output_mmap_offset              (global_fsm_s_output_mmap_offset),
    .global_fsm_s_quant_weight_mmap_offset        (global_fsm_s_quant_weight_mmap_offset),
    .global_fsm_s_seq_len                         (global_fsm_s_seq_len),
    .global_fsm_s_weight_s_sum_mmap_offset        (global_fsm_s_weight_s_sum_mmap_offset),
    .input_mmap_offset                            (input_mmap_offset),
    .is_done_Linear_Layer_i4xi4_q_0               (is_done_Linear_Layer_i4xi4_q_0),
    .is_done_dequant_layer_q_int_fp32_0           (is_done_dequant_layer_q_int_fp32_0),
    .is_done_input_loader_r1_ln_iembed_fp32_0     (is_done_input_loader_r1_ln_iembed_fp32_0),
    .is_done_output_drainer_q_fp32_0              (is_done_output_drainer_q_fp32_0),
    .is_done_quant_layer_r1_ln_iembed_fp32_int4_0 (is_done_quant_layer_r1_ln_iembed_fp32_int4_0),
    .is_done_weight_loader_wq_0                   (is_done_weight_loader_wq_0),
    .is_done_weight_s_loader_wq_0                 (is_done_weight_s_loader_wq_0),
    .output_mmap_offset                           (output_mmap_offset),
    .quant_weight_mmap_offset                     (quant_weight_mmap_offset),
    .seq_len                                      (seq_len),
    .weight_s_sum_mmap_offset                     (weight_s_sum_mmap_offset)
);


__task_fsm_dequant_layer_q_int_fp32_0 dequant_layer_q_int_fp32_0 /**   Generated by RapidStream   **/ (
    .ap_clk                (ap_clk),
    .ap_rst_n              (ap_rst_n),
    .global_fsm_ap_done    (global_fsm_ap_done),
    .global_fsm_ap_start   (global_fsm_ap_start),
    .global_fsm_s_seq_len  (global_fsm_s_seq_len),
    .task_ap_done          (dequant_layer_q_int_fp32_0__ap_done),
    .task_ap_idle          (dequant_layer_q_int_fp32_0__ap_idle),
    .task_ap_ready         (dequant_layer_q_int_fp32_0__ap_ready),
    .task_ap_start         (dequant_layer_q_int_fp32_0__ap_start),
    .task_s_seq_len        (dequant_layer_q_int_fp32_0___seq_len__q0),
    .to_global_fsm_is_done (is_done_dequant_layer_q_int_fp32_0)
);


__task_fsm_input_loader_r1_ln_iembed_fp32_0 input_loader_r1_ln_iembed_fp32_0 /**   Generated by RapidStream   **/ (
    .ap_clk                         (ap_clk),
    .ap_rst_n                       (ap_rst_n),
    .global_fsm_ap_done             (global_fsm_ap_done),
    .global_fsm_ap_start            (global_fsm_ap_start),
    .global_fsm_s_input_mmap_offset (global_fsm_s_input_mmap_offset),
    .global_fsm_s_seq_len           (global_fsm_s_seq_len),
    .task_ap_done                   (input_loader_r1_ln_iembed_fp32_0__ap_done),
    .task_ap_idle                   (input_loader_r1_ln_iembed_fp32_0__ap_idle),
    .task_ap_ready                  (input_loader_r1_ln_iembed_fp32_0__ap_ready),
    .task_ap_start                  (input_loader_r1_ln_iembed_fp32_0__ap_start),
    .task_s_input_mmap_offset       (input_loader_r1_ln_iembed_fp32_0___input_mmap_offset__q0),
    .task_s_seq_len                 (input_loader_r1_ln_iembed_fp32_0___seq_len__q0),
    .to_global_fsm_is_done          (is_done_input_loader_r1_ln_iembed_fp32_0)
);


__task_fsm_output_drainer_q_fp32_0 output_drainer_q_fp32_0 /**   Generated by RapidStream   **/ (
    .ap_clk                          (ap_clk),
    .ap_rst_n                        (ap_rst_n),
    .global_fsm_ap_done              (global_fsm_ap_done),
    .global_fsm_ap_start             (global_fsm_ap_start),
    .global_fsm_s_output_mmap_offset (global_fsm_s_output_mmap_offset),
    .global_fsm_s_seq_len            (global_fsm_s_seq_len),
    .task_ap_done                    (output_drainer_q_fp32_0__ap_done),
    .task_ap_idle                    (output_drainer_q_fp32_0__ap_idle),
    .task_ap_ready                   (output_drainer_q_fp32_0__ap_ready),
    .task_ap_start                   (output_drainer_q_fp32_0__ap_start),
    .task_s_output_mmap_offset       (output_drainer_q_fp32_0___output_mmap_offset__q0),
    .task_s_seq_len                  (output_drainer_q_fp32_0___seq_len__q0),
    .to_global_fsm_is_done           (is_done_output_drainer_q_fp32_0)
);


__task_fsm_quant_layer_r1_ln_iembed_fp32_int4_0 quant_layer_r1_ln_iembed_fp32_int4_0 /**   Generated by RapidStream   **/ (
    .ap_clk                (ap_clk),
    .ap_rst_n              (ap_rst_n),
    .global_fsm_ap_done    (global_fsm_ap_done),
    .global_fsm_ap_start   (global_fsm_ap_start),
    .global_fsm_s_seq_len  (global_fsm_s_seq_len),
    .task_ap_done          (quant_layer_r1_ln_iembed_fp32_int4_0__ap_done),
    .task_ap_idle          (quant_layer_r1_ln_iembed_fp32_int4_0__ap_idle),
    .task_ap_ready         (quant_layer_r1_ln_iembed_fp32_int4_0__ap_ready),
    .task_ap_start         (quant_layer_r1_ln_iembed_fp32_int4_0__ap_start),
    .task_s_seq_len        (quant_layer_r1_ln_iembed_fp32_int4_0___seq_len__q0),
    .to_global_fsm_is_done (is_done_quant_layer_r1_ln_iembed_fp32_int4_0)
);


__task_fsm_weight_loader_wq_0 weight_loader_wq_0 /**   Generated by RapidStream   **/ (
    .ap_clk                                (ap_clk),
    .ap_rst_n                              (ap_rst_n),
    .global_fsm_ap_done                    (global_fsm_ap_done),
    .global_fsm_ap_start                   (global_fsm_ap_start),
    .global_fsm_s_quant_weight_mmap_offset (global_fsm_s_quant_weight_mmap_offset),
    .global_fsm_s_seq_len                  (global_fsm_s_seq_len),
    .task_ap_done                          (weight_loader_wq_0__ap_done),
    .task_ap_idle                          (weight_loader_wq_0__ap_idle),
    .task_ap_ready                         (weight_loader_wq_0__ap_ready),
    .task_ap_start                         (weight_loader_wq_0__ap_start),
    .task_s_quant_weight_mmap_offset       (weight_loader_wq_0___quant_weight_mmap_offset__q0),
    .task_s_seq_len                        (weight_loader_wq_0___seq_len__q0),
    .to_global_fsm_is_done                 (is_done_weight_loader_wq_0)
);


__task_fsm_weight_s_loader_wq_0 weight_s_loader_wq_0 /**   Generated by RapidStream   **/ (
    .ap_clk                                (ap_clk),
    .ap_rst_n                              (ap_rst_n),
    .global_fsm_ap_done                    (global_fsm_ap_done),
    .global_fsm_ap_start                   (global_fsm_ap_start),
    .global_fsm_s_seq_len                  (global_fsm_s_seq_len),
    .global_fsm_s_weight_s_sum_mmap_offset (global_fsm_s_weight_s_sum_mmap_offset),
    .task_ap_done                          (weight_s_loader_wq_0__ap_done),
    .task_ap_idle                          (weight_s_loader_wq_0__ap_idle),
    .task_ap_ready                         (weight_s_loader_wq_0__ap_ready),
    .task_ap_start                         (weight_s_loader_wq_0__ap_start),
    .task_s_seq_len                        (weight_s_loader_wq_0___seq_len__q0),
    .task_s_weight_s_sum_mmap_offset       (weight_s_loader_wq_0___weight_s_sum_mmap_offset__q0),
    .to_global_fsm_is_done                 (is_done_weight_s_loader_wq_0)
);

endmodule  // QuantWrapper_Linear_Layer_q_tb_fsm