// ==================================================
// RTL generated by RapidStream
//
// Copyright 2024 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================
`timescale 1 ns / 1 ps
/**   Generated by RapidStream   **/
module SLOT_X1Y0_TO_SLOT_X1Y0 (
    input wire  [0:0] Linear_Layer_i4xi4_q_0_ff_0_RS_FF_PP_BODY_0_if_dout,
    output wire [0:0] Linear_Layer_i4xi4_q_0_ff_0_RS_FF_PP_BODY_1_if_dout,
    input wire  [0:0] __merged_task_fsm_SLOT_X0Y0_TO_SLOT_X0Y0_0_ff_0_RS_FF_PP_BODY_0_if_dout,
    output wire [0:0] __merged_task_fsm_SLOT_X0Y0_TO_SLOT_X0Y0_0_ff_0_RS_FF_PP_BODY_1_if_dout,
    input wire  [0:0] __tapa_fsm_unit___ff_0_RS_FF_PP_BODY_0_if_dout,
    output wire [0:0] __tapa_fsm_unit___ff_0_RS_FF_PP_BODY_1_if_dout,
    input wire  [0:0] _antWrapper_Linear_Layer_q_tb_aux_split_aux_1_inst_ff_0_RS_FF_PP_HEAD_if_dout002,
    output wire [0:0] _tWrapper_Linear_Layer_q_tb_aux_split_aux_1_inst_ff_0_RS_FF_PP_BODY_0_if_dout063,
    input wire        ap_clk,
    input wire  [0:0] control_s_axi_U_ff_0_RS_FF_PP_BODY_0_if_dout,
    output wire [0:0] control_s_axi_U_ff_0_RS_FF_PP_BODY_1_if_dout,
    input wire  [0:0] dequant_layer_q_int_fp32_0_ff_0_RS_FF_PP_BODY_0_if_dout,
    output wire [0:0] dequant_layer_q_int_fp32_0_ff_0_RS_FF_PP_BODY_1_if_dout,
    input wire  [0:0] input_loader_r1_ln_iembed_fp32_0_ff_0_RS_FF_PP_BODY_0_if_dout,
    output wire [0:0] input_loader_r1_ln_iembed_fp32_0_ff_0_RS_FF_PP_BODY_1_if_dout,
    input wire  [0:0] input_s_b_stream_ff_0_RS_FF_PP_BODY_0_if_dout,
    output wire [0:0] input_s_b_stream_ff_0_RS_FF_PP_BODY_1_if_dout,
    input wire  [0:0] output_drainer_q_fp32_0_ff_0_RS_FF_PP_BODY_0_if_dout,
    output wire [0:0] output_drainer_q_fp32_0_ff_0_RS_FF_PP_BODY_1_if_dout
);




__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (1),
    .__NEXT_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__PREV_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) Linear_Layer_i4xi4_q_0_ff_0_RS_FF_PP_BODY_1 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (Linear_Layer_i4xi4_q_0_ff_0_RS_FF_PP_BODY_0_if_dout),
    .if_dout (Linear_Layer_i4xi4_q_0_ff_0_RS_FF_PP_BODY_1_if_dout)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (1),
    .__NEXT_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__PREV_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) __merged_task_fsm_SLOT_X0Y0_TO_SLOT_X0Y0_0_ff_0_RS_FF_PP_BODY_1 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (__merged_task_fsm_SLOT_X0Y0_TO_SLOT_X0Y0_0_ff_0_RS_FF_PP_BODY_0_if_dout),
    .if_dout (__merged_task_fsm_SLOT_X0Y0_TO_SLOT_X0Y0_0_ff_0_RS_FF_PP_BODY_1_if_dout)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (2),
    .__NEXT_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__PREV_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) __rs_QuantWrapper_Linear_Layer_q_tb_aux_split_aux_1_inst_ff_0_RS_FF_PP_BODY_0 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (_antWrapper_Linear_Layer_q_tb_aux_split_aux_1_inst_ff_0_RS_FF_PP_HEAD_if_dout002),
    .if_dout (_tWrapper_Linear_Layer_q_tb_aux_split_aux_1_inst_ff_0_RS_FF_PP_BODY_0_if_dout063)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (1),
    .__NEXT_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__PREV_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) __tapa_fsm_unit___ff_0_RS_FF_PP_BODY_1 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (__tapa_fsm_unit___ff_0_RS_FF_PP_BODY_0_if_dout),
    .if_dout (__tapa_fsm_unit___ff_0_RS_FF_PP_BODY_1_if_dout)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (1),
    .__NEXT_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__PREV_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) control_s_axi_U_ff_0_RS_FF_PP_BODY_1 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (control_s_axi_U_ff_0_RS_FF_PP_BODY_0_if_dout),
    .if_dout (control_s_axi_U_ff_0_RS_FF_PP_BODY_1_if_dout)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (1),
    .__NEXT_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__PREV_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) dequant_layer_q_int_fp32_0_ff_0_RS_FF_PP_BODY_1 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (dequant_layer_q_int_fp32_0_ff_0_RS_FF_PP_BODY_0_if_dout),
    .if_dout (dequant_layer_q_int_fp32_0_ff_0_RS_FF_PP_BODY_1_if_dout)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (1),
    .__NEXT_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__PREV_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) input_loader_r1_ln_iembed_fp32_0_ff_0_RS_FF_PP_BODY_1 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (input_loader_r1_ln_iembed_fp32_0_ff_0_RS_FF_PP_BODY_0_if_dout),
    .if_dout (input_loader_r1_ln_iembed_fp32_0_ff_0_RS_FF_PP_BODY_1_if_dout)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (1),
    .__NEXT_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__PREV_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) input_s_b_stream_ff_0_RS_FF_PP_BODY_1 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (input_s_b_stream_ff_0_RS_FF_PP_BODY_0_if_dout),
    .if_dout (input_s_b_stream_ff_0_RS_FF_PP_BODY_1_if_dout)
);


__rs_feed_forward_reg #(
    .DATA_WIDTH    (1),
    .ENABLE_REG    (1),
    .__NEXT_REGION ("SLOT_X0Y0_TO_SLOT_X0Y0"),
    .__PREV_REGION ("SLOT_X1Y1_TO_SLOT_X1Y1"),
    .__REGION      ("SLOT_X1Y0_TO_SLOT_X1Y0")
) output_drainer_q_fp32_0_ff_0_RS_FF_PP_BODY_1 /**   Generated by RapidStream   **/ (
    .clk     (ap_clk),
    .if_din  (output_drainer_q_fp32_0_ff_0_RS_FF_PP_BODY_0_if_dout),
    .if_dout (output_drainer_q_fp32_0_ff_0_RS_FF_PP_BODY_1_if_dout)
);

endmodule  // SLOT_X1Y0_TO_SLOT_X1Y0